### ISSUE TITLE
[Suggestion] Warning when deploying code that goes over SE's character limit

### ISSUE THREAD

**Issue by sirhamsteralot** [malware-dev/MDK-SE#101]
Basically what the title says, give a warning/error if code goes over keens set 100k character limit when trying to deploy.

**Comment by JakenVeina** [comment]
On this note, a cool feature would be to allow for different levels of minification. I recently found myself trying to debug a script that exceeds the character limit without minification, which meant I had to minify it myself to get a reasonable decompilation result in dnSpy. Being able to minify whitespace and/or symbols separately would be pretty useful.

Happy to submit a PR for this myself, if it just involves some refactoring.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
