### ISSUE TITLE
Make options not contain user specific values

### ISSUE THREAD

**Issue by LordMike** [malware-dev/MDK-SE#103]
Hey,

I've just tried out MDK and it looks really good. However, I'm trying to use it in a shared script development setup (github), and there it would suck to commit an `MDK.options` that contains _my_ paths to binary files and outputs. 

The outputs can be handled by environment variables, `%appdata%` etc.., but the path to the `Bin64` folder of SE can't be handled like that.

Maybe have a `MDK.options.user` that doesn't need to be committed, that can contain these values?

Perhaps use a merging strategy, where you go up directory levels (till you hit the root of the drive), and using any `MDK.options` along the way?.. That way, I can have an `MDK.options` outside my repository that will contain my binary path (and it would work for all my repositories too ..)?

**Comment by malware-dev** [comment]
This is already in progress, or rather, pretty much finished. I still need to update the upgrade system, and that will take time since I only have so much time to work on this.

**Comment by malware-dev** [comment]
Fair warning btw. I cannot promise being able to finish this before Easter 😞
