### ISSUE TITLE
Minification is slow, perhaps @luvies can help?

### ISSUE THREAD

**Issue by LordMike** [malware-dev/MDK-SE#104]
I ran MDK and tried minifying the TIM script, and it took quite a while. Which makes me wonder, since the minifier [here](https://github.com/luvies/SpaceEngineers_IngameScriptingBase/blob/master/Build/Processor.cs), which uses `Mono.Cecil` and `ICSharpCode.NRefactory` doesn't have this speed penalty. 

Could there be some options or techniques that MDK could use to speed up their minification?

**Comment by malware-dev** [comment]
Sorry, no. I will not rewrite the minifier for the 3rd time. I don't have that kind of time available.

**Comment by malware-dev** [comment]
Besides, the minification process really only needs to be done on the final build. I _really_ should be including the character limitation removal plugin to MDK somehow, so it'll be easier to test scripts without minifying, until one is ready to create the final build for publication.

**Comment by malware-dev** [comment]
Here, @LordMike, I added this to the wiki:
https://github.com/malware-dev/MDK-SE/wiki/The-Minifier
