### ISSUE TITLE
extension/package.json not found inside zip in VS-Code

### ISSUE THREAD

**Issue by hringriin** [malware-dev/MDK-SE#107]
I know the .vsix file is supposed to be installed on a Windows machine and with Visual Studio. But [Visual-Studio-Code on (Arch) Linux](https://wiki.archlinux.org/index.php/VS_Code) has a Plugin which is said to be able to install .vsix files as well. If I try to do so, the error message `extension/package.json not found inside zip` is shown.

Assuming the vsix file as a container file, is there a way to install the content of that file manually, i.e. where do I have to put the content.

If there is a way to make it run in vs-code, I'd be happy to know.

Regards!

**Comment by malware-dev** [comment]
This package is simply not compatible with anything but Visual Studio.
