### ISSUE TITLE
ShowTextureOnScreenFlag page is missing

### ISSUE THREAD

**Issue by Georgiks** [malware-dev/MDK-SE#109]
https://github.com/malware-dev/MDK-SE/wiki/VRage.Game.GUI.TextPanel.ShowTextOnScreenFlag link is nil.
Access from https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyTextSurface.ShowOnScreen this page

**Comment by malware-dev** [comment]
As mentioned in discord, I repeat it here for the sake of documentation, that page is missing because that type has not been whitelisted.
