### ISSUE TITLE
Allow portions of the script to remain unminified (for configuration)

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#11]
A request has been made to allow for portions of the code to remain unminified when using the minifier, in order to facilitate in-script configuration.

**Comment by malware-dev** [comment]
🤔 It might that be it would be best to refactor the minifier, and make it a selfcontained post-process step. But how, then, would it know what to minify and what not, if it doesn't know the file names? Perhaps MMaster's method is best anyway; by using special comment tags...

**Comment by Skimt** [comment]
What if variables written in Readme.cs overwrites variables that are identical in Program.cs? Would that be possible?

**Comment by malware-dev** [comment]
I'm sorry, no. I will not be making any kind of feature which changes the way a normal C# project would work, due to future plans. Whether the script runs in Space Engineers or a virtual environment the behavior should be identical.
