### ISSUE TITLE
Using RegualrExpressions

### ISSUE THREAD

**Issue by jacob7395** [malware-dev/MDK-SE#113]
Hi,

When using regex I have needed to refrence the funtions/objects in full. If I add

`Using System.Text.RegularExpressions`

Then use a Regex object the code compiles but dosn't run in game. When I refrence the Rexex object in full -

`System.Text.RegularExpressions.Regex ... = ...`

The code runs fine.

I hope there is an easy fix for this if not a warning would save some time.

Thanks :)

**Comment by malware-dev** [comment]
There's nothing I can do about that, because this is how it is in the _game._

**Comment by jacob7395** [comment]
Okay, thanks for the reply.
