### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Fetzi89** [malware-dev/MDK-SE#116]
Hi,
if i try to install the MDK.vsix i get the following error in the log

"13.04.2019 10:42:03 - Er wird nach passenden Produkten gesucht...
13.04.2019 10:42:03 - Installiertes Produkt gefunden - Globaler Pfad
13.04.2019 10:42:03 - Installiertes Produkt gefunden - Visual Studio Community 2019
13.04.2019 10:42:03 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) "

i´ve already tried to reinstall VS, i also installed the .NET desktop development, but there are some selecteable subtypes, do i need any of them?

**Comment by malware-dev** [comment]
If you read the instructions on the install page, you'll see that the extension does _not_ support Visual Studio 2019 yet. I'm working on it, I _hope_ to have a working version after this week but obviously I can't make a promise. As of now, 2017 is required.

**Comment by Fetzi89** [comment]
oooh okay thak you, i thought "at least VS2017" :D . 
okay then i try to get the 2017 edition till you updated it :)
