### ISSUE TITLE
Initial comment block is removed on Deploy

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#12]
Initial comment block is removed and replaced with MDK comment section.

Source before Deploy: 
https://cdn.discordapp.com/attachments/260126085684002826/341281763949150210/unknown.png

Deployed script:
![image](https://user-images.githubusercontent.com/18159679/28755848-08a541d6-7518-11e7-946e-9f87fcdbceda.png)

**Comment by malware-dev** [comment]
Current workaround until a solution is found: Move the initial comment into a file called `Readme.cs`, that is what that file is _for_. There are no guarantees how the deployer will join your script together, so this would be the better solution for introductory comments anyway.
