### ISSUE TITLE
feature: minifier: at option to use only visually distinct characters as replacement

### ISSUE THREAD

**Issue by krypt-lynx** [malware-dev/MDK-SE#120]
This feature will allow to read stack trace from screenshot (bugreport from a script user, for example)

**Comment by malware-dev** [comment]
Sorry. This one is unlikely.

**Comment by krypt-lynx** [comment]
Well. It can be implemented in more generic way: A way to provide some custom list of available replacements

**Comment by malware-dev** [comment]
Actually, thinking about it I won't summarily deny this one, but no promises

**Comment by krypt-lynx** [comment]
Well, actually, I can try to implement this one and replacement map by myself.
by questions is: which file format I should use and how I need to integrate it into MDK?

All chars in file as available characters? Put it into project with special name?
Map as csv file?

**Comment by malware-dev** [comment]
I'm sure there are existing formats for replacement map to consider, there's at least one for JavaScript for sure, it's even integrated into browsers. Consider that people might want to _include_ this map with their deployment. As for the character map, I don't know, I don't have a preference. It might as well just be a text file with all characters printed on a single line.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
