### ISSUE TITLE
feature: standalone console tool

### ISSUE THREAD

**Issue by krypt-lynx** [malware-dev/MDK-SE#121]
It will allow for weirdos such me to use it with it's out deployment scripts.
Or even to use it for non SE projects.

**Comment by krypt-lynx** [comment]
Not an VS plugin, but a tool which I can use separate from it (I'm mostly interested in minifier)
Just a tool which accepts a list of files as parameters, some options (settings/output paths) and does the work.

**Comment by malware-dev** [comment]
Ah. Sorry. Unlikely.
