### ISSUE TITLE
feature: minifier: a way to preserve names, but not formatting

### ISSUE THREAD

**Issue by krypt-lynx** [malware-dev/MDK-SE#122]
All in title. For example, I want to make my script partially editable, but it involves use of enums.

**Comment by malware-dev** [comment]
Ok, so just switch off renaming, essentially. I assume you're asking for a region?

**Comment by krypt-lynx** [comment]
Actually, in any way. regions are easiest to implement, I guess?

**Comment by malware-dev** [comment]
Regions is the way used in MDK to segment the code. Like `#region mdk preserve` and such. _If_ I implement this at some point it would either be global or a region.

**Comment by wmrojer** [comment]
An option to just remove comments and trim leading & trailing spaces would go a long way in making the code smaller but still readable and editable in game. 
To bad the in game script editor don't understand tabs. :(

**Comment by malware-dev** [comment]
Partially solved with the new comment-stripping feature only. Will not go further.
