### ISSUE TITLE
[PRE] [VS2019] Error when attempting to create a new Project

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-SE#124]
When attempting to create a new Ingame Script project I get the following error:

![image](https://user-images.githubusercontent.com/2725436/56363806-48eac680-61ed-11e9-836b-09666bfbf0d7.png)

The project directory is created but empty.

This happens when creating a new solution or attempting to add a new project to an existing solution.

**Comment by Omega1102** [comment]
Same Problem here!

**Comment by hungabal** [comment]
I got this too.
I use VS2019

**Comment by malware-dev** [comment]
Yes it seems like converting extensions to VS2019 isn't as easy as Microsoft claimed it would be... 😒 I'm sorry.
