### ISSUE TITLE
[PRE] [VS2019] New projects default to C# 7 or higher.

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-SE#125]
Since the IngameScriptTemplate.csproj file lacks a `<LangVersion>6</LangVersion>` property, Visual Studio 2019 will default to the latest minor version (7.3).

Since the Analyzer doesn't check for language version, this could lead to the accidental use of unsupported language features.

**Comment by malware-dev** [comment]
It's a bit more unfortunate than that. Not only does VS2019 somehow ignore the template's C#6 setting, but also its .NET4.6.2 setting.

**Comment by VMSBigot** [comment]
Does seeting the required and max work? I checked against 16/16.02 on both Enterprise and Pro and it locked it to 4.6.2/C#6
    <RequiredFrameworkVersion>4.6.2</RequiredFrameworkVersion>
    <MaxFrameworkVersion>4.6.2</MaxFrameworkVersion>

**Comment by malware-dev** [comment]
A-ha. That is probably it, VMSBigot. As for the C# version, seems like that restriction was indeed lost somewhere.

**Comment by malware-dev** [comment]
Oop, no it wasn't... was looking the wrong place.

**Comment by VMSBigot** [comment]
@malware-dev  Anything you need help with?

**Comment by malware-dev** [comment]
This one is fixed I think. Ill take all help I can get but the only _concrete_ thing I can think of right now is to figure out why the mixin project template is ignored in VS2019. I haven't tackled that yet. The new properties branch. 

---- VMSBigot wrote ----

**Comment by VMSBigot** [comment]
Can you checkin Debugging/TriggerTracing? .gitignore got it by the Debug* exclusion

**Comment by malware-dev** [comment]
Done.

**Comment by VMSBigot** [comment]
https://github.com/malware-dev/MDK-SE/pull/132

Duplicate guid was preventing it from loading.

What version of VS are you using to dev?

**Comment by malware-dev** [comment]
2017 since that's the primary version I need to support - most people have that still. Kinda funny though. Why would that fail in 2019 but work just fine in 2017...

**Comment by VMSBigot** [comment]
Oddly I didn't have it work in either version. I submitted a PR (https://github.com/malware-dev/MDK-SE/pull/133) to cleanup a few issues with dev'ing on VS2019. 

Sometimes the only answer is "Visual Studio; that's why."

**Comment by malware-dev** [comment]
Hmm. Maybe it hadn't cleaned up the earlier version properly even though I uninstalled it. Either way, thank you _very_ much for your continued contributions, it is highly appreciated.
