### ISSUE TITLE
[PRE] Unexpected "The MDK.options file could not be found." Analyzer result.

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-SE#126]
Whenever a file containing code is opened, the entire file is marked as an error with the following:

>Severity	Code	Description	Project	File	Line	Suppression State
Error	MissingOptionsRule	The MDK.options could not be loaded.	ShipSystemsManager	C:\Users\Kristian\source\repos\SE-ShipSystemsManager\ShipSystemsManager\Program.cs	2	Active

The error appears to be obsolete since the `MDK.options` file was replaced with `MDK.options.props` and `MDK.paths.props`.

Projects will correctly build and deploy, and the error can be worked around by adding a new file `GlobalSuppressions.debug.cs` with the following content:
```csharp
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Whitelist", "MissingOptionsRule:Missing Or Corrupted Options", Justification = "Workaround until the analyzer is fixed.")]
```

**Comment by malware-dev** [comment]
I was not able to reproduce this issue :(
