### ISSUE TITLE
[PRE] MDKFactory extension class added to deployed code

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#128]
Using a project that I started a LONG time ago and have kept updated, I got issue #127 

Reloaded Vis Studio and no errors.

But I get the MDK factory extension class being added to the deployed code (minifier is on).

}class Ɲ{static Ɲ(){MDKUtilityFramework.Load();}public static void Ĳ(){var Ɯ=MDKFactory.CreateProgram<Program>();
MDKFactory.Run(Ɯ);}

**Comment by Wicorel** [comment]
That was obviously for minified.  Non-minfied added code looks like:

[code]
}
public class TestBootstrapper
{
    // All the files in this folder, as well as all files containing the file ".debug.", will be excluded
    // from the build process. You can use this to create utilites for testing your scripts directly in
    // Visual Studio.

    static TestBootstrapper()
    {
        // Initialize the MDK utility framework
        MDKUtilityFramework.Load();
    }

    public static void Main()
    {
        // In order for your program to actually run, you will need to provide a mockup of all the facilities
        // your script uses from the game, since they're not available outside of the game.

        // Create and configure the desired program.
        var program = MDKFactory.CreateProgram<Program>();
        MDKFactory.Run(program);
    }
[/code]

**Comment by malware-dev** [comment]
Ok, so for some reason it's not reading the ignore config correctly. It would be great if you could provide me with the failing project.

**Comment by malware-dev** [comment]
Oh, you got an error upgrading. Then the options is probably broken, so it doesn't know to ignore the MDK folder.

**Comment by Wicorel** [comment]
This project did not get an error upgrading.. but it was opened after the error occured on another project.

It is simple single file with no minification.

https://github.com/Wicorel/WicoSpaceEngineers/tree/master/WicoModular

It gets the MDKFactory code added at the end.
