### ISSUE TITLE
[PRE] Warning about analyzer not having required netstandard

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#129]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE1003	Analyzer assembly 'c:\users\saett\appdata\local\microsoft\visualstudio\15.0_ce59efb3\extensions\dixykren.l1h\Analyzers\MDKAnalyzer.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.	MDK Orbital Launch		1	Active

**Comment by malware-dev** [comment]
Oh we're back at this one, are we... 😒
