### ISSUE TITLE
Suggestion: Refreshing whitelist runs SE; Add -skipintro to not show intro video

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#130]
When doing "Refresh Whitelist Cache", MDK  runs SE.

However, the intro video starts and runs through.  Then it will exit normally.

If you add -skipintro to the SE command line, it won't run the intro video.

**Comment by malware-dev** [comment]
Ah, yes, good point. I had forgotten the entire "refresh whitelist cache" - and definitely the need to update it for skipintro as I've been using that since day one, so I forgot the intro was even a thing... 😂
