### ISSUE TITLE
[PRE] MDK Analyzer not found

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#131]
Error on building.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'c:\users\saett\appdata\local\microsoft\visualstudio\15.0_ce59efb3\extensions\dixykren.l1h\Analyzers\MDKAnalyzer.dll' could not be found	MDK Craft Control	C:\Users\saett\OneDrive\Documents\Visual Studio 2017\Projects\MDK Craft Control\MDK Craft Control\CSC	1	Active

**Comment by Wicorel** [comment]
Fixed by reloading a couple of times.  

NOTE: may have had to close ALL instances of VS using MDK to get it to update.

**Comment by VMSBigot** [comment]
Do you know if you can reproduce this when its not in a OneDrive sync'd folder? I've run into issues in the past when saving to a OneDrive/DropBox folder in the past with VS due to files being synced in the background.

**Comment by the-vindicar** [comment]
Hmmmm. I got the same issue, and my project was inside Nextcloud sync folder.

**Comment by VMSBigot** [comment]
@the-vindicar I haven't used Nextcloud before, but if you can reliably reproduce the issue, can you try disabling the sync and see if that helps any? @Wicorel's description of fixing it by reloading sounds like a timing related issue and may be due to the sync holding files open or reading/writing to them unexpectedly from VS's standpoint.

**Comment by the-vindicar** [comment]
Well, I gave it a minute to finish syncing and tried again, issue gone.

**Comment by malware-dev** [comment]
Ok this is an interesting discussion as the project I had that failed for a short while was on DropBox. However, the actual DLL it's asking for is not, that's installed in Visual Studio's extension storage area.

**Comment by xBoogieManx** [comment]
I started getting this error after updating to the latest MDK
All my files are local (C drive)
I fixed this by commenting out the commented line and adding the uncommented line in my MDK.path.props file located in [My Project]\MDK folder.



<MDKInstallPath>C:\Users\Jon\AppData\Local\Microsoft\VisualStudio\16.0_b64dcf8c\Extensions\iixgfkgt.2to</MDKInstallPath>

**Comment by xBoogieManx** [comment]
For some reason my "cut an paste" didn't work

So, for clarity, i commented out this path for the MDKInstallPath:
c:\users\jon\appdata\local\microsoft\visualstudio\16.0_b64dcf8c\extensions\lj1knutp.e2m

and added the following path:
C:\Users\Jon\AppData\Local\Microsoft\VisualStudio\16.0_b64dcf8c\Extensions\iixgfkgt.2to

**Comment by malware-dev** [comment]
MDK should have prompted you to update your project, and done that _for_ you. Didn't it?
