### ISSUE TITLE
A class for all turrets

### ISSUE THREAD

**Issue by superpcfan** [malware-dev/MDK-SE#134]
I'm new on GitHub and I hope this is the right place for such a question.

At browsing the web to learn about the SE API I saw a generic class for all (Base and Large) turrets. I don't know the exact name nor the page and i do not find it any more. I went on too fast.
But I'm wondering that in the wiki no such a class like "IMyTurretBaseAndLarge" is listed in the inheritance tree of the turrets.

This class would be nice to fetch all blocks of type "turret". Can someone help and have a look?

**Comment by malware-dev** [comment]
These issues are specifically for the MDK project. If you want help with scripting, you should go to Keen's Discord (https://discordapp.com/invite/KeenSWH) and find the #programming-in-game channel.

I believe the closest thing to what you're asking for is [IMyUserControllableGun](https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyUserControllableGun), but that would probably include fixed weapons as well as turrets. However I don't deal with weapons much. Go ask in Discord. Someone will be able to answer you there.
