### ISSUE TITLE
[Wiki] Profiler guide - no need to backup/copy/overwrite anything

### ISSUE THREAD

**Issue by THDigi** [malware-dev/MDK-SE#135]
https://github.com/malware-dev/MDK-SE/wiki/Advanced-Profiling-The-Game

> Make sure you make a backup of your Bin64 directory before you copy the files, to make restoring them easier. Open the Bin64_Profile folder from the ModSDK's install directory, select everything in this folder and copy all of the files to Bin64 in your game's install directory, overwriting any of the files you're asked to.

That's really unnecessary.
A better way is to junction the Bin64_profile from SDK to the game folder then just run SpaceEngineers.exe from the Bin64_profile (or shortcut on desktop/steam/etc).

`mklink /J "<SE>/Bin64_Profile" "<SDK>/Bin64_Profile"`

**Comment by malware-dev** [comment]
You have access don't you? Fix it ™️ 😛

**Comment by THDigi** [comment]
I don't just edit stuff willy nilly =) but since you asked, it's done :]

**Comment by malware-dev** [comment]
I know you don't, which is why I trusted you with this kind of access 😉 Thanks.
