### ISSUE TITLE
[PRE] MDK deploy option goes away after using once

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#136]
1) Deploy a project.  For sanity use a simple one without minifier.
2) Try to deploy again; menu item is missing

Closing Vis Studio and re-opening make the menu come back again.

**Comment by malware-dev** [comment]
Hm. I've seen this, but not consistently and not in a debugging session yet. Part of the reason why it hasn't been "properly" released. Thanks for confirming.

**Comment by Wicorel** [comment]
Using MDK Craft Control project:

1) on open, the Deploy option appears
2) after a short delay, the option goes away
This is the same time I get a message from github saying the origin is not defined
(causal?  or signifies end of add-in init?)

**Comment by Wicorel** [comment]
Further repo:

1) ONLY happens when I load Vis Studio by opening the SLN from Explorer. (so I can't turn on logging)

2) does NOT happen when I load Vis Studio, then open the SLN.

**Comment by Wicorel** [comment]
So it's not a "Critical" bug..  but annoying..

**Comment by malware-dev** [comment]
Yes, it's critical. Because it happens randomly to me too. But even the log didn't catch it so this is gonna be painful

**Comment by malware-dev** [comment]
I'm wondering if this one is actually the same thing I've tried to fix here. Could you please try and see if this solves the issue?
https://github.com/malware-dev/MDK-SE/releases/tag/1.2.21
