### ISSUE TITLE
IMyProjector.RemainingBlocksPerType and MyDefinitionBase

### ISSUE THREAD

**Issue by senevoldsen** [malware-dev/MDK-SE#139]
MDK marks `MyDefinitionBase` as a prohibited type. But then how are you to use `IMyProjector.RemainingBlocksPerType` ?

I want to get the `IMyItemType`, e.g. using the implicit conversion `IMyItemType itemType = myDefBase.Id`.

**Comment by malware-dev** [comment]
Questions for ingame scripting goes to the Keen discord or forum (most notably the first). These issues are for MDK only. I do not answer such questions here.
https://discordapp.com/invite/keenswh

**Comment by senevoldsen** [comment]
Sorry for my vague question. I was not actually asking for scripting help per se. My intended question was whether it was a bug in MDK that it was marked prohibited. Since from a API standpoint it is would useless for Keen to offer a method you cannot really use anyway. Based on your response I am assuming MDK is correct and the bug is with Keen (or me), and I will take my query there.

Btw, thanks for the tool.

**Comment by malware-dev** [comment]
Well, you can verify _that_ by checking in a PB whether it says it's prohibited or not 🙂 I'm pretty confident that it works right though.
