### ISSUE TITLE
[Wiki] Bad link generated for a Dictionary

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#140]
See https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyProjector.RemainingBlocksPerType

The link generated for Dictionary is not valid.

**Comment by DontNuts** [comment]
Same for List...
e.g. https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMySensorBlock.DetectedEntities

**Comment by malware-dev** [comment]
Yes, it's the same problem. The link should have had an extra `-{number of generic parameters}` generated on it.

**Comment by malware-dev** [comment]
Fixed.
