### ISSUE TITLE
No deploy option

### ISSUE THREAD

**Issue by Scavenjer** [malware-dev/MDK-SE#141]
[Radar fetcher.zip](https://github.com/malware-dev/MDK-SE/files/3137813/Radar.fetcher.zip)
Cannot find the deploy option, even after restart.

**Comment by xBoogieManx** [comment]
Using latest Preview MDK-SE w/ VS 2019 Community (latest patches)
My deploy option disappears as well. But after restarting, it returns ... until i deploy again.

**Comment by malware-dev** [comment]
Yes, this is known and the reason this is still a prerelease. Unfortunately I currently cannot reproduce. I managed at one point, but once I attached the debugger, no dice.

**Comment by malware-dev** [comment]
Yeah. As I suspected, when I opened @Scavenjer's project, it's working just fine... 😒

**Comment by xBoogieManx** [comment]
I'm not sure what change cause this issue to disappear for me, BUT, the Deploy option is not disappearing for me now. Maybe a VS update.

**Comment by malware-dev** [comment]
Maybe. I don't know what to do with this. There's been a few hundred downloads of the preview version and only a very few reports... either people are not reporting or this isn't really a big issue... I'm debating releasing it as a full version.

**Comment by malware-dev** [comment]
#152

**Comment by malware-dev** [comment]
Note to self:

<https://docs.microsoft.com/en-us/visualstudio/extensibility/managing-project-loading-in-a-solution?view=vs-2019>

**Comment by Der-Isy** [comment]
One note about this topic: I have the same problem but if you attach "MDK Deploy All Scripts" to a toolbar, it will stay there, even if the option has disappeared elsewhere.

To do that, edit a toolbar -> customize -> add command -> extras -> "MDK Deploy All Scripts" (found at roughly 2/3 of the list) -> ok. Now you always have the deploy button in your toolbar. (translated the menus from german - could be named differently in english)

**Comment by GeneralSpace** [comment]
@Der-Isy that's genius. I created an MDK menu in the Build toolbar with all the available MDK menu commands. I also mapped MDK Deploy Script to Alt+M, and it works even when the right-click menu option disappears.

**Comment by Der-Isy** [comment]
You're welcome ;)

**Comment by malware-dev** [comment]
Are you guys having this issue _consistently?_ Are you using VS2017 or VS2019?

**Comment by malware-dev** [comment]
Please try this one. It will create a new output window named MDK Dev Output with some runtime information. If it doesn't show, MDK hasn't loaded properly.

[MDK.zip](https://github.com/malware-dev/MDK-SE/files/3317889/MDK.zip)

**Comment by malware-dev** [comment]
Example of output window:
![image](https://user-images.githubusercontent.com/4653628/59978350-b9420980-95db-11e9-9b57-0c72b48e960a.png)

**Comment by MechWipf** [comment]
I am using VS2019 and had even after a restart no Deploy option.
After installing your updated version I got the MDK Dev Console output, but the only Output was "Initializing MDK" and still no deploy possible.

I tried unloading and loading the Project in the Solution Explorer and this triggered the MDK detection which promply complained that my project had to be updated. This brought back the option to deploy and it's still there after several deploys and restarts.

**Comment by malware-dev** [comment]
Speculation: This happens when you start visual studio by opening solutions directly. It does _not_ happen if you open Visual Studio _first_ and opening the solutions after.

**Comment by Der-Isy** [comment]
With the old versions, opening the project file directly was working perfectly fine..

**Comment by malware-dev** [comment]
Yes, because the old version was loaded synchronously, something I was not allowed to continue doing. So I think I understand what is happening now.

**Comment by malware-dev** [comment]
Hi guys. Could you please try and see if this solves the issue?
https://github.com/malware-dev/MDK-SE/releases/tag/1.2.21

**Comment by Der-Isy** [comment]
Seems to work now when opening from project file (VS closed), although the update window took some time to appear.. Tested on VS 2017 15.9.13.. Well done! And blame VS for being stupid ;)
