### ISSUE TITLE
vs code

### ISSUE THREAD

**Issue by tombomb** [malware-dev/MDK-SE#143]
Any way to get this to run in vs code? when installing it gives an error about a missing package.json, Im kinda a nub at vs studio vs vs code extensions, would it be a full rewrite?

**Comment by malware-dev** [comment]
The only thing VS and VS Code has in common is the name.

**Comment by kwilliams1987** [comment]
You can use Visual Studio Community Edition (2017 or 2019) with the extension for free.

https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16

**Comment by tombomb** [comment]
ty ty was just wondering =)

**Comment by malware-dev** [comment]
I'd like to keep this issue open as it is a very common question :-)

**Comment by kwilliams1987** [comment]
[IGS.zip](https://github.com/malware-dev/MDK-SE/files/3182679/IGS.zip)

Here's an absolute minimum project required to be able to build scripts in VSCode (with code completion).

Note that this is in no way a substitute for MDK-SE, but it's a lot better than using something like Notepad++.

You'll have to do your packaging and script deployment yourself by extracting the inner content of the `Program` class.

Be sure to update the `MDKGameBinPath` property in `IGS.csproj` if you have a none-standard install path.
