### ISSUE TITLE
[Minor] Cancelling creation of new ingame script project does not remove created directory

### ISSUE THREAD

**Issue by Georgiks** [malware-dev/MDK-SE#144]
After I've accidentally selected Ingame script as a new project to be added into my solution, but then cancelling it as next MDK dialog window poped out, I could not create project of other type with same name, because the old directory remained.

**Comment by malware-dev** [comment]
That's Visual Studio's doing. I don't create the folders or the files, I've only provided a template. Visual Studio does the rest.

**Comment by malware-dev** [comment]
Hmm. I could check if there's something I can return in the wizard to make Visual Studio clean up after itself, but I kinda doubt it.

**Comment by Georgiks** [comment]
I checked some template (ASP.NET Web Application), when I cancel the second dialog, it removes the directory and returns back to template selection.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
