### ISSUE TITLE
No method for checking whether vessel is moving forward or backward?

### ISSUE THREAD

**Issue by FinlayDaG33k** [malware-dev/MDK-SE#148]
Hii there,

I'm currently trying to make my script figure out whether the ship is moving forward or backwards.  
I have been fiddling with this for about 3 days not but never found a solution on this.  

Considering the game itself seems to be able to see whether it should go forward or backward (when a player presses W or S), it should be possible to have this in the Programmable Block as well right?
Or am I missing something important?

**Comment by malware-dev** [comment]
These issues are only for the MDK extension. If you need help with scripting, please go to Keen's discord (https://discordapp.com/invite/keenswh), #programming-in-game channel, or if you do not want realtime chat, go to Keen's forums (https://forum.keenswh.com/forums/programming-in-game.410940/). The discord _is_ the superior one though.

**Comment by malware-dev** [comment]
Please understand, there's just _me_ here - answering such questions would quickly become a full time job, and I already _have_ one :D
