### ISSUE TITLE
Missing picture for Steam Workshop.

### ISSUE THREAD

**Issue by Elfiwolfe** [malware-dev/MDK-SE#15]
Deploying from MDK to SE.
Then uploading the project will not have 
![thumb](https://user-images.githubusercontent.com/22664974/28860783-c5d4f6ec-7712-11e7-9b41-b7c8f83199af.png)
the c# pictures of scripts on the workshop.

**Comment by malware-dev** [comment]
Fixed for the next release

**Comment by Elfiwolfe** [comment]
It puts thumbwithpromotion into the folder.  I had to rename to thumb to get it to upload to workshop.

**Comment by malware-dev** [comment]
I can't reproduce. How'd you manage that?

**Comment by Elfiwolfe** [comment]
Um.. I think this is a close.. this was a projected created before the fix.

**Comment by malware-dev** [comment]
Ok, I see. Closing again then.
