### ISSUE TITLE
"The type 'Object' is defined in an assembly that is not referenced"

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#150]
Space Engineers is now using .NET Standard assemblies.

Close Visual Studio, delete the .VS folder in your solution folder and restart Visual Studio. That should fix it.

**Comment by OhRly-net** [comment]
the .vs folder keeps coming back whenever i restart Visual Studio, I keep getting this error.

**Comment by malware-dev** [comment]
@OhRly-net I saw you got help on Discord. Just to be clear though: the .vs folder is _supposed_ to come back, it's a cache folder for Visual Studio. It gets corrupted by VS during the transition from .NET Framework assemblies and .NET Standard assemblies. This is the first I hear of the need to add an extra reference though. Strange, it was never a problem for me. You said something on Discord about a reinstall working? Did you still have to add this reference?

**Comment by OhRly-net** [comment]
I had to add the reference to all my existing solutions, a reinstall didn't work because i tested the projects where i already added the reference. I also added it to your template file to create new solutions.

**Comment by malware-dev** [comment]
Ok, gotcha. So apparently I need to add it to the template. Strange how I have no such problem, but I don't care - if it works it works.

**Comment by OhRly-net** [comment]
I still have this warning now though, but at least i can deploy scripts again :)
https://i.imgur.com/g46EfXW.png

**Comment by malware-dev** [comment]
@OhRly-net Yeah _that_ one is known. You can safely ignore it, it's been proven to be a false alarm.
