### ISSUE TITLE
MDK crashes vs 2017/2019 during deploy

### ISSUE THREAD

**Issue by mattftw** [malware-dev/MDK-SE#152]
After upgrading the plugin to the latest version (1.2.15) visual studio crashes during deployment of an ingame script.

Initially I thought the issue may have been because I was using 2017 so i updated to 2019 and discovered the issue persists. Even a newly created blank project will cause a crash.

Steps taken to reproduce crash in screenshots below.

![1](https://user-images.githubusercontent.com/2224474/59160860-1fc62280-8b1a-11e9-8ab8-7b4d663e17de.PNG)
![2](https://user-images.githubusercontent.com/2224474/59160862-22c11300-8b1a-11e9-9db5-2ccc93eba8fe.PNG)
![3](https://user-images.githubusercontent.com/2224474/59160863-25236d00-8b1a-11e9-9773-2438717293dc.PNG)

I understand that there isn't really any information to help debug the issue so if you have any ideas on what further information will be helpful, that would be great.

Attached is ActivityLog.xml which appears to have some maybe related info in entry 361 to 367
[ActivityLog.xml.gz](https://github.com/malware-dev/MDK-SE/files/3269689/ActivityLog.xml.gz)

**Comment by malware-dev** [comment]
Fixed during direct conversation. Thank you, @mattftw.
