### ISSUE TITLE
MyWaypointInfo.FindAll

### ISSUE THREAD

**Issue by citizenslave** [malware-dev/MDK-SE#154]
What is the `source` parameter supposed to be?

**Comment by malware-dev** [comment]
The source is any text that may or may not contain GPS coordinates in text format as dictated by the game (copy a GPS to clipboard and paste in a text editor to see). The function will extract anything matching that pattern. 

I'm sorry, I cannot provide scripting help here, I do not have the extra time. These issues are for MDK only. Please refer to the API list or Keen's discord (where you also will find me more often than not).
