### ISSUE TITLE
[Feature request] Display a warning if character count is nearing or above maximum

### ISSUE THREAD

**Issue by the-vindicar** [malware-dev/MDK-SE#155]
I've read issue #22, but instead of displaying character count preemptively, I suggest displaying it after deployment is complete. I expect it to be much easier, as you have access to complete script.cs file.
To reduce intrusiveness, I suggest altering the message notifying the user about deployment completion depending on whether script size is well below threshold (say, below 95%), nearing threshold or above threshold.

**Comment by ouroborus** [comment]
Related: #101

**Comment by SCBionicle** [comment]
I bet it would be better to display it as a warning that shows in the coding error dialog.

**Comment by malware-dev** [comment]
Duplicate.
