### ISSUE TITLE
Updating from 1.1.31 to 1.2.17 doesn't update my existing project

### ISSUE THREAD

**Issue by Der-Isy** [malware-dev/MDK-SE#156]
Hey Malware,

maybe I'm just stupid or I'm missing something, but after updating to the newest MDK version, my existing project doesn't get updated. Now all my references to SE are broken. Also, the new files don't get added to the project (mdk.paths.props and new mdk.options.props)

Is there something I can do about that or do I need to create a new project with the new MDK? Running it on VS 2017 - 15.9.13

Best regards

**Comment by Der-Isy** [comment]
There you go:

[Test.zip](https://github.com/malware-dev/MDK-SE/files/3297761/Test.zip)

**Comment by Der-Isy** [comment]
On further investigation, it seems, that my MDK doesn't wan't to update at all - not even projects that were created with it.. Also, the script options are missing in the context menu (right click project).

**Comment by malware-dev** [comment]
Did you try completely uninstalling MDK and reinstalling the latest version?

**Comment by Der-Isy** [comment]
Yes, just did it.. I also tried 1.2.15.. Same deal.. When installing 1.1.31 again, I get asked whether I want to update the script when opening it.

**Comment by malware-dev** [comment]
Did you see what the installer said about the installation? Did it actually succeed or fail?

**Comment by Der-Isy** [comment]
It succeeded.. That's what it said at least.. The behavior is the same on both machines, my main pc and my laptop..

![image](https://user-images.githubusercontent.com/40140756/59708343-dbffa700-9204-11e9-860e-dcb5022dc5f1.png)

**Comment by malware-dev** [comment]
Well _that_ one shows the old version.

Try exiting VS and deleting all bin, obj and .vs folders in your project.

**Comment by Der-Isy** [comment]
Whoops.. That was my pc.. as I said.. I rolled back.. Laptop now:

![Anmerkung 2019-06-18 201657](https://user-images.githubusercontent.com/40140756/59708940-0ef66a80-9206-11e9-86bb-ac24628ec9e6.png)

**Comment by Der-Isy** [comment]
Deleted these folders.. Still, no update window appears and all references are broken..

**Comment by malware-dev** [comment]
I don't get it.

**Comment by Der-Isy** [comment]
Me neither.. Does it work on your side? With my test.zip?

**Comment by malware-dev** [comment]
That's Just Another Project:tm:. Nothing special about it. MDK works just fine on my end.

**Comment by malware-dev** [comment]
You could always try VS2019?

**Comment by Der-Isy** [comment]
I could... But as you know: never change a running system ;) Although at least with your MDK, it's not running anymore, so I guess, I'll change it ;)

To conclude: Support for VS 2017 has ended?

**Comment by malware-dev** [comment]
Not intentionally...

Interesting. I stand corrected. It does _not_ ask to update.

I'll take a deeper look tomorrow.

**Comment by malware-dev** [comment]
Wow

Here's where assumptions go blow up right in my face

It doesn't ask to update in VS2019 either

Wtf

**Comment by malware-dev** [comment]
Great. Just great. Loading it in the debug version?

Works like a charm... 😒 Ok, so I'll have to dig deeper tomorrow then. But now at least we know there's _some_ kind of problem here.

**Comment by malware-dev** [comment]
... And now, unloading and reloading the project in VS2019 (without debug) made it work...

**Comment by Der-Isy** [comment]
And I already thought, I did something silly.. Sorry to create work for you, but I'd really like to keep on using your MDK..

**Comment by Der-Isy** [comment]
LOL! Indeed! Unloading the project and loading it again showed the window!

**Comment by malware-dev** [comment]
Ah ffs... 🤔 

Something going wrong during the async load

Crap

**Comment by malware-dev** [comment]
Well, at least it fixes it for _you_ 👍

**Comment by Der-Isy** [comment]
I mean, it's a workaround for the time.. I can live with that for now ;)

**Comment by Der-Isy** [comment]
One other thing though: right clicking a project should give a dropdown with "MDK Script Manager" and "MDK Script Options" at the bottom.. The script options were only there once. I clicked on them and activated the minifier. Now this entry is gone:

![Anmerkung 2019-06-18 232518](https://user-images.githubusercontent.com/40140756/59720938-61448500-9220-11e9-9817-9a1c9b3b3897.png)

**Comment by malware-dev** [comment]
#141

**Comment by malware-dev** [comment]
@Der-Isy MDK isn't getting loading _at all_ when first loading that test project you provided.

**Comment by malware-dev** [comment]
Please try this one. It will create a new output window named MDK Dev Output with some runtime information. If it doesn't show, MDK hasn't loaded properly.

[MDK.zip](https://github.com/malware-dev/MDK-SE/files/3317889/MDK.zip)

**Comment by Der-Isy** [comment]
I don't know, where this window was supposed to appear, but I didn't see anything.. Same deal: opening project from file (VS is closed) - nothing. Close project and reopen it (while VS keeps opened) brings the usual repair/update window..

**Comment by malware-dev** [comment]
It's an output window, so you'll find it in the combo box of the standard output window. Same toolwindow where you see the debug output of a program.

**Comment by malware-dev** [comment]
Ok, I'm starting to believe VS2017 isn't quite as happy with background-loaded addins as VS2019 is. But I can't go back to synchronous loading because VS2019 won't have that. 💢

**Comment by malware-dev** [comment]
![image](https://user-images.githubusercontent.com/4653628/59978341-a62f3980-95db-11e9-801c-3fcb25881844.png)

**Comment by Der-Isy** [comment]
Oh, there it is... So, start by loading a File (VS closed):
> Initializing MDK

Closing project, reopening it:
> Detected the loading of a solution
> Analyzing project...
> Test is a valid MDK project.

**Comment by Der-Isy** [comment]
I will upgrade to VS 2019 then.. But you should point out on the releases page, that VS 2019 is the minimum requirement now..

**Comment by malware-dev** [comment]
I probably should, but I'm not ready to give up just yet.

**Comment by malware-dev** [comment]
Hi guys. Could you please try and see if this solves the issue?
https://github.com/malware-dev/MDK-SE/releases/tag/1.2.21

**Comment by Der-Isy** [comment]
https://github.com/malware-dev/MDK-SE/issues/141#issuecomment-509020105
