### ISSUE TITLE
[Wiki][Request] Would you share the API page generator?

### ISSUE THREAD

**Issue by Sarithule** [malware-dev/MDK-SE#157]
Hello, I am Coren (steam name), author of the Easy Automation script

I was wondering if you would be willing to share the program that grabs all the info from the game and writes the API page?

Ever since the Detailed Info no longer updates, my script has been hobbled and I need to create a way for EA users to access the full functionality of every type of block at run-time. This involves having a block class that contains each block type as a variable that is null. It's constructor takes an IMyTerminalBlock and attempts to cast the block in question to every type using "as". The constructor also gets the type of the block and stores it as a modified string (just the name, not the path). 

Now we can access the properties of that specific block with a delegate dictionary that contains the modified type names and property names of every single block as keys. The values are tuples  that contain a string for the data type and a delegate that takes the block class and returns a string of value of the property requested.

(Dictionary<string, Dictionary<string, MyTuple<string, Func<Block, string>>>>)

this way the properties info can be accessed like this.

var blockDict = BlockDict();
IMyTerminalBlock tBlock = GridTerminalSystem.GetBlockWithName(blockName);
Block block = new Block(tBlock);
string value = blockDict[block.Type][propertyOf].Item2(block);

Creating the Block class and the dictionary by hand is time consuming, error prone, and will easily become out dated when space engineers makes changes during updates. I would really like to create a program that auto generates these using the info directly from the game. Would what you have made to auto generate the API page be able to help me?

**Comment by malware-dev** [comment]
Everything related to MDK and its wiki is already available right here. You're looking for the docgen project. Fair warning though. It's not pretty, it's just a "get the work done" kind of project. 

You should definitely be able to do what you want with code similar to this generator. 


---- Sarithule wrote ----

**Comment by Sarithule** [comment]
Awesome, Thank you! I will check that out.
