### ISSUE TITLE
[Suggestion] Ability to disable backups

### ISSUE THREAD

**Issue by Der-Isy** [malware-dev/MDK-SE#158]
With the newest MDK v1.2+ backups of a project are made whenever you open and "repair" it on another machine. Although this is great and potentially a good idea, switching between machines constantly results in a big pile of backups.

I would like to have the ability to turn these backups off because I delete them anyway. Either as a global setting in the VS options or on a per script basis via the "MDK Script Options". Another way of dealing with that would be to have a definable number of backups or just one backup just in case something goes wrong.

**Comment by malware-dev** [comment]
You shouldn't need to repair on another machine. Don't push the .path.props file.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
