### ISSUE TITLE
Update disabled old solution deploy

### ISSUE THREAD

**Issue by Raibo** [malware-dev/MDK-SE#159]
[IngameScript1.zip](https://github.com/malware-dev/MDK-SE/files/3389793/IngameScript1.zip)

There is one solution, three projects, none of which deploys. I deleted the .vs dir to make sure, nothing changes.
Shows dialog window "Deploy rejected" and then "Project health report".
Repair button did not help, but code style settings (syntax highlighting and colors) went crazy. (Reloading VS eliminated this)

dev console output;
```MDK Command 260 is attempting to retrieve an MDK project
MDK Command 260 retrieved a valid project
Analyzing project...
Analyzing project...
A solution is already loaded on start
Initializing MDK
IngameScript1 is a valid MDK project.
Analyzing project...
solar cos finder is a valid MDK project.
old solar clock: Invalid install path.
old solar clock is a valid MDK project.
old solar clock: The whitelist cache must be updated.
IngameScript1: Invalid install path.
solar cos finder: Invalid install path.
solar cos finder: The whitelist cache must be updated.
IngameScript1: The whitelist cache must be updated.
```
Error when trying to build
```etadata file 'c:\users\raibo\appdata\local\microsoft\visualstudio\15.0_90f8caa0\extensions\xhwouins.qej\Analyzers\MDKAnalyzer.dll' could not be found```

**Comment by malware-dev** [comment]
The addin cannot affect code style settings, that has nothing to do with MDK and what it does, so I will have to ignore that aspect of this. Otherwise, thank you for the report, I will check it out.

**Comment by malware-dev** [comment]
I see. It somehow fails to update the analyzer path right.
And then I restart Visual Studio, and it _does_ work right.
That's strange, and excessively annoying.

The problem, I think, is that the analyzer is stored together with the actual extension. If I somehow could get that installed into the same location every time, this wouldn't be as much of a problem. That, however, requires a custom installer.

**Comment by malware-dev** [comment]
Workaround for now is repair, clean/rebuild all, and restart Visual Studio. That should make your projects work.
