### ISSUE TITLE
Can't deploy without cleaning

### ISSUE THREAD

**Issue by hardliner66** [malware-dev/MDK-SE#160]
If i try to deploy a script a second time, the plugin complains that MDKAnalyzer.dll is missing. If I clean the project and deploy after that it works fine. But still only once, after that I have to clean again.

I'm using vs 2019.

**Comment by malware-dev** [comment]
#159

**Comment by hardliner66** [comment]
Ah, thanks. I reinstalled the plugin and created a new project, which worked as well.

**Comment by malware-dev** [comment]
Yes, clearly the upgrade process is suddenly flawed for some reason.

**Comment by malware-dev** [comment]
Another solution is to exit visual studio, delete the .vs, bin and obj folders and restart.
