### ISSUE TITLE
discord invitation expires 

### ISSUE THREAD

**Issue by feyleth** [malware-dev/MDK-SE#161]
hello,
discord invitation is expires, please can you put new invitation for discord
thank you

**Comment by malware-dev** [comment]
Fixed the link. Incidentally, it's

https://discord.gg/keenswh

**Comment by chrisheib** [comment]
MDK-SE/CONTRIBUTING.md still points to the old, invalid https://discord.gg/0hIE7GirODUqhfIg

**Comment by malware-dev** [comment]
What? Somebody actually _read_ that thing? 👀 

Thanks. Fixed.
