### ISSUE TITLE
can´t install.

### ISSUE THREAD

**Issue by Themiro** [malware-dev/MDK-SE#162]
when i try to install the plugin it just outputs that there is no products to install it to.

Log: 
`8/30/2019 5:21:55 PM - Microsoft VSIX Installer
8/30/2019 5:21:55 PM - -------------------------------------------
8/30/2019 5:21:55 PM - vsixinstaller.exe version:
8/30/2019 5:21:55 PM - 15.9.3043
8/30/2019 5:21:55 PM - -------------------------------------------
8/30/2019 5:21:55 PM - Command line parameters:
8/30/2019 5:21:55 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\amira\AppData\Local\Temp\MDK-2.vsix
8/30/2019 5:21:55 PM - -------------------------------------------
8/30/2019 5:21:55 PM - Microsoft VSIX Installer
8/30/2019 5:21:55 PM - -------------------------------------------
8/30/2019 5:21:55 PM - Initializing Install...
8/30/2019 5:21:55 PM - Extension Details...
8/30/2019 5:21:55 PM - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
8/30/2019 5:21:55 PM - 	Name               : MDK/SE
8/30/2019 5:21:55 PM - 	Author             : Morten Aune Lyrstad
8/30/2019 5:21:55 PM - 	Version            : 1.2.22
8/30/2019 5:21:55 PM - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
8/30/2019 5:21:55 PM - 	Locale             : en-US
8/30/2019 5:21:55 PM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
8/30/2019 5:21:55 PM - 	InstalledByMSI     : False
8/30/2019 5:21:55 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
8/30/2019 5:21:55 PM - 
8/30/2019 5:21:55 PM - 	SignatureState     : Unsigned
8/30/2019 5:21:55 PM - 	Supported Products : 
8/30/2019 5:21:55 PM - 		Microsoft.VisualStudio.Community
8/30/2019 5:21:55 PM - 			Version : [15.0.28307.53,17.0)
8/30/2019 5:21:55 PM - 
8/30/2019 5:21:55 PM - 	References         : 
8/30/2019 5:21:55 PM - 	Prerequisites      : 
8/30/2019 5:21:55 PM - 		-------------------------------------------------------
8/30/2019 5:21:55 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
8/30/2019 5:21:55 PM - 		Name         : Visual Studio core editor
8/30/2019 5:21:55 PM - 		Version      : [15.0,)
8/30/2019 5:21:55 PM - 
8/30/2019 5:21:55 PM - 		-------------------------------------------------------
8/30/2019 5:21:55 PM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
8/30/2019 5:21:55 PM - 		Name         : Roslyn Language Services
8/30/2019 5:21:55 PM - 		Version      : [15.0,)
8/30/2019 5:21:55 PM - 
8/30/2019 5:21:55 PM - Signature Details...
8/30/2019 5:21:55 PM - 	Extension is not signed.
8/30/2019 5:21:55 PM - 
8/30/2019 5:21:55 PM - Searching for applicable products...
8/30/2019 5:21:55 PM - Found installed product - Global Location
8/30/2019 5:21:55 PM - Found installed product - Visual Studio Community 2017
8/30/2019 5:21:55 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
`

**Comment by malware-dev** [comment]
That log is unfortunately less than helpful... I need to ask the obvious question... _Do_  you have Visual Studio 2017 15.9 with C# and .NET Desktop Development installed?

You could also consider installing Visual Studio 2019 instead.

**Comment by Themiro** [comment]
i´ve got Visual Studio 2019 installed with almost all extensions related to .NET or C#

**Comment by malware-dev** [comment]
I'm sorry. It works for most people (including me) and I am by _no_ means an expert on the VSIX installer. I actually have very little control to what happens with that installer, it is controlled completely by Visual Studio when I build the extension. I have _no_ clue why it would not work for you. 

The log says it found Visual Studio 2017 only though. It says nothing about VS2019. Kinda indicating that there's something strange with your installation?
