### ISSUE TITLE
Remote control blocks won't release control over thrusters

### ISSUE THREAD

**Issue by TyTechSci** [malware-dev/MDK-SE#165]
https://steamcommunity.com/sharedfiles/filedetails/?id=1883796648

Test ship for debugging by Keen. Illustrates that programming can't switch from Autopilot to PB control of ship without first coming to a stop or the player manually triggering the Remote control release via pressing WASD etc...

Program runs one pass when you are in flight seat and press 6. 

Every even program loop it runs the remote control, every odd it turns off the RC and does a thruster override.

On odd iterations you can see the RC is autopilot off, no dampners, no thrust control and that the forward thruster is overridden. RC will not release control unless you press WASD or the ship stops, at which point the thruster override starts working and ship goes. You can also manually adjust thruster override when it's in bugged state and no effect.

**Comment by TyTechSci** [comment]
Oh... just realized this is wrong spot for this. Sorry, will leave it up in case I get lucky and someone see and knows a fix or workaround.

**Comment by malware-dev** [comment]
I'm sorry, but I have to close this as I don't want to encourage others asking scripting questions or reporting bugs on my site.
