### ISSUE TITLE
Utility Class with MyGridProgram interface 

### ISSUE THREAD

**Issue by Arkentus** [malware-dev/MDK-SE#168]
_First ! Thanks for your works ! (French guy write in english)_ 

Hello ! 

I do not know if I missed something but i try to make Utility class with MyGridProgram method in it. I've make a very simple exemple, but i want to make some utility class (Stator method extend, Debug to lcdManager,...)

In this exemple, i make a Debug Utility class. This class manage all debug tools i need and show result to LCD (This exemple only initialize the target LCD). 

If i want to use **GridTerminalSystem.GetBlockWithName** in my utility. So i add **MyGridProgram** extend on my class.

-  If i don't extend, Visual don't deploy because "object reference is require". In game, this script return "Object reference not set to an instance of an object : Program.Debug.Inits(String name)"

Program.cs
```
partial class Program : MyGridProgram {

        public Program() {
            //Initialize Debug Screen 
            Debug debug = new Debug();
            debug.Inits("[CODE][DEBUG]");
        }

        public void Main(string argument, UpdateType updateSource) { 
        }  
}
```
Debug.cs
```
partial class Program {

        class Debug : MyGridProgram{

            public void Inits(string name) {

                //Find LCD Block 
                IMyTextPanel lcdDebug = GridTerminalSystem.GetBlockWithName(name) as IMyTextPanel;

                //Check if is find
                if (lcdDebug != null) {
                    lcdDebug.WriteText("LDC Debud Ready !");
                } else {
                    Echo("!Debug: LCDScreen -" + name + "- not found");
                }
            }
        }
    }
```

I think i make an error somewhere, but i don't find where ^^

I hope my question is complete and understandable

**Comment by malware-dev** [comment]
Hello, Arkentus. I'm afraid I do not provide scripting help in these pages. There are far too many of you guys and just one of me. Please ask such questions on Keen's discord.

With that said: you _cannot_ derive from MyGridProgram. It's pointless, it won't get initialized properly and as such holds no meaning.

What you do is pass your Program instance into your subclass.

```csharp
class Debug
{
    Program _program;
    IMyTextPanel _lcdDebug;
    public Debug(Program program, string name)
    {
        _program = program;
        _lcdDebug = _program.GridTerminalSystem.GetBlockWithName(name) as IMyTextPanel;

      ...
    }
}
```

Please ask any followup questions on the Keen discord https://discord.gg/keenswh.

**Comment by Arkentus** [comment]
> Hello, Arkentus. I'm afraid I do not provide scripting help in these pages. First of all, these issues are dedicated to MDK itself - and the Wiki. Secondly, there are far too many of you guys and just one of me. Please ask such questions on Keen's discord, the #programming-in-game channel. You'll often find me there as well.

No problem, I take note and I will not do it anymore ^^ 

> With that said: you cannot derive from MyGridProgram. It's pointless, it won't get initialized properly and as such holds no meaning.
What you do is pass your Program instance into your subclass.

Thank you very much !!! It's work fine ! 

Have nice day and Merry Christmas !!
