### ISSUE TITLE
Wiki - MyIni - Bugs in example code

### ISSUE THREAD

**Issue by Waikiki-Tim** [malware-dev/MDK-SE#169]
I've noticed at least to places in the example code where you don't close the _if_ condition correctly. E.g.
 `if (!_ini.TryParse(Me.CustomData, out result)`. There are two open parentheses but only one close parenthesis.

Easy enough to spot and fix, just thought you might want to know.

**Comment by malware-dev** [comment]
I'm not surprised, and yes, I do indeed want to know. Please let me know exactly where you found them so I don't have to search through all the tutorials... there are a few, after all ;)

**Comment by malware-dev** [comment]
(to be pendantic, those aren't bugs, they're syntax errors. Bugs _compile_ :P )

**Comment by Waikiki-Tim** [comment]
You are correct, syntax errors. :-)

VRage.Game.ModAPI.Ingame.Utilities.MyIni... is that what you need?

**Comment by malware-dev** [comment]
Oh it's in the API documentation? Then there's nothing I can do as those examples are stored in the game's _source code._

**Comment by Waikiki-Tim** [comment]
Oh, ok.
