### ISSUE TITLE
Deployment Class Order

### ISSUE THREAD

**Issue by Elfiwolfe** [malware-dev/MDK-SE#17]
When deploying with a shared Project and Utility Classes.

Items are added in alphabetical order  So any customize variables, Program(), Save(), Main(string argument) gets further down in the code instead of at the front.

May be user training.

**Comment by malware-dev** [comment]
This is a great idea.

**Comment by malware-dev** [comment]
Need to figure out _some_ way of telling the system what order you want something to be added in. Any suggestion will be appreciated.

**Comment by Elfiwolfe** [comment]
Idea is 
Readme.cs
initial section of program to include the leading var and //
Program(), Save(), Main(string argument).
And then the rest of the methods of program. and then classes in alphabetical order.

**Comment by malware-dev** [comment]
It's just too easy to accidentally close these issues, isn't it...

**Comment by malware-dev** [comment]
🤔 Another idea:
An options.json file where you can set these things up:
```json
{
    "buildOrder": [
        "Program.cs",
        "SpecialClass.cs"
    ]
}
```
any unmentioned file is added after these

**Comment by malware-dev** [comment]
But yeah, the absolute minimum should be as you suggest, I agree

Perhaps that's even enough

**Comment by malware-dev** [comment]
Replaced by issues #18 and #19
