### ISSUE TITLE
UpdateType.Antenna is now UpdateType.IGC

### ISSUE THREAD

**Issue by Pharap** [malware-dev/MDK-SE#170]
This wiki page needs to be updated to reflect the change:
https://github.com/malware-dev/MDK-SE/wiki/Continuous-Running-No-Timers-Needed

**Comment by malware-dev** [comment]
No, Antenna is not now IGC. It's been two different things for almost two years. You _are_ right however that the Antenna value is now finally removed.

**Comment by Pharap** [comment]
Regretably I haven't really been keeping up over the last two yeas because my feelings towards the game have grown ever ambivalent and my time has been occupied by other pursuits.
The systems may be different, but the intent and basic principle is the same - 'wireless' ship to ship communication using antennas.

At any rate, debating the semantics would be a waste of both our time, the important thing is that the information has been updated.

**Comment by malware-dev** [comment]
I know, that was not the intent. Both values have existed simultaneously and how they were _used_ when writing scripts for them were very different, so mistaking one for the other would earlier have been a problem. Still, it won't be a prolem any more, as the old value no longer exists - finally.
