### ISSUE TITLE
MDK set up not opening -MAC OS

### ISSUE THREAD

**Issue by ChaxRao** [malware-dev/MDK-SE#171]
I tried to install it on my 2017 MacBook Pro I have visual studio code yet I could not install mdk is it windows / linux only?

**Comment by malware-dev** [comment]
I'm sorry, this is a Visual Studio addin, _not_ Visual Studio Code. They have nothing in common but the name.

**Comment by ChaxRao** [comment]
sorry I made a mistake it was visual studio not vs code Im so used to typing vs code .
I know it an adon I can't open it to apply it even when I open it in vs I get a load of numbers/co ordinates

**Comment by malware-dev** [comment]
Unfortunately Visual Studio for mac is _also_ not really Visual Studio.. It's another IDE Microsoft bought and renamed. Addins for the "real" Visual Studio are not compatible with the Mac version. I'm sorry to disappoint.

**Comment by ChaxRao** [comment]
ok thanks for telling ima get a vm :)
