### ISSUE TITLE
why does Me.GetSurface(0) give me a NullReferenceException?

### ISSUE THREAD

**Issue by LaRoso** [malware-dev/MDK-SE#175]
I would understand it if it happened in VS, as we don't have a Programmable Block there, but why is Me null in the game?

**Comment by malware-dev** [comment]
I do not provide scripting help here. These issues are for MDK itself _only_. Please go to the [Keen discord](https://discordapp.com/invite/keenswh), #programming-in-game, for scripting help. You'll often find me there as well.

Did you derive one of your own classes MyGridProgram yourself or something? You can't do that. Only Program itself uses that class. Me is never null in the game.
