### ISSUE TITLE
Little typing error in "IMyIntergridCommunicationSystem"

### ISSUE THREAD

**Issue by Raibo** [malware-dev/MDK-SE#178]
![image](https://user-images.githubusercontent.com/8547320/74229446-342f7000-4ce4-11ea-942b-3a0e9690b057.png)
Word "will" two times

**Comment by malware-dev** [comment]
I have no control over API documentation. Those are in the source code. Sorry.

**Comment by Raibo** [comment]
Oh, sorry then
