### ISSUE TITLE
i cant create a new in game script

### ISSUE THREAD

**Issue by the7thsun** [malware-dev/MDK-SE#180]
![image](https://user-images.githubusercontent.com/33845972/74988556-bebe5080-5403-11ea-8ef2-2ec94cda22d8.png)

**Comment by kwilliams1987** [comment]
Can you reproduce the error, and then copy the content of the temp file before it's cleaned up?

Might help diagnose the issue.

**Comment by the7thsun** [comment]
> Can you reproduce the error, and then copy the content of the temp file before it's cleaned up?
> 
> Might help diagnose the issue.

Sorry I didn't reply quickly, whenever I go to the temp file it's empty even right after I recreate the issue

**Comment by malware-dev** [comment]
I wish I could help you, but your error is indicating that somehow the indicated file is generated corrupt, maybe through an invalid character. Since you're the first to report this error, I simply have no data to work with... in other words, I _need_ to see the faulty file in order to do anything.

**Comment by the7thsun** [comment]
how can I get that to you

**Comment by malware-dev** [comment]
I have no idea. I didn't even know VS generated anything in the temp folder, and I _certainly_ wouldn't have expected it to have cleaned up before you close the error message.

**Comment by the7thsun** [comment]
I can record a video to show you what I'm doing and see if there is another way to do it

**Comment by malware-dev** [comment]
Worth a try

**Comment by the7thsun** [comment]
ok il do that when I have time

**Comment by the7thsun** [comment]
https://drive.google.com/open?id=1FdBBOAQYB8OfXQvG3Ldt5wc6XKy6iAyT

**Comment by the7thsun** [comment]
running it as administrator doesn't work either

**Comment by the7thsun** [comment]
if this doesn't work can you think of a work around?

**Comment by malware-dev** [comment]
I see you have an & in your path. I'd be willing to bet _that_ is your problem.

**Comment by the7thsun** [comment]
That worked, thanks.
