### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by robm1158** [malware-dev/MDK-SE#185]
WIll this work with VS Code rather than the entire Visual Studio?

**Comment by malware-dev** [comment]
The only correlation between Visual Studio Code and Visual Studio is the name. Apples and oranges. Or rather, peas (VS Code) and water melons (VS)...

So, I'm afraid not.

**Comment by kwilliams1987** [comment]
Visual Studio Community Edition is free and the extension supports it.

https://visualstudio.microsoft.com/vs/community/
