### ISSUE TITLE
Summaries/comments not indented properly on deploy

### ISSUE THREAD

**Issue by THDigi** [malware-dev/MDK-SE#189]
Result: https://gist.github.com/THDigi/a3eb524e0bd971bd3fddca55cc5e7515/ae0751000a6371ec8df188eda49bb73dfbc3655a#file-simpletimersm_example_mergedforpb-cs-L54

The SimpleTimerSM is defined in a referenced mixin project and also has:
`// <mdk sortorder="999" />`
at its start.

**Comment by Gwindalmir** [comment]
Your example looks fine, however I am hitting this issue as well.
I have several "utility classes" in my project, and when deployed, the XML Documentation tags aren't at the same indent level.

Here's a screenshot in-game after pasting the contents from the deploy notification:
![image](https://user-images.githubusercontent.com/1127170/90578737-e6a32c80-e178-11ea-9239-53d1162ea43c.png)

**Comment by THDigi** [comment]
Oh I manually fixed indentation in that gist, I forgot I posted it here =)

You can see in revisions the issue, it's the same as your screenshot yeah.

**Comment by tgkgate** [comment]
Can confirm this is still an issue 2021/09/04 with xmldoc comments

    /// <summary>
    	  /// Class containing extension methods for the following classes<br/>
    	  /// <br/>
    	  /// GridTerminalSystem
    	  /// </summary>
    public static class Extensions

**Comment by tgkgate** [comment]
Can reconfirm as of 2023/05/02 this bug is alive and well.

`/// <summary>
        /// Sets the name of the remote control to orient on (e.g. "remote control 1")<br />
        /// Set to "" to use the first remote control found
        /// </summary>
        /// <remarks>
        ///	Default: Empty String
        /// </remarks>
private const string REMOTE_CONTROL_NAME = "";`

**Comment by malware-dev** [comment]
I'm afraid this does not have a high priority.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
