### ISSUE TITLE
Broken link in "Deploying your script to SE"

### ISSUE THREAD

**Issue by Georgiks** [malware-dev/MDK-SE#190]
First link on wiki page https://github.com/malware-dev/MDK-SE/wiki/Deploying-Your-Script-to-Space-Engineers _**utility and extension classes**_ is broken.

Fix:
"https://github.com/malware-dev/MDK-SE/wiki/Utility-Class-or-Extension-Class%3F"
to
"https://github.com/malware-dev/MDK-SE/wiki/Utility-Class-or-Extension-Class"

**Comment by malware-dev** [comment]
Thank you Sir!
