### ISSUE TITLE
VRageMath.Vector3D.Normalize wrong return type

### ISSUE THREAD

**Issue by bellero2007** [malware-dev/MDK-SE#193]
Hello,
In the wiki the return value of `VRageMath.Vector3D.Normalize` `public double Normalize()` is double. Should it not be a Vector3D? The same in the Visual Studio

[Wiki Page](https://github.com/malware-dev/MDK-SE/wiki/VRageMath.Vector3D.Normalize)

Thanks

**Comment by malware-dev** [comment]
The wiki is autogenerated from the source.

I didn't write the code, and I don't work for Keen ;)

I imagine the idea is that a normalized vector can only be 0-1 anyway, so there's no point in using 64-bit floating point.

**Comment by bellero2007** [comment]
I did not know that the wiki is autogenerated from Keen sources.
Anyway, I think it is wrong because a normalized vector is still a vector, like the `public static Vector3D Normalize(Vector3D value)` method does.

Of course, you can not do anything ;)

**Comment by malware-dev** [comment]
Oh, wait, now I see. The Normalize method is a transformative method. It changes the vector it's _called_ on, it doesn't return a normalized vector.

**Comment by bellero2007** [comment]
oh, my bad :(

Thank you very much
