### ISSUE TITLE
[Documentation] UpdateType.ModApi should be UpdateType.Mod

### ISSUE THREAD

**Issue by Whiplash141** [malware-dev/MDK-SE#194]
`UpdateType.ModApi` listed in https://github.com/malware-dev/MDK-SE/wiki/Continuous-Running-No-Timers-Needed should be `UpdateType.Mod`.

**Comment by Wicorel** [comment]
I changed it.

**Comment by malware-dev** [comment]
Thank you for reporting, Whip, and thanks for fixing, Wic 😄
