### ISSUE TITLE
[Wiki] MyModStorageComponent

### ISSUE THREAD

**Issue by captain828** [malware-dev/MDK-SE#197]
`MyModStorageComponent` is mentioned under [IMyTerminalBlock](https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyTerminalBlock) > Custom Data but can't be found separately.

In VS, trying to create a new `MyModStorageComponent` instance ends up with a "The type or member 'MyModStorageComponent' is prohibited in Space Engineers".

I tried searching for more info on this but the only thing I could find was a Keen post from 2016 that explains how to use this.

So either this is deprecated and the wiki should be updated or this is missing from MDK.

**Comment by malware-dev** [comment]
The API part of the wiki is automatically generated. This is Keen documentation, I have no control over it. It is _not_ missing: It is simply not accessible and never was. It is simply mentioned in Keen's documentation of the property.
