### ISSUE TITLE
Description Deleted? 

### ISSUE THREAD

**Issue by GHYNG** [malware-dev/MDK-SE#198]
I am new to this MDK page, and I found this tool very helpful for developing ingame scripts. However I found that most descriptions for interfaces, properties, and methods under Sandbox.ModAPI.Ingame namespace were deleted. Those descriptions were very helpful because it is hard to guess the purposes of those members just by their names. Was it a temporary measure (to delete those descriptions) or was I looking at a wrong place for interface API?

**Comment by malware-dev** [comment]
Very few of the descriptions have _ever_ existed. I am at the mercy of Keen in this case. _They_ are the ones writing the API descriptions, not me.

You say they were _deleted_ though. Do you have an example of a file that had descriptions but no longer do? The API listing is automatic, so I need to check if something went wrong or if Keen actually removed them.

**Comment by malware-dev** [comment]
I found it. The XML files in question had been removed by Steam. Once I verified the game they were back. The documentation should have returned now.

**Comment by GHYNG** [comment]
Thank you for your reply! 

Those descriptions were in the block interfaces in ingame namespace until 4 days ago, and they are now back again. 

Anyway, thank you for your information and your work here, very helpful!
