### ISSUE TITLE
[WIKI] Missing method in MyItemType documentation

### ISSUE THREAD

**Issue by bdk02** [malware-dev/MDK-SE#201]
In the documentation of the VRage.Game.ModAPI.Ingame.MyItemInfo you mentioned a GetItemInfo method for VRage.Game.ModAPI.Ingame.MyItemType. But in the documentation of VRage.Game.ModAPI.Ingame.MyItemType it is not listed under methods even though it exists and can be used in scripts.

**Comment by malware-dev** [comment]
Hm. Seems like something might be off in the generator. Dunno when I can get a chance to fix that.

**Comment by malware-dev** [comment]
Nope. This extension method is here. https://github.com/malware-dev/MDK-SE/wiki/VRage.Game.ModAPI.Ingame.MyPhysicalInventoryItemExtensions_ModAPI

So - this is _not_ wrong.
