### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by lizelive** [malware-dev/MDK-SE#203]
Is it possible to use MDK for creating mods as well? Having support for shared library between my mods without a lot of simlinking would be amazing. Also the automatic whitelist checking and code minimization (helps a bit against code bandits).
How might this be done?
Thank you,
Liz

**Comment by malware-dev** [comment]
This tool is designed for ingame scripts only, I'm afraid. I asked about the desire for mod support in this tool at some point and got a pretty much negative response so I never extended it that way.
