### ISSUE TITLE
MDK throws exception on deploy if project was created inside the IngameScripts\local directory

### ISSUE THREAD

**Issue by Gwindalmir** [malware-dev/MDK-SE#204]
I created my project inside of **%appdata%\SpaceEngineers\IngameScripts\Local**; not thinking anything about it.
However on deploy, it throws an exception.
In retrospec, I should not have created a project in the this location... but that's how I work with mods, so I didn't think anything of it.

> MDK.Build.BuildException: Error writing final script for C:\Users\Daniel\AppData\Roaming\SpaceEngineers\IngameScripts\local\LCARSTerminal\LCARSTerminal.csproj ---> System.IO.IOException: The process cannot access the file 'C:\Users\Daniel\AppData\Roaming\SpaceEngineers\IngameScripts\local\LCARSTerminal\thumb.png' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
>    at MDK.Build.BuildModule.WriteScript(Project project, String output, String script) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 211
>    --- End of inner exception stack trace ---
>    at MDK.Build.BuildModule.WriteScript(Project project, String output, String script) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 219
>    at MDK.Build.BuildModule.<BuildAsync>d__27.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 182
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 118
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MDK.MDKPackage.<DeployAsync>d__47.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359

**Comment by malware-dev** [comment]
Well, so don't create the project there then 😄 

The system isn't designed for that. What has happened here is that the game locked the thumb texture so the plugin couldn't overwrite it. Besides, the entire system is designed for the publish system. It combines multiple .cs files into one. So it really does make no sense at all to have the project there.

There's nothing to fix here.

**Comment by Gwindalmir** [comment]
I don't think I had the game running.
I certainly never loaded the scripts in-game browser.

**Comment by malware-dev** [comment]
What locked it isn't really important, it was locked. But it really doesn't make sense to make a project there no matter how you twist and turn it, as opposed to mods, ingame script .cs-files aren't directly compatible. They _must_ be processed.
