### ISSUE TITLE
CodeSimplifier changes access modifiers for unreferenced base classes/interfaces

### ISSUE THREAD

**Issue by jeffgriffin** [malware-dev/MDK-SE#207]
A public base class or base interface of a class or interface that is accessed outside Program (e.g. in an extension method), will drop its public access modifier, because the base class/interface itself is not accessed.  The result is an inconsistent accessibility error during "Check Code".

**Comment by malware-dev** [comment]
You are going to have to provide a specific example, as I'm not seeing a problem.

**Comment by jeffgriffin** [comment]
This will do it.
https://gist.github.com/jeffgriffin/4b84bb61ad11206d1daeec1baedeacee

**Comment by malware-dev** [comment]
Ah. Well, easy solution. Don't nest the types, you don't need to ;)

Workaround, anyway.

**Comment by jeffgriffin** [comment]
I'm not sure I follow.  They need to be nested in Program, don't they?

**Comment by malware-dev** [comment]
Not at all. An extension class is just another type. Doesn't _have_ to be just an extension type, can be _any_ type. MDK deals with it.

**Comment by malware-dev** [comment]
Hm. This might be problematic. Seems like it's an issue in the Roslyn SymbolFinder class. It's not reporting the interface usage.

**Comment by jeffgriffin** [comment]
I see.  Unfortunately this opens up a Pandora's Box of additional issues post-minification, including more instances of this one.  In the meantime it's working to reference the base class in a trivial way, like this:
public static class ExtensionClass
{
    static Program.ITestBase _appeaseMinifier;
    ...

**Comment by jeffgriffin** [comment]
Moving them all out is problematic for a number of reasons, but at any rate I think I fixed the bug.
