### ISSUE TITLE
MyIni possible unintentional loss of the three dashes used to terminate a configuration stream

### ISSUE THREAD

**Issue by MMiller-2020** [malware-dev/MDK-SE#210]
(I am new to GitHub and posting on SE scripting, please advise if I am not following protocol)
I am experimenting with the MyIni feature and I noticed something that may not be intentional.
I initialize my programmable block’s custom data as follows.

Custom Data before running Main()
[SectionOne]
Setting1=true
Setting2=true
— (three dashes here)

If I add a comment to the configuration the three dashes are discarded.

Custom Data after running Main()
;SectionComment
[SectionOne]
Setting1=true
Setting2=true
	<- dashes are gone

If I have content after the three dashes they are preserved

Custom Data before running Main()
[SectionOne]
Setting1=true
Setting2=true
— (three dashes here)
End Content

Custom Data after running Main()

;SectionComment
[SectionOne]
Setting1=true
Setting2=true
— (three dashes here)
End Content

Shouldn’t the three dashes be preserved regardless if there data after them?

While I have only use the set comment members to write to the ini configuration I expect this may be happening with any write to the configuration.

Here is my test code
public Program()
{
    if (Me.CustomData == "")//write out the Script section name and configuration settings
    {
       //Me.CustomData = "[SectionOne]\nSetting1=true\nSetting2=true\n---\nEnd Content";

       Me.CustomData = "[SectionOne]\nSetting1=true\nSetting2=true\n---";
    }
}

public void Main(string argument, UpdateType updateSource)
{
    MyIni _ini = new MyIni();
    MyIniParseResult result;

    if (!_ini.TryParse(Me.CustomData, out result))
    {
        Echo($"CustomData error:\nLine {result}");
        throw new Exception(result.ToString());
    }

  // _ini.SetSectionComment("SectionOne","SectionComment");
  //  _ini.SetComment("SectionOne","Setting1","Setting1Comment");
    _ini.SetEndComment("EndComment");
    Me.CustomData = _ini.ToString();
}

**Comment by malware-dev** [comment]
I do not provide scripting help here. These issues are for MDK itself and the documentation _only_. Please go to the [Keen discord](https://discordapp.com/invite/keenswh), #programming-in-game, for scripting help. You'll often find me there as well.

That said, this is expected behavior, as the three dashes are only added if the parser is filled with EndContent. No EndContent, no dashes.

**Comment by MMiller-2020** [comment]
Thank you for the quick response and answer.
