### ISSUE TITLE
[Feature Request] Lite Minifier Option

### ISSUE THREAD

**Issue by SCBionicle** [malware-dev/MDK-SE#212]
Add an option that does everything short of renaming symbols to enable better debugging.

Note: I already started on coding this, but I've yet to debug and test it. Before I continue, I just wanted to see if @malware-dev is okay with it.

**Comment by malware-dev** [comment]
Sure, why not. Although it's probably better to debug using the [limitation removal plugin](https://github.com/malware-dev/MDK-SE/wiki/The-Minifier#but-the-minifier-is-slow) so you can debug with the completely unminified version.

**Comment by SCBionicle** [comment]
@malware-dev I have linked a pull request (#213) to this issue. Could you review it and see what you think? I couldn't get it to properly build due to my inexperience with VS plugins so a certain commit might have to be reverted. (The commit was linked in the PR)

**Comment by malware-dev** [comment]
So, @SCBionicle, I discovered a problem. You didn't update the script properties page with the new minifier. Also, at the same time, the minifier text should probably be Lite (No Renaming) so people don't have to guess.

**Comment by SCBionicle** [comment]
@malware-dev what part of code do I need to change for that?

**Comment by malware-dev** [comment]
ScriptOptionsDialog

**Comment by SCBionicle** [comment]
@malware-dev I just tested #214, it appears the think you pointed out now works with the changes you suggested.
