### ISSUE TITLE
[Minor] Minifier removes comments at the end of the mdk preserve region

### ISSUE THREAD

**Issue by i72jilej** [malware-dev/MDK-SE#216]
I've noticed that when deploying the script, the comments right at the end of the "mdk preserve" region are removed as if they were outside the region.
It would be something like this:
```
#region mdk preserve
//This comment is preserved

string aVariable = "This variable is preserved too";

//A comment in the middle

string anotherVar = "This variable is preserved too";

//This comment is removed
//This one too
#endregion
//The rest of the script goes here
```

The deployed script would look like this:
```
//This comment is preserved

string aVariable = "This variable is preserved too";

//A comment in the middle

string anotherVar = "This variable is preserved too";
Program(){...}void Save(){...}void Main(string A,UpdateType B){...}
```

**Comment by malware-dev** [comment]
Yes, this is because the region is removed and the comments are _attached_ to said region.

I'm sorry, I won't fix this. Just move the comments below the #endregion.
