### ISSUE TITLE
Wizard class does not exist in the assembly?

### ISSUE THREAD

**Issue by Mateo35** [malware-dev/MDK-SE#218]
Sorry, I'm stuck trying to create an ingame script project. Whenever I press create I get this error. I downloaded the MDKmaster but wasn't sure what to do with it.
![E](https://user-images.githubusercontent.com/60317629/99863818-851e9f80-2b65-11eb-8b92-fc8cc4fa81e3.png)

**Comment by idtx314** [comment]
@Mateo35 I've also just run into this exact error message while trying to create a new project. This looks like it was closed quickly, what was the solution? I tried re-installing the MDK just for giggles but that doesn't seem to have helped.

**Comment by Mateo35** [comment]
Sorry about closing without my solution. What I did was repair Visual Studio through Visual Studio Installer (can be found in start menu). And restarted my PC. Then just to make sure I also reinstalled the MDK, and that seemed to work. :)

**Comment by Mateo35** [comment]
Side note. I also updated my Visual Studio to the latest version (was only a version or two behind)

**Comment by idtx314** [comment]
I'd already installed the latest MDK, so I tried updating Visual Studio through the Visual Studio Installer. That did the trick for me. Thanks!

**Comment by malware-dev** [comment]
Thank you guys. I will add a notice to the download page that the newest VS2019 is required.
