### ISSUE TITLE
[WIKI] "IMyMotorSuspension" missing property "Speed Limit"

### ISSUE THREAD

**Issue by mlq1819** [malware-dev/MDK-SE#219]
Property Id: "Speed Limit"
Property TypeName: "Single" (float)
Known method of accessing value: 
IMyMotorSuspension.GetValue<float>("Speed Limit"); //(value between 0 and 360)
Property Name: unknown

Note: There appears to be a bug attached to changing the wheel's speed limit through changing this property, as it sometimes fails to limit propulsion properly if it was previously set to full power. This bug is not thoroughly tested.

**Comment by malware-dev** [comment]
You'll have to report game bugs to Keen, not me 🙂As for the terminal property, it's already listed. https://github.com/malware-dev/MDK-SE/wiki/List-Of-Terminal-Properties-and-Actions#imymotorsuspension
