### ISSUE TITLE
Unable to create project (MDK.Services.IngameScriptWizard does not exist)

### ISSUE THREAD

**Issue by azazar** [malware-dev/MDK-SE#220]
When I attempt to create project following error message appears.

![MDK error](https://user-images.githubusercontent.com/2816075/100600956-0a971200-3313-11eb-8330-5f1a92db7d08.png)

**Comment by malware-dev** [comment]
See https://github.com/malware-dev/MDK-SE/issues/218

and the release notes stating that you need the newest VS2019.

**Comment by storm-ace** [comment]
Had same issue after updating to 16.8.2 > it fix itself happy coding 👍
