### ISSUE TITLE
Error on InGame Script 

### ISSUE THREAD

**Issue by HajItsFunBon** [malware-dev/MDK-SE#223]
when im trying to make project with InGame Script i get this error:

the file vstemplate refers to a wizard class 'MDK.services.IngameScriptWizzard' that does not exist in the assembly 'MDK, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed62e...........' 

(comment if you need the dotted part)

i use VS community 2017 15.9.30

i tried using VS 2019 16.7.4, same issue

**Comment by malware-dev** [comment]
Please read the release notes.
https://github.com/malware-dev/MDK-SE/releases
