### ISSUE TITLE
VS Community 2017 15.9.30 - Unable to create project (MDK.Services.IngameScriptWizard does not exist)

### ISSUE THREAD

**Issue by gargan26** [malware-dev/MDK-SE#224]
I am unable to create a project using Visual Studio Community 2017 15.9.30. The following error message appears:

![Error Message](https://user-images.githubusercontent.com/2816075/100600956-0a971200-3313-11eb-8330-5f1a92db7d08.png)

**Comment by malware-dev** [comment]
Does nobody read release notes? 😛

**Comment by gargan26** [comment]
Uh... Your release notes for the latest release as of this post specify in part:
"MDK now requires at least Visual Studio 2017 15.9."

Well, this is incorrect as I have VS 2017 15.9.30 and it doesn't work...

**Comment by malware-dev** [comment]
It also says this:

**KNOWN ISSUE:**

After upgrading your project, VS might complain that it does not find the MDK analyzer. This is caused by the project not getting properly upgraded. I don't know why the upgrade wizard doesn't get run properly, I don't have this problem myself. Unloading / reloading your project manually, by right-clicking the project node, should force the upgrade wizard to run.

**Comment by malware-dev** [comment]
Please let me know if it works, and I'll alter the note to include the wizard specifically as well - _or_ remove the 2017 support text.

**Comment by gargan26** [comment]
I saw that part as well but I have no project to upgrade. This is my first time even trying to create a project.  Incidentally, I'm only using 2017 because when I went to install VS2019, the installer said that it was incompatible with my version of windows 10.  I am using an extremely old version (1511) and just never upgraded.  Version 1703 or later is required to install and use VS2019 so I guess it's time to upgrade.

**Comment by malware-dev** [comment]
Ah crap.

Then I guess 2017 support really _is_ dead. Sorry about that.

**Comment by gargan26** [comment]
No worries. 😄

**Comment by austinvaness** [comment]
I am getting this error in Visual Studio Community 2019.

**Comment by malware-dev** [comment]
Make sure your VS is fully up to date.

**Comment by malware-dev** [comment]
The latest MDK version how has a VS2019 16.8 requirement built in.
