### ISSUE TITLE
[Bug] Error Creating New Project

### ISSUE THREAD

**Issue by SCBionicle** [malware-dev/MDK-SE#226]
# Actual Behavior
MDK throws a missing template error whenever I create a new MDK project in an existing MDK solution. (Haven't tested it in a new solution)

# Expected Behavior
After filling out the new project dialog, the MDK dialog should appear without an error.

# Screenshots
![mdk broken](https://user-images.githubusercontent.com/17008727/103578671-9a912400-4e9c-11eb-9d50-57009b4142d9.png)

# Context
I have previously cloned and contributed to the project and I've pulled the latest changes and ran VS in debug mode. I am unable to reproduce this error. My guess is that it was a bad compile for the installer.

**Comment by malware-dev** [comment]
People usually get it to work after updating Visual Studio.

**Comment by SCBionicle** [comment]
I'm on visual studio 2019, but not on the latest patch version, largely because I don't like how the version control was revamped. But, if you think this is worth just closing, go ahead. I figure that either something went wrong with installing or compiling but compiling the plugin locally on my machine fixes the problem.

**Comment by malware-dev** [comment]
Yes I _did_ mean update Visual Studio 2019. No new compile etc. necessary, just doing the update fixes it for them.
