### ISSUE TITLE
[Feature Request] Ability to Develop Script without local install

### ISSUE THREAD

**Issue by TheZombie1999** [malware-dev/MDK-SE#227]
I am playing space engineers of the Nvidia GForce Now plattform, because it doesnt run on my laptop nativly.
But i still want to develop space engineers scripts on my maschine which is not possible because to setup the install the binary path is required. Would it be possible to have the ability to develope scripts without an local install ?

**Comment by malware-dev** [comment]
You _need_ the binaries. I can't copy the binaries for you, that'd be illegal.
