### ISSUE TITLE
Update window gives mixed information

### ISSUE THREAD

**Issue by XkyRauh** [malware-dev/MDK-SE#23]
In the 1.0 release 2017/08/12, The Tools-->MDK menu has two options: "Blueprint Manager" and "Check for Updates."

Clicking "Check for Updates" opens a dialogue box with the header "New MDK Version Available," but the text in the dialogue explains "There's no new version available for download at this time."  (Should the header change?)

Furthermore, the grey text that follows advises me to "Go to Tools | Options | MDK | SE to set your options for update checks" ... but as explained above, there are only two menu options: "Blueprint Manager" and "Check for Updates."  I do not have "SE" as an available option!

**Comment by malware-dev** [comment]
Hah...

Yes, the title should change.

That should be Tools | Options | MDK/SE, not MDK | SE...
