### ISSUE TITLE
[Feature request] copy compiled script to clipboard

### ISSUE THREAD

**Issue by azazar** [malware-dev/MDK-SE#230]
It's quite annoying to choose script from the game menu on each minor script update. It takes more clicks and button presses to get script updated in pb, than just pasting it the ingame editor.

**Comment by Kuraanal** [comment]
When your deploy your script from VS, there is an infobox appearing on top of the window offering you to copy your deployed script to the clipboard.

> Your script has been deployed.    **Show Me    -    Copy script to the Clipboard**

**Comment by malware-dev** [comment]
I was just about to say the same, thanks, Kuraanal 😄

**Comment by azazar** [comment]
Thank you. I didn't notice that.
