### ISSUE TITLE
Running the game through SELauncher no longer possible?

### ISSUE THREAD

**Issue by KcHNST** [malware-dev/MDK-SE#231]
I have been unable to successfully load or create a save when starting the game through the SELauncher [as described here](https://github.com/malware-dev/MDK-SE/wiki/Advanced-dnSpy-tips-and-tricks#seeing-local-variables-when-code-is-paused) (both with dnSpy attached and without it).

The game simply crashes when loading an existing save or throws some generic error when creating a new empty world.

Is this supposed to work still? Maybe it should be removed if it's no longer possible.

**Comment by malware-dev** [comment]
I'm afraid this is not my code - and I also don't use this method of debugging. Maybe @THDigi - the author of that tutorial - knows more.

**Comment by malware-dev** [comment]
@KcHNST I asked Equinox, the original author of SELauncher, and he says it works perfectly fine for him...

**Comment by KcHNST** [comment]
Thank you for looking into this, as long as it works for others I can just assume it's something on my end.
I'll come back to this if I find out the cause.

**Comment by THDigi** [comment]
We've found a better way just now, simply using a text file =) I've updated the guide with the file and info.
