### ISSUE TITLE
Add mentions of of MyWindTurbine adn MyHydrogenEngine to API reference?

### ISSUE THREAD

**Issue by AdrianDeWinter** [malware-dev/MDK-SE#232]
The Wind Turbine and Hydrogen Engine blocks have non-whitelisted types, but no specific interfaces (Why, Keen, Why?).
Thus, they naturally dont show up in the Scripting API reference.

I was wondering if it would be possible to manually mention that fact somewhere, i recently spent quite some time trying to figure out why i could not find their interfaces and was starting to think the API ref was out of date.

[IMyPowerProducer](https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyPowerProducer) might be a good place for this, since they both do inherit that one

Thanks in advance :)

PS: any idea why those two dont get their own interfaces? I wanted to tally up power output by block type and ended up string-comparing the result of GetType().Name, seems like an unnessecary workaround if they just had those interfaces

**Comment by malware-dev** [comment]
The documentation is automatically generated from the source.  I have no way to add manual documentation.

**Comment by malware-dev** [comment]
To answer the question of why; that's two-fold. 1. Because they've been heading toward a more component based system than a class based system for a while now. 2. Because the programmable block has no priority for them. Not _low_ priority... _no_ priority.
