### ISSUE TITLE
Can im build clear script file?

### ISSUE THREAD

**Issue by tuturox91** [malware-dev/MDK-SE#237]
Can im build/save clear script file (without using, namespace) and save into SpaceEngineers\IngameScripts\local\Script_1?
Im write the script and want save clear version into local script folder. I can this automaticaly or me need manuale clear file from "Using", "namespace" block and then  save him in InagameScript folder????

**Comment by Wicorel** [comment]
Use the 'Deploy' feature.

This does exactly what you asked.
