### ISSUE TITLE
Missing System.Collections.Immutable in MDK.paths.probs on repair prompt.

### ISSUE THREAD

**Issue by OnuxNemori** [malware-dev/MDK-SE#238]
When creating a project the following is inserted in MDK.paths.probs.
`
		<Reference Include="System.Collections.Immutable">
			<HintPath>$(MDKGameBinPath)\System.Collections.Immutable.dll</HintPath>
			<Private>false</Private>
		</Reference>
`
When repairing an installation, after the repair prompt (Reason is the paths file is in the git ignore to prevent issues with other systems), it does not add this, resulting in unable to build untill that is added.

Edit: Wrongly formed sentence.

**Comment by malware-dev** [comment]
_That_ explains a thing or two! Thank you!
