### ISSUE TITLE
Wiki - Vector Transformations with World Matrices - picture change request

### ISSUE THREAD

**Issue by scanerang** [malware-dev/MDK-SE#240]
2 of the pictures on the Wiki/Math/Vector Transformations with World Matrices page show how matrixes are put together. The pictures use the forward and left direction and needs to add an negative sign since SE use Right and Backwards. This really annoys me. The pictures below changes the named arrows, the text in the matrix and swaps the colors (to match the orientation gui when placing blocks). 

![MDK-SE Wiki matrix format](https://user-images.githubusercontent.com/85294685/120663097-07c7d600-c48a-11eb-850b-c89ccbc6c7cd.png)

![MDK-SE Wiki vector transformation](https://user-images.githubusercontent.com/85294685/120665542-28912b00-c48c-11eb-94f6-4bb67e0f1660.png)

**Comment by malware-dev** [comment]
@Whiplash141

**Comment by MrNoms** [comment]
I second this suggestion and wish to add to it. The multiplications that refer to transforming between the frames of reference are ambiguous.

It is obvious that a vector in the world space has components `[X,Y,Z]`. It is clear that `vector.X`  refers to the `X` component of  `vector` in world space.

But, how is a vector constructed in local space? `[vector.X, vector.Y, vector.Z]` is unclear. Does a local space vector have the form `[vector.Backwards, vector.Right, vector.Up]`? Is it `[vector.Up, vector.Backwards, vector.Right]`?

The answer can be inferred with a little math, but we should only need to double check our code, not diagrams in documentation.

**Comment by Whiplash141** [comment]
> The pictures use the forward and left direction and needs to add an negative sign since SE use Right and Backwards.

It is simply a different representation of the same math. Forward-left-up is more intuitive imo, the *only* difference is a sign change. If you want to add secondary diagrams with both representations presented, that's fine.

> we should only need to double check our code, not diagrams in documentation.

The diagrams are _not_ incorrect. If you want a sentence describing what each component of a vector means in local space, I can add that. However, it is not necessary as Vector3D has all of the base directions exposed via static members.

**Comment by scanerang** [comment]
> It is simply a different representation of the same math. Forward-left-up is more intuitive imo, the _only_ difference is a sign change.

While I agree that Forward Left Up makes more sense, space engineers uses Right, Up, Back as the basis vectors. I think most people will have an easier time if double negatives are avoided. Adding arbitrary sign flips will increase the likelihood that a plus or minus get mixed up.

**Comment by Whiplash141** [comment]
> I think most people will have an easier time if double negatives are avoided. 

I've found the opposite. The reason I opted for Forward-Left-Up is beginners were confused about Backwards-Right-Up. Forward-Left-Up easily lends itself to using the right hand to intuitively visualize the orientation of entities.

> Adding arbitrary sign flips will increase the likelihood that a plus or minus get mixed up.

And again, you needn't directly interface with these signs. If you are setting things in a matrix, you just access it via the setters (ex: `mat.Forward = new Vector3D(1,0,0)`). You certainly don't need to mess with matrix signs when you are _given_ the World Matrix by accessing an entity. Whilst the signs are important, for the actual transformations, you aren't really directly touching them.

**Comment by MrNoms** [comment]
After actually interfacing with the world matrix and its data type, it's even more obvious how these vectors work and how to build their components.

However, I still stand my statement regarding the representation of "Transforming Block Vector to World Vector." Local vector components may _technically_ have accessible `X`, `Y`, and `Z` members, the local space is shown with `-Left`, `Up`, and `-Front` components.

**Comment by Whiplash141** [comment]
Figures have been updated, note about local space components added, figure with alternative representations added.

**Comment by Whiplash141** [comment]
Marking as resolved.
