### ISSUE TITLE
Project Health Report locks VS

### ISSUE THREAD

**Issue by DarkEyeDragon** [malware-dev/MDK-SE#243]
I added the Extention to VS 2019 and after setting the binaries path (incorrectly apparently) it pops up with a repair popup which fails to repair and then pops up another window, but you are unable to close the windows cuz the focus one is under the other popup.

https://user-images.githubusercontent.com/6131099/127740289-d1f457e0-80f9-4714-8bef-5990c5c56df8.mp4

Edit: there also seems no easy way to change those settings from within VS without the popups

**Comment by malware-dev** [comment]
Yes you can.

tools|options|MDK/SE to change the basic path.

**Comment by malware-dev** [comment]
To fix your existing projects, open the mdk.paths.props, change the MDKUseGameBinPath to yes, and point MDKGameBinPath to the right path.

Steam has changed a file format, which has broken the repair mechanism.

**Comment by malware-dev** [comment]
Fixed in 1.4.9
