### ISSUE TITLE
Cannot find Entities.Blocks.MySpaceProjector

### ISSUE THREAD

**Issue by peetya** [malware-dev/MDK-SE#244]
First of all, thank you for your work, it's so much fun to write scripts in Visual Studio, thanks to your wiki and VS plugin :)

I am trying to access a Console Block that has been added in one of the DLCs (Decorative Blocks). Its class is `Entities.Blocks.MySpaceProjector` but I cannot import it in Visual Studio, therefore I cannot access its API.

Can you help me, how can I import it? :) Or is it missing for reason?

Thank you in advance!

**Comment by malware-dev** [comment]
I don't help with scripts here. This is _just_ for the MDK system.

Go to Keen's Discord, the #programming-in-game channel, to get scripting help. You'll often find me there as well as several knowledgeable people.

You're trying to access types that aren't allowed in a programmable block. You don't use those classes ijn ingame scripts. You use the _interfaces._ IMyProjector in this case.
