### ISSUE TITLE
Cannot find MDK settings

### ISSUE THREAD

**Issue by Altereusse** [malware-dev/MDK-SE#248]
I just recently installed and reinstalled the extension and made sure my Visual Studio is up to date and it still displays the same message saying that it cannot find the MDK settings and that I need to make sure my VS is up to date.

This only occurs when I try to create a normal In game script project but when I create a Mixin, nothing is wrong. 

I have no clue as to why this may be. I've even looked at the other issues to maybe find an answer but I couldn't.

**Comment by malware-dev** [comment]
I am sorry. A few people have been getting this problem over the years and I have never been able to ascertain the reason for it.

Does your project folder have any unusual characters in them or something?

**Comment by Altereusse** [comment]
No.
I've tried relocating the projects to different folders but it doesn't do anything either.

**Comment by Omeged** [comment]
Same problem here. Only Mixin works but normal Ingame script is impossible. All possible fixes seems to work only in VS2017 but not in 2019 (like gacutil).

**Comment by RickBardock** [comment]
Having the same problem, I'm on an old laptop, one that cannot even load space engineers. perhaps this is the problem?
I've attempted to install all the required extensions, but that hasn't fixed the issue, I'm posting
[dd_VSIXInstaller_20220918184315_2810.log](https://github.com/malware-dev/MDK-SE/files/9595401/dd_VSIXInstaller_20220918184315_2810.log)
 my log file attached here.

**Comment by malware-dev** [comment]
@RickBardock Your log is the Vsix installer log and has nothing to do with the error mentioned in this issue? You seem to be trying to install MDK on VS2022 which won't work (as specified several places in the documentation).

**Comment by RickBardock** [comment]
Thank you for the response in general and for it being so fast, either didn't see it or didn't read it. Now for the other issue.. Downloading visual studios older and correct version from Microsoft.  Gives me the options to download visual studios 2017 v. 15.0 and v. 15.9, which one? Also, the options of visual studios team explorer 2017 or agents for visual studios 2017 or visual C++ redistributable for visual studios 2017, out of these 5 options, which one is the correct one, for myself and anyone who comes after, thank you.
