### ISSUE TITLE
MDK RC stripping off #endregion

### ISSUE THREAD

**Issue by Elfiwolfe** [malware-dev/MDK-SE#25]
#endregion being stripped off.  starting with RC version.  was working on prerelease versions

example.
shared project autogyro
namespace IngameScript {
    partial class Program {
        #region Autogyro  
        // http://forums.keenswh.com/threads/aligning-ship-to-planet-gravity.7373513/#post-1286885461  

        double CTRL_COEFF = 0.5;
...
        void gyrosOff() {
            for (int i = 0; i < gyros.Count; ++i) { gyros[i].GyroOverride = false; }
        }
        #endregion
        //endof autogyro

the #endregion and //endof autogyro are getting stripped off during the code being packaged together.

**Comment by malware-dev** [comment]
Ah crap, regions. Those are a PITA to work with in Roslyn. I have a sneaking suspicion what this is all about. I'll see if I can fix it.

In the mean time, don't use regions :P

**Comment by Elfiwolfe** [comment]
I just // out the regions and it works.
Not even sure what region does.  But it is a bug so gave you info.
