### ISSUE TITLE
Cannot install MDK-SE

### ISSUE THREAD

**Issue by Matliam08** [malware-dev/MDK-SE#253]
I cannot install, when attempting install
Install Failed
"The install of 'MDK/SE' was not successful for all the selected products. For more information, click on the install log link at the bottom of the dialog.
MDK/SE
       this extension is not installable on any currently installed products."
Shows up, I viewed the Install Log and it showed this...
       
  1/28/2022 8:23:02 PM - Microsoft VSIX Installer
1/28/2022 8:23:02 PM - -------------------------------------------
1/28/2022 8:23:02 PM - vsixinstaller.exe version:
1/28/2022 8:23:02 PM - 17.0.5226-preview5
1/28/2022 8:23:02 PM - -------------------------------------------
1/28/2022 8:23:02 PM - Command line parameters:
1/28/2022 8:23:02 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\potatoisland\Downloads\MDK(4).vsix
1/28/2022 8:23:02 PM - -------------------------------------------
1/28/2022 8:23:02 PM - Microsoft VSIX Installer
1/28/2022 8:23:02 PM - -------------------------------------------
1/28/2022 8:23:03 PM - Initializing Install...
1/28/2022 8:23:03 PM - Extension Details...
1/28/2022 8:23:03 PM - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
1/28/2022 8:23:03 PM - 	Name               : MDK/SE
1/28/2022 8:23:03 PM - 	Author             : Morten Aune Lyrstad
1/28/2022 8:23:03 PM - 	Version            : 1.4.10
1/28/2022 8:23:03 PM - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
1/28/2022 8:23:03 PM - 	Locale             : en-US
1/28/2022 8:23:03 PM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
1/28/2022 8:23:03 PM - 	InstalledByMSI     : False
1/28/2022 8:23:03 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
1/28/2022 8:23:03 PM - 
1/28/2022 8:23:03 PM - 	SignatureState     : Unsigned
1/28/2022 8:23:03 PM - 	Supported Products : 
1/28/2022 8:23:03 PM - 		Microsoft.VisualStudio.Community
1/28/2022 8:23:03 PM - 			Version : [16.8,17.0)
1/28/2022 8:23:03 PM - 			ProductArchitecture : x86
1/28/2022 8:23:03 PM - 
1/28/2022 8:23:03 PM - 	References         : 
1/28/2022 8:23:03 PM - 	Prerequisites      : 
1/28/2022 8:23:03 PM - 		-------------------------------------------------------
1/28/2022 8:23:03 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/28/2022 8:23:03 PM - 		Name         : Visual Studio core editor
1/28/2022 8:23:03 PM - 		Version      : [15.0,)
1/28/2022 8:23:03 PM - 
1/28/2022 8:23:03 PM - 		-------------------------------------------------------
1/28/2022 8:23:03 PM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
1/28/2022 8:23:03 PM - 		Name         : Roslyn Language Services
1/28/2022 8:23:03 PM - 		Version      : [15.0,)
1/28/2022 8:23:03 PM - 
1/28/2022 8:23:03 PM - Signature Details...
1/28/2022 8:23:03 PM - 	Extension is not signed.
1/28/2022 8:23:03 PM - 
1/28/2022 8:23:03 PM - Searching for applicable products...
1/28/2022 8:23:03 PM - Found installed product - Global Location
1/28/2022 8:23:03 PM - Found installed product - Visual Studio Community 2022
1/28/2022 8:23:03 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by malware-dev** [comment]
https://github.com/malware-dev/MDK-SE#visual-studio-2022-support
