### ISSUE TITLE
MDK not installing

### ISSUE THREAD

**Issue by BotEmma** [malware-dev/MDK-SE#257]
I am trying to install the MDK and when I run the installer I get a message saying the install was not successful for the selected products when I never got to select a product. I have VS Code and VS 2017 and from what I remember both of these are installed on my D: drive not my C:

Here is the install log:
2/24/2022 12:18:59 PM - Microsoft VSIX Installer
2/24/2022 12:18:59 PM - -------------------------------------------
2/24/2022 12:18:59 PM - vsixinstaller.exe version:
2/24/2022 12:18:59 PM - 15.9.3043
2/24/2022 12:18:59 PM - -------------------------------------------
2/24/2022 12:18:59 PM - Command line parameters:
2/24/2022 12:18:59 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ethan\Downloads\MDK.vsix
2/24/2022 12:18:59 PM - -------------------------------------------
2/24/2022 12:18:59 PM - Microsoft VSIX Installer
2/24/2022 12:18:59 PM - -------------------------------------------
2/24/2022 12:18:59 PM - Initializing Install...
2/24/2022 12:18:59 PM - Extension Details...
2/24/2022 12:18:59 PM - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
2/24/2022 12:18:59 PM - 	Name               : MDK/SE
2/24/2022 12:18:59 PM - 	Author             : Morten Aune Lyrstad
2/24/2022 12:18:59 PM - 	Version            : 1.4.12
2/24/2022 12:18:59 PM - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
2/24/2022 12:18:59 PM - 	Locale             : en-US
2/24/2022 12:18:59 PM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
2/24/2022 12:18:59 PM - 	InstalledByMSI     : False
2/24/2022 12:18:59 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
2/24/2022 12:18:59 PM - 
2/24/2022 12:19:00 PM - 	SignatureState     : Unsigned
2/24/2022 12:19:00 PM - 	Supported Products : 
2/24/2022 12:19:00 PM - 		Microsoft.VisualStudio.Community
2/24/2022 12:19:00 PM - 			Version : [16.8,17.0)
2/24/2022 12:19:00 PM - 
2/24/2022 12:19:00 PM - 	References         : 
2/24/2022 12:19:00 PM - 	Prerequisites      : 
2/24/2022 12:19:00 PM - 		-------------------------------------------------------
2/24/2022 12:19:00 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2/24/2022 12:19:00 PM - 		Name         : Visual Studio core editor
2/24/2022 12:19:00 PM - 		Version      : [15.0,)
2/24/2022 12:19:00 PM - 
2/24/2022 12:19:00 PM - 		-------------------------------------------------------
2/24/2022 12:19:00 PM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
2/24/2022 12:19:00 PM - 		Name         : Roslyn Language Services
2/24/2022 12:19:00 PM - 		Version      : [15.0,)
2/24/2022 12:19:00 PM - 
2/24/2022 12:19:00 PM - Signature Details...
2/24/2022 12:19:00 PM - 	Extension is not signed.
2/24/2022 12:19:00 PM - 
2/24/2022 12:19:00 PM - Searching for applicable products...
2/24/2022 12:19:00 PM - Found installed product - Global Location
2/24/2022 12:19:00 PM - Found installed product - Visual Studio Community 2017
2/24/2022 12:19:00 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by malware-dev** [comment]
https://github.com/malware-dev/MDK-SE/wiki/Getting-Started-with-MDK#step-1

MDK requires specifically Visual Studio 2019.

VSCode has nothing in common with Visual Studio but the name.
