### ISSUE TITLE
Visual Studio 2022 Issue

### ISSUE THREAD

**Issue by Et3rnalPho3nix** [malware-dev/MDK-SE#259]
Was going to start to play with some scripting, and many people recommend to add this plug in with Visual studio. Unfortunately I am not able to get 2019 in the community addition any longer, and when I run the plugin it fails due to incompatible version on Visual studio. 

Is there a work around for this at all?

**Comment by Et3rnalPho3nix** [comment]
Derp, Issue is on main page.....

**Comment by malware-dev** [comment]
There's a link to getting VS2019 in the https://github.com/malware-dev/MDK-SE/wiki/Getting-Started-with-MDK page.

I'm sorry it's taking so long with a '22 version 😭

**Comment by Et3rnalPho3nix** [comment]
OMG, I feel like such a derp for missing this! Thanks! this should get me going. 

No worries on the 22 version, the fact that you are keeping things up to date, and that this wicked awesome tool exists is enough. Life is more than video games, as much as it would be nice haha.

Thanks for pointing me in the right direction!! Much Appreciated.
