### ISSUE TITLE
MDK.vsix Not able to be installed in VS2015 Community Edition

### ISSUE THREAD

**Issue by mellexpro** [malware-dev/MDK-SE#26]
Hi Malware, I tried installing the .vsix file following the steps outlined in you getting started guide (I only got as far as Step 2) when the installer complained that the extension cannot be installed with with the currently VS2015 community installation, please help?

Screenshot:
![image](https://user-images.githubusercontent.com/17949569/29252708-574ffcc2-806c-11e7-96b0-db6751955dac.png)

Install log:
`2017/08/13 21:12:12 - Microsoft VSIX Installer
2017/08/13 21:12:12 - -------------------------------------------
2017/08/13 21:12:12 - Initializing Install...
2017/08/13 21:12:12 - Extension Details...
2017/08/13 21:12:12 - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
2017/08/13 21:12:12 - 	Name               : MDK/SE
2017/08/13 21:12:12 - 	Author             : Morten Aune Lyrstad
2017/08/13 21:12:12 - 	Version            : 0.9.36
2017/08/13 21:12:12 - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
2017/08/13 21:12:12 - 	Locale             : en-US
2017/08/13 21:12:12 - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
2017/08/13 21:12:12 - 	InstalledByMSI     : False
2017/08/13 21:12:12 - 	SupportedFrameworkVersionRange : [4.6.1,)
2017/08/13 21:12:12 - 
2017/08/13 21:12:12 - 	SignatureState     : Unsigned
2017/08/13 21:12:12 - 	Supported Products : 
2017/08/13 21:12:12 - 		Microsoft.VisualStudio.Community
2017/08/13 21:12:12 - 			Version : [15.0]
2017/08/13 21:12:12 - 
2017/08/13 21:12:12 - 	References         : 
2017/08/13 21:12:12 - 		-------------------------------------------------------
2017/08/13 21:12:12 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
2017/08/13 21:12:12 - 		Name         : Visual Studio MPF 15.0
2017/08/13 21:12:12 - 		Version      : [15.0]
2017/08/13 21:12:12 - 		MoreInfoURL  : 
2017/08/13 21:12:12 - 		Nested       : No
2017/08/13 21:12:12 - 
2017/08/13 21:12:12 - Signature Details...
2017/08/13 21:12:12 - 	Extension is not signed.
2017/08/13 21:12:12 - 
2017/08/13 21:12:12 - Searching for applicable products...
2017/08/13 21:12:12 - Found installed product - Microsoft Visual Studio Community 2015
2017/08/13 21:12:12 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
2017/08/13 21:12:12 - Found installed product - Global Location
2017/08/13 21:12:12 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`

**Comment by mellexpro** [comment]
Is it possible to get the installer to recognize VS v14.0 and an applicable target?

`<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0]" />`

Thanks

**Comment by malware-dev** [comment]
Why don't you just upgrade to 2017? This is designed for that. _I_ will not be supporting any earlier versions. I'm just one guy. I'm not going to be supporting multiple IDE versions, just the one I use myself.

Sorry.

**Comment by malware-dev** [comment]
I might accept a pull request adding this support, but I cannot guarantee that I won't be using any 2017-specific features - although frankly I doubt it.

**Comment by mellexpro** [comment]
Ok I will investigate upgrading cause I am using VS2015 for another scripting development which uses its own extension package, I don't know if it will be a problem for me but I want to try your extension with space engineers which I think its worth the upgrade effort.

Thanks for your quick reply

**Comment by malware-dev** [comment]
Worst case scenario you can easily run both 2015 and 2017 in parallel. They install side-by-side by default, actually.

**Comment by mellexpro** [comment]
hmmm OK, I honestly didn't know that, I will give it a go.

**Comment by malware-dev** [comment]
_Will not be fixed_
