### ISSUE TITLE
Unable to load Analyzer assembly

### ISSUE THREAD

**Issue by dosfx** [malware-dev/MDK-SE#261]
After updating to the latest version (1.2.31 -> 1.4.12) All my old projects detected they needed an upgrade and I let them do so. I restart visual studio as was advised by the updater. After the restart all my old projects generate the warning 
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly c:\users\dos\appdata\local\microsoft\visualstudio\16.0_faa58f81\extensions\3ujszklj.cks\Analyzers\MDKAnalyzer.dll: Could not find a part of the path 'c:\users\dos\appdata\local\microsoft\visualstudio\16.0_faa58f81\extensions\3ujszklj.cks\Analyzers\MDKAnalyzer.dll'.	BumbleControl		1	Active
```

I checked and that `3ujszklj.cks` must be the old path for the VS extension. The new path has been updated in all of the MDK.paths.props files. In fact I greped in the solution dir for `3ujszklj.cks` and got 0 hits so I'm not sure where the old path is still stored. I've tried a Solution Clean and Rebuild, still getting the warnings.

**Comment by malware-dev** [comment]
If you check you'll see it actually _works._ There's nothing I can do about this, it'll just go away at some point.

**Comment by dosfx** [comment]
Correct it does. Fair enough, thanks for the response.
