### ISSUE TITLE
Error: This Extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by cowman405** [malware-dev/MDK-SE#265]
I can't seem to Insall this extension and I haven't been able to resolve this issue on my own.

I just installed the latest version of the community verson of Microsoft Visual Studio 2022 (17.2.1) and can't get this extension to install correctly. After following a few different Guides and even changing the "supported products" in the .vsixmanifest file to match my version I still can't get this to work. 

Important to mention that I only have the .NET Framework SDK & targeting pack installed.

I'm new to Visual Studio and this extension and don't really know where to go from here, if anyone can provide some form of assistance It would be greatly appreciated.

The file below is a .txt file containing the full install log for anyone who might need it.

[VSIX-SE Error Report.txt](https://github.com/malware-dev/MDK-SE/files/8715037/VSIX-SE.Error.Report.txt)

**Comment by kwilliams1987** [comment]
The extension doesn't support 2022 due to API changes.

You'll need to download the 2019 Community Edition.

**Comment by cowman405** [comment]
How do I Download the 2019 version? I can't find a listing on the website and the installer doesn't give me an option to install previous versions.

**Comment by kwilliams1987** [comment]
This link will force the Visual Studio Installer to offer Visual Studio 2019 Community Edition:

https://download.visualstudio.microsoft.com/download/pr/f4685935-e4ae-4242-93bc-38dbe6477fb9/bac769ac161e6797cade44882e3de6f54292d6c1d8bb546daa91fe96f30813a3/vs_Community.exe

**Comment by malware-dev** [comment]
You'll find everything on the getting started page. On May 18, 2022 13:09, cowman405 ***@***.***> wrote:
How do I Download the 2019 version? I can't find a listing on the website and the installer doesn't give me an option to install previous versions.

**Comment by cowman405** [comment]
Great, Thank You!
