### ISSUE TITLE
Cannot install mdk-se on Visual Studio 2022

### ISSUE THREAD

**Issue by Maverik37** [malware-dev/MDK-SE#267]
Hi,

I want to install mdk se for visual studio but the installation failed .

here the error message  in joint file

For information i install Visual Studio on my other disk (D:) and not on C:/ to keep some place

do you have solutions ?

thanks in advance,
best regards
[dd_VSIXInstaller_20220618142718_3f6c.log](https://github.com/malware-dev/MDK-SE/files/8933529/dd_VSIXInstaller_20220618142718_3f6c.log)
:

**Comment by kwilliams1987** [comment]
VS2022 isn't currently supported.

**Comment by spreedated** [comment]
That's a shame imho.
These days vs2019 is seldom found and I don't wanna install 2019 just for this particular use case.
What about the source, is there a support for 2022? - What's the main reason for 2022 being not supported, afaik, there's not much of a difference, but I'm by far no vsix developer.

**Comment by malware-dev** [comment]
The reason VS'22 is not supported is the huge changes MS made to the addin APIs I use, requiring a larger rewrite of MDK.
