### ISSUE TITLE
Missing deploy in vs 17 enterprise

### ISSUE THREAD

**Issue by sirhamsteralot** [malware-dev/MDK-SE#27]
pics:
http://imgur.com/a/qDmrL (multiple images)

project (zipped):
https://drive.google.com/open?id=0B1BcAyBfX9iFWUlhTWFFMXN5Rk0

**Comment by sirhamsteralot** [comment]
closing and reopening the solution fixes the issue

**Comment by malware-dev** [comment]
Historical note: This has nothing to do with Visual Studio Edition. MDK is not correctly recognizing the initial load of a newly created project, so it can't check whether the new project is an MDK project.
