### ISSUE TITLE
Error in IMyLandingGear properties in the wiki

### ISSUE THREAD

**Issue by MaxwellMasaitis** [malware-dev/MDK-SE#270]
The `IsParkingEnabled` property has no description and the `LockMode` property has a description referencing the parking signal, which seems wrong.

**Comment by malware-dev** [comment]
That is Keen's responsibility, not mine 😁On Jun 24, 2022 05:32, MaxwellMasaitis ***@***.***> wrote:
The IsParkingEnabled property has no description and the LockMode property has a description referencing the parking signal, which seems wrong.
