### ISSUE TITLE
Trim Unused Types Not Working

### ISSUE THREAD

**Issue by GHYNG** [malware-dev/MDK-SE#271]
In the MDK Script Options, I had "Trim Unused Types" clicked. 

The source code is: 

```cs
namespace IngameScript {
	partial class Program : MyGridProgram {
		public void Main(string args, UpdateType updateType) {
			Echo("do something");
		}
		private void TestA() {
			// does nothing
		}
	}
}
```

And it generated this: 

```cs
// with minifier striping comments
public void Main(string args, UpdateType updateType) {
	Echo("do something");
}
private void TestA() {
}
```

or this: 

```cs
// with minifier full
void Main(string A,UpdateType B){Echo("do something");}void C(){}
```

While it should not generate the unused function?

**Comment by malware-dev** [comment]
Note, it says unused _types_ not functions. On Jul 11, 2022 09:04, GHYNG ***@***.***> wrote:
In the MDK Script Options, I had "Trim Unused Types" clicked.
The source code is:
namespace IngameScript {
	partial class Program : MyGridProgram {
		public void Main(string args, UpdateType updateType) {
			Echo("do something");
		}
		private void TestA() {
			// does nothing
		}
	}
}
And it generated this:
// with minifier striping comments
public void Main(string args, UpdateType updateType) {
	Echo("do something");
}
private void TestA() {
}
or this:
// with minifier full
void Main(string A,UpdateType B){Echo("do something");}void C(){}
While it should not generate the unused function?
