### ISSUE TITLE
Missing - BlocksOfType

### ISSUE THREAD

**Issue by samerrie** [malware-dev/MDK-SE#273]
- for "Wind Turbine" <- cant be found with: GridTerminalSystem.GetBlocksOfType<IMyWindTurbine>
 - for "Hydrogen Engine" <- cant be found with: GridTerminalSystem.GetBlocksOfType<IMyHydrogenEngine>
 -  for "Projector"<- cant be found with: GridTerminalSystem.GetBlocksOfType<IMyProjector>
 - for "Hinge Part"<- cant be found with: GridTerminalSystem.GetBlocksOfType<IMyHingePart>

**Comment by malware-dev** [comment]
Not all block types have their own interface. Go to Keen's Discord (https://discord.com/invite/keenswh) to learn how to get those blocks.I just document the API. I don't make it.On Aug 4, 2022 02:11, samerrie ***@***.***> wrote:
for "Wind Turbine" <- cant be found with: GridTerminalSystem.GetBlocksOfTypefor "Hydrogen Engine" <- cant be found with: GridTerminalSystem.GetBlocksOfTypefor "Projector"<- cant be found with: GridTerminalSystem.GetBlocksOfTypefor "Hinge Part"<- cant be found with: GridTerminalSystem.GetBlocksOfType
