### ISSUE TITLE
Is there a way to save an IMyCubeBlock to MyIni?

### ISSUE THREAD

**Issue by 33iRobot33** [malware-dev/MDK-SE#276]
I'm trying to save a <IMyCubeBlock> list to the MyIni file. Anyone knows a way to do this?

**Comment by malware-dev** [comment]
I do not provide scripting help here. These issues are reserved for MDK things. Please go to Keen's discord. [https://discord.com/invite/keenswh](https://discord.com/invite/keenswh)
