### ISSUE TITLE
.NET Framwork 4.6.1 unavailable

### ISSUE THREAD

**Issue by Ratchet68** [malware-dev/MDK-SE#277]
Reproduce : 
 - Follow the tutorial :  https://github.com/malware-dev/MDK-SE/wiki/Getting-Started-with-MDK
 - When creating a new project, visual studio prompt a ".NET Framwork 4.6.1 unavailable"

Fix : 
- Install the dev package for .NET v4.6.1 https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net461-developer-pack-offline-installer

I've very little knowledge on how the installation of extension work, but would it be possible for futur user to install automatically the .NET v4.6.1 ?

**Comment by malware-dev** [comment]
If you read the first paragraph in the Getting Started guide, it will tell you that you are now to use .NET 4.8, not 4.6.1 - and where to find it.

**Comment by malware-dev** [comment]
![image](https://user-images.githubusercontent.com/4653628/197696913-81f36a1f-99d5-4b26-847f-e7e1b43af523.png)
