### ISSUE TITLE
What to type in the Program.Main brackets

### ISSUE THREAD

**Issue by PunktAtomic** [malware-dev/MDK-SE#278]
![grafik](https://user-images.githubusercontent.com/118569313/202798802-3a8d6675-27f4-45b5-aef5-e1eba85e473f.png)
I don't get what I have to put in those Brackets for the code in a script block to run. In Youtube videos people leave this how it is and so did I, but it's an error for me. I tried understanding what was wanted in the Wiki but I couldn't work it out as there is no syntax example. I have constant updates at 10 ticks set. What do I need to type in the Bracket of Program.Main for the code to run?

**Comment by malware-dev** [comment]
What do you mean no syntax example?
<https://github.com/malware-dev/MDK-SE/wiki/The-Anatomy-of-a-Script>
<https://github.com/malware-dev/MDK-SE/wiki/Your-First-Script>
<https://github.com/malware-dev/MDK-SE/wiki/The-Grid-Terminal-System>
as a beginning...

If you mean C# syntax, I assume at least a basic knowledge of C# in my tutorials. It's beyond the scope of my tutorials to teach that, as they're already in existence _all over_ the web. C# is a popular programming language.

I also do not provide scripting help in these issues, I do not have the time. Join Keen's discord, #programmable-block channel. You'll find me and a lot of other people there.

<https://discord.com/invite/keenswh>

**Comment by PunktAtomic** [comment]
Okay, I will ask there
