### ISSUE TITLE
Wiki: Add the following information to the information on Sandbox.ModAPI.Ingame.MyShipMass

### ISSUE THREAD

**Issue by largenumberhere** [malware-dev/MDK-SE#279]
BaseMass = ship with empty containers + weight of 100kg for each player in a cockpit (inconsistently)
PhysicalMass = Physics engine calulated base mass + cargo
TotalMass = Physical mass+ inventory of player in cockpits

**Comment by malware-dev** [comment]
That's Keen's domain, not mine. I can't add _anything_ to the API documentation itself :D

**Comment by largenumberhere** [comment]
Thanks for the info. Do you know the best way I could contact them about
this?

**Comment by malware-dev** [comment]
At support@keenswh.com.
