### ISSUE TITLE
 MDK 1.14.2 Visual Studio 2019: "This extension is not installable on any currently installed products." (older 2019 versions)

### ISSUE THREAD

**Issue by jwf1112** [malware-dev/MDK-SE#280]
When attempting to install the logs shows the following error:  This extension is not installable on any currently installed products.

from my understanding this is not expected for the 2019 version of visual studio as that is the currently the supported version by MDK

the log shows that it correctly detects the 2019 version which is what is weird, has there been a possible update to support a later version and the documentation in the getting started needs to be updated? I will try testing one or two earlier releases to see if the issue is replicated or only specific to the 1.14.2 release

[dd_VSIXInstaller_20221217202406_0874.log](https://github.com/malware-dev/MDK-SE/files/10253013/dd_VSIXInstaller_20221217202406_0874.log)

**Comment by jwf1112** [comment]
After taking a closer look in the log it appears it might be due to an outdated version of the 2019 visual studio (looks like i currently have v15 and it requires v16.8 or 17) will attempt updating and seeing if issue is resolved

**Comment by jwf1112** [comment]
Updating Visual Studio 2019 resolves the installation issue, documentation might need to include step to ensure visual studio is updated if already installed for edge case of outdated visual studio 2019 versions

**Comment by malware-dev** [comment]
As it says on the download (Releases) page, you need at least 16.8 🙂
