### ISSUE TITLE
Suggestion: Lower code to allow newer C# features

### ISSUE THREAD

**Issue by WazWaz** [malware-dev/MDK-SE#282]
While SE will presumably stay with supporting C# 7.3, MDK could use selective lowering to allow any version of C# to be used. This would need to be selective to avoid blowing out the code size lowering below C# 7.3.

Obviously this is a wishful-thinking "MDK2" kind of feature.

**Comment by malware-dev** [comment]
C#6. The programmable block and mods only supports C#6.

Otherwise... Not a chance in the 9 hells that I will put that amount of effort to this... sorry.
