### ISSUE TITLE
I can't install plugin

### ISSUE THREAD

**Issue by SeaOfBloods30** [malware-dev/MDK-SE#288]
Hello everyone,
I've a little problem with the installation. I've visul studio community 2019 the latest version but it does not work with the latest version of this plugin. Pls help me :( . This is the log file.

21/04/2023 22:10:39 - Microsoft VSIX Installer
21/04/2023 22:10:39 - -------------------------------------------
21/04/2023 22:10:39 - vsixinstaller.exe version:
21/04/2023 22:10:39 - 17.5.4074+g1de9468fa7
21/04/2023 22:10:39 - -------------------------------------------
21/04/2023 22:10:39 - Command line parameters:
21/04/2023 22:10:39 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Christian\Downloads\MDK.vsix
21/04/2023 22:10:39 - -------------------------------------------
21/04/2023 22:10:39 - Microsoft VSIX Installer
21/04/2023 22:10:39 - -------------------------------------------
21/04/2023 22:10:40 - Initializing Install...
21/04/2023 22:10:40 - Dettagli estensione...
21/04/2023 22:10:40 - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
21/04/2023 22:10:40 - 	Name               : MDK/SE
21/04/2023 22:10:40 - 	Author             : Morten Aune Lyrstad
21/04/2023 22:10:40 - 	Version            : 1.4.13
21/04/2023 22:10:40 - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
21/04/2023 22:10:40 - 	Locale             : en-US
21/04/2023 22:10:40 - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
21/04/2023 22:10:40 - 	InstalledByMSI     : False
21/04/2023 22:10:40 - 	SupportedFrameworkVersionRange : [4.8,)
21/04/2023 22:10:40 - 	SignatureState     : Unsigned
21/04/2023 22:10:40 - 	Prodotti supportati : 
21/04/2023 22:10:40 - 		Microsoft.VisualStudio.Community
21/04/2023 22:10:40 - 			Version : [16.8,17.0)
21/04/2023 22:10:40 - 			ProductArchitecture : x86
21/04/2023 22:10:40 - 	Riferimenti        : 
21/04/2023 22:10:40 - 	Prerequisiti       : 
21/04/2023 22:10:40 - 		-------------------------------------------------------
21/04/2023 22:10:40 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
21/04/2023 22:10:40 - 		Name         : Visual Studio core editor
21/04/2023 22:10:40 - 		Version      : [15.0,)
21/04/2023 22:10:40 - 		-------------------------------------------------------
21/04/2023 22:10:40 - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
21/04/2023 22:10:40 - 		Name         : Roslyn Language Services
21/04/2023 22:10:40 - 		Version      : [15.0,)
21/04/2023 22:10:40 - Dettagli firma...
21/04/2023 22:10:40 - 	Extension is not signed.
21/04/2023 22:10:40 - Ricerca di prodotti applicabili in corso...
21/04/2023 22:10:40 - Trovato prodotto installato - Percorso globale
21/04/2023 22:10:40 - VSIXInstaller.NoApplicableSKUsException: Questa estensione non è installabile su nessuno dei prodotti attualmente installati.
   in VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   in VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   in VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   in VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   in VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   in VSIXInstaller.App.Initialize()
   in System.Threading.Tasks.Task`1.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()

**Comment by malware-dev** [comment]
The installer disagrees with you. From it's point of view, you do not have an appropriate Visual Studio installed. I'm afraid I can't really tell you anything further than that.
