### ISSUE TITLE
See if it's possible to strip unused types

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#29]
Add an option to strip unused types from the deployed scripts. This will make shared projects even more useful.

**Comment by malware-dev** [comment]
This would obviously also be of help to the Minifier - maybe an even more aggressive version which looks at members?

**Comment by baratgabor** [comment]
Yes, this would be a huge improvement... I like to use shared projects, and to create/store potentially useful components in them, but the bloat they add to the deployed script (in that space-constrained environment) is quite crippling. I'm constantly having time issues, but maybe I'll actually try to look into this. :)

**Comment by malware-dev** [comment]
I actually _know_ how to do this, it's just all about... you know... actually getting it in there... 😄

**Comment by malware-dev** [comment]
The workaround I personally use right now is to have many shared projects with few components per project.

**Comment by malware-dev** [comment]
I need to be clear. I don't think it's a good idea for someone else to be trying to solve this particular problem. The code in question is in too much flux yet, I would probably not be able to merge anything here.

**Comment by baratgabor** [comment]
Okay. :) I didn't even look into this yet; tbh I'm not really working on my ingame script lately, so I don't have any urgency. But maybe I'll play around with some stuff just on my forked version, as having experience with VS extension development can come handy.

**Comment by malware-dev** [comment]
_That_ is true enough, there's a billion and one pitfalls to fall into and your google-fu has to be _really_ good in order to separate the wrong answers from the right ones... Extension development for Visual Studio is _not_ fun. But the end result is worth it when it works...
