### ISSUE TITLE
(VS'22) Random error "feature not allowed in SE"

### ISSUE THREAD

**Issue by JustPCode** [malware-dev/MDK-SE#294]
It's not a big deal deal but I think it's worth taking note of.

Sometimes, out of nowhere, VS decides to throw an error like "feature disabled in space engineers" or something and then disappears, later I'll upload a screenshot.

It's not a major bug but it's really annoying

**Comment by malware-dev** [comment]
Screenshot doesn't help me. If I can't reproduce, I can't fix. Besides, VS has _always_ been temperamental with this stuff, with VS'19 too.
