### ISSUE TITLE
check call back event from any block when finish work 

### ISSUE THREAD

**Issue by hassanFraihat7780** [malware-dev/MDK-SE#297]
need check callback event from block when finish working .

ex: need callback from IMyExtendedPistonBase when finish expand .

any help

**Comment by malware-dev** [comment]
Hi. There are _no_ events at all in the PB API, as events leak if you don't know what you're doing. You need to poll for state.

That said, this site is not for script help, these issues are purely for MDK problems. Go to [Keen's discord](https://discord.gg/keenswh), #programmable-block channel, to get help for scripting.
