### ISSUE TITLE
Issue with Playing AI Recorder (Task) Block Using a Script

### ISSUE THREAD

**Issue by gidegra1** [malware-dev/MDK-SE#298]
I am currently facing a challenge with playing the AI Recorder (Task) block in Space Engineers using a script. I have attempted to use the provided methods, but the block does not respond as expected. I would like to find a solution or workaround to successfully initiate the playback of recorded AI tasks using a script.

I find the method "Void Play()" but that didn't work. At the moment I start a timer block that then play the Ai Recorder. But if I want to start it agin it don't start playing.

I would greatly appreciate any guidance or alternative approaches that can help me successfully play the AI Recorder (Task) block using a script. Thank you for your assistance in resolving this issue.

**Comment by malware-dev** [comment]
I'm sorry, this site is only for MDK issues, I don't do scripting help here. I'm just one guy, I don't know everything - I haven't worked with the AI blocks at all, they're not my thing (yet). Go to [Keen's discord](https://discord.gg/keenswh), #programmable-block channel.
