### ISSUE TITLE
a PDF-file for the wiki

### ISSUE THREAD

**Issue by Nerk0s** [malware-dev/MDK-SE#299]
Hello,

I'm new to coding scripts to space engineers and am somewhat bound to regularly look up the wiki 
and would find it really usefull to be able to download a PDF-version of the wiki to use in case of having no wifi-access.
I hope this request gets a positiv response.
Thanks.

**Comment by malware-dev** [comment]
I do not have any kind of software that can convert markdown files to pdf. _However._ You can download the entire documentation site locally to your computer. Best way is via Git or the GitHub application.

[Download this](https://desktop.github.com/), or use your preferred Git application, of course.

Look for this in the lower right of the wiki pages: 
![image](https://github.com/malware-dev/MDK-SE/assets/4653628/d10379c2-67d9-4b78-a18c-466034c6b771)

This is the cloning URL. Follow the instructions given by the GitHub application on how to clone a repo, and you'll get everything locally. You'll need a Markdown reader.

**Comment by kwilliams1987** [comment]
You can convert Markdown to PDF using `pandoc`, although I don't think it works with multiple linked files.
