### ISSUE TITLE
Crash with 0.9.37-RC 

### ISSUE THREAD

**Issue by Elfiwolfe** [malware-dev/MDK-SE#30]
When I open the solution of the attached project, VS stopped working
devenv.exe 
System.nullReferenceExpection
'Object reference not set to an instance of an object.'

Debugger says
+		$exception	{"Object reference not set to an instance of an object."}	System.NullReferenceException
Output says
An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.dll
Object reference not set to an instance of an object.

**Comment by Elfiwolfe** [comment]
[ShipsMainProgramMk2.zip](https://github.com/malware-dev/MDK-SE/files/1224325/ShipsMainProgramMk2.zip)

**Comment by Elfiwolfe** [comment]
Crash is after the upgrade project screen comes up but before you even touch the button on the upgrade.

**Comment by Elfiwolfe** [comment]
[CrashMDKmk2.zip](https://github.com/malware-dev/MDK-SE/files/1224336/CrashMDKmk2.zip)

**Comment by Elfiwolfe** [comment]
Latest version of MDK does not crash with this project.

**Comment by malware-dev** [comment]
Thank you!
