### ISSUE TITLE
Add Autocannon API

### ISSUE THREAD

**Issue by PioMas306637** [malware-dev/MDK-SE#301]
There is no Autocannon interface and I'd find it very usefull. Epecially the shoot once and toggle on methods.

**Comment by malware-dev** [comment]
The autocannon is just another normal turret. The individual weapons don't have their own interfaces. I don't know which turret interface it uses, it might actually be missile turret 🤔 I don't script weapons much myself, go to [Keen's discord](https://discord.gg/keenswh) and ask in the #programmable-block channel, there should be someone there who can give you a clear answer.

Also; I don't work for Keen. Any kind of changes to the API will have to be requested of _them_ not me 🙂
