### ISSUE TITLE
Status of MDK-CLI - Scripting on Linux?

### ISSUE THREAD

**Issue by LinuxSquare** [malware-dev/MDK-SE#306]
Hei og god dag

I just stumbled over this fabulous repo.
Since I'm a Gnu+Linux user & admin since almost 4 years, I code and play video games (such as SE) on my Arch Linux device.

I do code often and wanted to program some scripts for my programmable blocks in SE, with synatx highlighting and a working tabcompletion.
However, since the extension is only available for Visual Studio on Windows, I'm afraid, that coding on Linux is not possible.

I have seen the following pull-request: https://github.com/malware-dev/MDK-SE/pull/292, and wanted to ask how's the status, since it's still open. It would be lovely, to have a downloadable cli.

If the cli's not available yet for public, is there any other solution? I've read, that SE must be installed on the system to code, so a VM with VS & SE isn't a pretty solution just for coding.

I would be happy for any help I can get.

Tusen takk

**Comment by malware-dev** [comment]
It is still open because I never got a response to my queries to fix problems.

SE must be installed on the system for the simple reason that we cannot provide the assemblies any other way, that would be copyright infringement. My extension doesn't change that, all that does is help set up the environment. You still need the game installed, even with MDK.

**Comment by LinuxSquare** [comment]
The game is installed, just on my Linux machine.
Is there no way around, to have a Windows VM for coding?

**Comment by malware-dev** [comment]
I don't know. I've never been a Linux person. I don't know what kind of IDEs are available for Linux, if there's any C# capable. I'm sorry, I have no answers for you.

**Comment by LinuxSquare** [comment]
> if there's any C# capable
There is MonoDevelop, which aims for VS-like experience.

But unfortunately, VS extensions are not working with MD.

**Comment by malware-dev** [comment]
Like I've been trying to tell you, you don't _need_ MDK to script. MDK is a convenience tool. You'll just have to set up the references yourself. _In theory_ you should be able to just copy the DLLs from your game and reference them. Or just reference them directly from the game directory (this is what MDK does)

**Comment by kwilliams1987** [comment]
There was a guide made to allow you to create the Boilerplate for a project in Visual Studio Code, however you need to patch up the references yourself (and convert the boiler plate to an Ingame Script) hoever it would at least allow code completion in MonoDevelop with the correct assembly references.

You would miss out on many of MDKs great features like detecting white listed functions but that's the unfortunate state unless you make a Windows VM.

**Comment by LinuxSquare** [comment]
> There was a guide made to allow you to 
> create the Boilerplate

Hm, since there isn't an uptodate guide, (only one which dates back to 2015) , I think it's less trouble if I made a Windows VM instead. 

Thank y'all.

**Comment by OmegaRogue** [comment]
> > if there's any C# capable
> 
> There is MonoDevelop, which aims for VS-like experience.
> 
> But unfortunately, VS extensions are not working with MD.

There's also JetBrains Rider, which even on windows is better than VS IMO

**Comment by malware-dev** [comment]
> > > if there's any C# capable
> > 
> > 
> > There is MonoDevelop, which aims for VS-like experience.
> > But unfortunately, VS extensions are not working with MD.
> 
> There's also JetBrains Rider, which even on windows is better than VS IMO

Strong agree,  big downside being - it's not free.

**Comment by OmegaRogue** [comment]
> > > > if there's any C# capable
> > > 
> > > 
> > > There is MonoDevelop, which aims for VS-like experience.
> > > But unfortunately, VS extensions are not working with MD.
> > 
> > There's also JetBrains Rider, which even on windows is better than VS IMO
> 
> Strong agree,  big downside being - it's not free.

Yes, otherwise theres always vscode, vim and emacs (and because of vscode every other ide that supports the LSP protocol)
