### ISSUE TITLE
Type 'string' prohibited

### ISSUE THREAD

**Issue by Skimt** [malware-dev/MDK-SE#31]
The error **"type or member 'string' is prohibited in Space Engineers"** appeared after I had used Ctrl+ X (cut & paste) on two methods that were seemingly unrelated to the method in which the error appeared. Seemed to me that IntelliSense wants data types ("var") to be more specifically defined ("string"). 

```
string[] ss = { "stuff", "stuff" };
// "var" was underlined red as an error
foreach (var s in ss) {
	// do
}
```

**Note:** I have Program.cs, Program1.cs, etc in the same IngameScript project, which may be improper usage of the MDK. The error(s) also disappeared as soon as I backspaced and rewrote the "r" in one of the "var"s. There were no crash. I view this bug as irrelevant, but for all I know it may be the cause for other issues, which is why I'm mentioning it.

**Ps.** I've never used GitHub before so I apologize if I'm not following GitHub bug report customs.

**Comment by malware-dev** [comment]
Most likely the analyzer was just confused, that happens now and again (Roslyn issue, not MDK issue).

Each individual project should have _one_ script.

This report is just fine :D

**Comment by malware-dev** [comment]
If you try to have more than one script (more than one Main method inside a Program class) deploy will not work.

**Comment by Skimt** [comment]
I've done [this](http://i.imgur.com/x1REu7m.jpg) so as to be able to work between scripts/backups. From what you're saying, I take it Program1() will not be recognized and changed back to Program() when deploying, or throw an error. I'll just have to find an alternative way of working with multiple script simultaneously when the time comes to deploy.

**Comment by malware-dev** [comment]
Yes, correct :D You can choose whether to deploy _one_ project or _all_ by right-clicking the individual project or the solution, respectively.

If you see more strange analyzer behavior, and can reproduce it reliably, please report again. I _never_ rule out the possibility of a bug! ;) Doesn't hurt to check it out.
