### ISSUE TITLE
Game Binaries Path

### ISSUE THREAD

**Issue by matt-pinder** [malware-dev/MDK-SE#315]
As a Xbox game pass user, the Game Binaries Path location is not prepopulated.

I am unsure what path to enter, is it the root?

I have the tree below (depth 3) but unsure where to put it

Space Engineers
 - Content
   - Content
      - Audio
      - Brains
      - CustomWorlds
      - Data
      - DataPlatform
      - Fonts
      - IventoryScenes
      - Models
      - Particles
      - Scenarios
      - Shaders
      - Textures
      - Videos
      - VisualScripts
      - VoxelMaps
      - Worlds
   - Images
   - SpaceEngineers_WS
      - de
      - es
      - fr
      - it
      - ja
      - pt-BR
      - ru
      - x64
      - zh-CN

**Comment by malware-dev** [comment]
This issue got an answer on the Discord; but to have the history:

Research shows, that the binary file on GamePass/Windows is the SpaceEngineers_WS folder in the structure above.
