### ISSUE TITLE
What about Visual Studio Code?

### ISSUE THREAD

**Issue by dardino** [malware-dev/MDK-SE#319]
Hi, I want ask the community about the creation of a plugin for vscode instead of vs.

Creating a 'MDK for SE' plugin for both Visual Studio and Visual Studio Code offers several advantages. 
For instance Visual Studio Code is a lightweight, cross-platform editor that can be used directly on browsers. 
By supporting both, the plugin becomes accessible to more users with different preferences and needs. 

What do you think?

**Comment by malware-dev** [comment]
I don't use Visual Studio Code, nor have I any interest of using it. It's that simple. Making a _plugin_ for VSCode would mean completely recreating MDK separately, they are quite simply not compatible in any way shape or form. This is why I'm leaving the entire plugin concept behind for MDK2.

MDK2 is IDE-agnostic, and level of support is dependent on what the IDE / editor is capable of, not MDK2 itself.  See #308 for what is going on with MDK, and the main page Readme.md for how to use MDK2 while it's in alpha.

**Comment by malware-dev** [comment]
Oh, for the record, there's [Discussions](https://github.com/malware-dev/MDK-SE/discussions) for questions like these 😄
