### ISSUE TITLE
Minifier breaks duck-typed structs

### ISSUE THREAD

**Issue by mchl12** [malware-dev/MDK-SE#322]
When using duck-typed structs for enumerables and enumerators, the minifier will break them by renaming the `GetEnumerator`, `MoveNext` methods and the `Current` property.

Steps to reproduce:
1) Paste below code into Program.cs in a fresh IngameScript project
2) Set minifier to 'None' and deploy it into the game, it will compile and run correctly
3) Set minifier to 'Full' and deploy it into the game
4) The script will not compile with the following compilation error: "Program(8,166): Error: foreach statement cannot operate on variables of type 'Program.H' because 'Program.H' does not contain a public instance definition for 'GetEnumerator'

```cs
using Sandbox.ModAPI.Ingame;
using System.Collections.Generic;

namespace IngameScript
{
    partial class Program : MyGridProgram
    {
        public Program()
        {
            List<int> list = new List<int> { 1, 2, 3, 4, 5 };
            MyEnumerable enumerable = new MyEnumerable(list);
            foreach (int v in enumerable)
            {
                Echo(v.ToString());
            }
        }

        struct MyEnumerable
        {
            private List<int> _list;
            
            public MyEnumerable(List<int> list)
            {
                _list = list;
            }

            public MyReverseEnumerator GetEnumerator()
            {
                return new MyReverseEnumerator(_list);
            }
        }

        struct MyReverseEnumerator
        {
            private List<int> _list;
            private int _position;

            public int Current => _list[_position];

            public MyReverseEnumerator(List<int> list)
            {
                _list = list;
                _position = _list.Count;
            }

            public bool MoveNext()
            {
                if (_position <= 0)
                    return false;

                _position--;
                return true;
            }
        }
    }
}
```

**Comment by malware-dev** [comment]
What the heck?!? How did I manage _that?_

**Comment by malware-dev** [comment]
Ooooh I see.
Sorry, but you're just gonna have to use the interface so the functions are actually marked as not belonging to the script.
