### ISSUE TITLE
SOLUTION TO DEPLOY BUG!!!!!

### ISSUE THREAD

**Issue by Truetech000** [malware-dev/MDK-SE#323]
i came across the comment left [here](https://github.com/dotnet/roslyn/issues/73854) , and i managed to implement the same fix. its actually easy too! simply download the NuGet package from [here](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.MSBuild) , rename the downloaded .nupkg file to a .zip and extract it. then copy both of the BuildHost folders that are in the zip under contentFiles > any > any to C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\VBCSharp\LanguageServices

the location may be different from community to professional and whatnot but the steps are identical. i restarted visual studio after copying and everything worked great!!!!

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
