### ISSUE TITLE
[MDK2] Missing support for <mdk sortorder="xx" /> tag

### ISSUE THREAD

**Issue by MMaster** [malware-dev/MDK-SE#326]
MDK 1 has support for sortorder tag to allow custom order when joining files to script.cs which I use in AutoLCDs2 to get specific configuration files at the top of the script and translation table at the bottom of the script.

Looks like this is not supported by MDK2 as it joins the files without following the order that MDK1 did.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
