### ISSUE TITLE
Download MDK.vsix 1.5.19, but it shows up as 1.5.18 and asks me to download 1.5.19

### ISSUE THREAD

**Issue by Braste** [malware-dev/MDK-SE#327]
As described in the title, I downloaded release 1.5.19, but VS tells me, that 1.5.18 is installed and the extension asks me to download 1.5.19.

**Comment by malware-dev** [comment]
Yep. Read the updates to find out why.

At this point you should probably move on to MDK2, it's just a question of time before this particular version is archived.

**Comment by Braste** [comment]
I tried to move on to MDK2. 
Unfortunately Visual Studio does not recognize any of the namespaces like VRage, Sandbox, etc. if I try to use MDK2. It does not work at all.
It does not recognize the nuget packages and it is unable to build the project, too. 
As I can build the project with VS Code without any problems, I suspected, that I did something wrong when I tried to create the MDK2 project, so i followed "Getting Started with MDK" and the project works without ANY problem in VS now.

As MDK2 is not working in my VS and MDK is, I do not want to move on.

**Comment by Braste** [comment]
This is what I get, if I try to build a newly created MDK2 project:
![image](https://github.com/malware-dev/MDK-SE/assets/494984/82e0a85a-2c08-4b43-bf3b-4e107a9a97f5)

As said, building tthe project in VS Code works, but I want to use VS.

**Comment by malware-dev** [comment]
Make sure you update your Visual Studio

**Comment by Braste** [comment]
Sorry to say it, but MDK does deploy the scripts, at least in my case.

**Comment by malware-dev** [comment]
With an old Visual Studio, yes

**Comment by malware-dev** [comment]
https://github.com/malware-dev/MDK-SE/issues/308

**Comment by malware-dev** [comment]
Which version of VS do you have? If you have < 22 you can side-by-side install 22.

**Comment by Braste** [comment]
I have 22, but not the newest update.

**Comment by malware-dev** [comment]
Strange. Why, then, would you be prevented from updating?Never mind. I am just curious, it is none of my business 😄On Jun 5, 2024 11:44, Stefan Braun ***@***.***> wrote:
I have 22, but not the newest update.

**Comment by Braste** [comment]
Because the latest update brakes some things we use in some projects.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
