### ISSUE TITLE
[MDK2] Minifier has issues with minified variable names

### ISSUE THREAD

**Issue by InfernoSuperNova** [malware-dev/MDK-SE#329]
https://discord.com/channels/@me/1253907280689369139/1253908743855276062
^ DM'ed project link, making an issue for organization

Minification on full fails with reference to some renamed minified types. 

`1>Verifying that nothing went wrong
1>C:\Users\willi\AppData\Roaming\SpaceEngineers\IngameScripts\local\ArgusLiteMDK2\script.cs(390,129): error CS0426: The type name '?' does not exist in the type 'W'
1>C:\Users\willi\AppData\Roaming\SpaceEngineers\IngameScripts\local\ArgusLiteMDK2\script.cs(392,37): error CS0426: The type name '?' does not exist in the type 'W'
1>C:\Users\willi\AppData\Roaming\SpaceEngineers\IngameScripts\local\ArgusLiteMDK2\script.cs(405,31): error CS1503: Argument 3: cannot convert from 'method group' to 'W.?'
1>C:\Users\willi\AppData\Roaming\SpaceEngineers\IngameScripts\local\ArgusLiteMDK2\script.cs(407,104): error CS1503: Argument 3: cannot convert from 'method group' to 'W.?'
1>C:\Users\willi\AppData\Roaming\SpaceEngineers\IngameScripts\local\ArgusLiteMDK2\script.cs(394,131): error CS1955: Non-invocable member '?.?' cannot be used like a method.
1>Failed to compile the project.
1>C:\Users\willi\.nuget\packages\mal.mdk2.pbpackager\2.0.2\build\Mal.Mdk2.PbPackager.props(18,9): error MSB3073: The command ""C:\Users\willi\.nuget\packages\mal.mdk2.pbpackager\2.0.2\build\..\tools\mdk.exe" pack "C:\Users\willi\source\repos\ArgusLiteMDK2\ArgusLiteMDK2\ArgusLiteMDK2.csproj"  -configuration Debug -interactive" exited with code -2.
1>Done building project "ArgusLiteMDK2.csproj" -- FAILED.`

It points to the previously successfully built script.cs for errors but of course it doesn't match

**Comment by malware-dev** [comment]
Fixed in 2.0.4
