### ISSUE TITLE
Deploy Rejected - A deployment is currently in progress.

### ISSUE THREAD

**Issue by Skimt** [malware-dev/MDK-SE#33]
If the script (previously deployed) is open in another program like Notepad++, and you try to deploy, it won't deploy, which is fine, but the script cannot be attempted to be deployed again until Visual Studio is restarted. Or, there is some other reason behind why it is trying to deploy indefinitely. Try opening the script up in Notepad++, deploy, and if it works, wait a couple of seconds, and try to deploy again. At this point it should be stuck in deploying state.

**Comment by malware-dev** [comment]
Hm. This is strange, I must investigate this. Thank you.

**Comment by malware-dev** [comment]
This is really annoying, but I can _not_ reproduce this problem :(

**Comment by Skimt** [comment]
Then it may just be my PC/OS, a hardware glitch or damage, a local setting or virus, causing various processes to act up. Unless someone else mentions something about this, I would ignore it :)

**Comment by malware-dev** [comment]
That's just it. Someone else _has_ reported this issue... so it's definitely real.

**Comment by malware-dev** [comment]
I have made an educated guess and made some changes. I have no idea if it will actually fix the problem, but since I can't reproduce it it's the best I can do for now.

**Comment by Skimt** [comment]
I've not been able to recreate the issue after the update.

**Comment by malware-dev** [comment]
I am _very_ happy to hear that! Hope it continues this way. Who knows, perhaps I can go gold tonight after all?
