### ISSUE TITLE
The "Deploy MDK Script" button is gone with 0.9.38

### ISSUE THREAD

**Issue by julianbartel** [malware-dev/MDK-SE#34]
After updating to 0.9.38, the deploy button in the context menu of the project (as well as some other buttons in the Tools menu) is gone. After going back to 0.9.37, all buttons where back again. Visual Studio version is 15.2.

Edit: Forgot to mention: Maybee this is related to #27? But closing and reloading solution did not fix the issue.

**Comment by Elfiwolfe** [comment]
Same.

**Comment by Elfiwolfe** [comment]
Found a whitelist error
[Failure] Could not find file 'C:\Users\elfiw\AppData\Local\Microsoft\VisualStudio\15.0_3208ebe1\Extensions\my1c2nqx.3qe\Analyzers\whitelist.cache'.
Correct location is
C:\Users\elfiw\AppData\Local\Microsoft\VisualStudio\15.0_3208ebe1\Extensions\xaogax5y.gya\Analyzers

**Comment by Elfiwolfe** [comment]
removed whitelist.cache.  closed VS. open VS and that forced a rebuild that added whitelist correctly

**Comment by Elfiwolfe** [comment]
Then it shows deploy all scripts.
when deploying.
1>------ Build started: Project: ShipMainProgramMk2, Configuration: Debug x64 ------
1>  ShipMainProgramMk2 -> C:\Users\elfiw\Source\Repos\ShipsMainProgramMk2\ShipMainProgramMk2\ShipMainProgramMk2\bin\ShipMainProgramMk2.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
 and that is as far as it gets.

**Comment by malware-dev** [comment]
Thank you. Yes I do believe it's related to #27. It would seem that my fix for _that_ problem might have caused a new one. To confirm; please try to unload and reload a single MDK project (not the entire solution). If I'm right, this should work and provide a workaround until I can solve it.

**Comment by julianbartel** [comment]
Workaround works 👍 Thanks!
