### ISSUE TITLE
Lambdas can cause variable name conflict when using minifier

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#37]
If there's a lambda (or may be a more global program) that uses a variable, it can conflict with the generated variable names and cause an error.  When using minifier.

For example: `groups[groupIndex].GetBlocks(theBlocks, (x => x.CubeGrid == Me.CubeGrid))`;

![image](https://user-images.githubusercontent.com/18159679/29501370-fa3deac8-85dc-11e7-80b7-64ac2cfd42d7.png)

**Comment by Wicorel** [comment]
Changing the source to:
`groups[groupIndex].GetBlocks(theBlocks, (x1 => x1.CubeGrid == Me.CubeGrid));`

'Fixes' the issue.

**Comment by malware-dev** [comment]
I'm so sorry these things take so long, it will happen, I promise...

**Comment by malware-dev** [comment]
Since the minifier is being completely rewritten from scratch, this issue is no longer relevant.
