### ISSUE TITLE
Correction Wiki / The Grid Terminal System 

### ISSUE THREAD

**Issue by CHeuberger** [malware-dev/MDK-SE#38]
Just a little Copy&Paste slip in the sample code of [The Grid Terminal System and Subclasses](https://github.com/malware-dev/MDK-SE/wiki/The-Grid-Terminal-System#user-content-the-grid-terminal-system-and-subclasses) :
```
public class SomeUsefulSubclass
{
    Program _program;

    public AirlockSystem(Program program) 
    {
        _program = program;
    }
```
I believe the constructor should be named `SomeUsefulSubclass` instead of `AirlockSystem`.
Nevertheless the documentation is awesome! Same valid for the MDK! Thankyou.

**Comment by malware-dev** [comment]
Haaahaha!!!

Copypasta strikes again!

Thank you, will fix immediately.
