### ISSUE TITLE
[bug] Cannot create new project - parameter "path" is null

### ISSUE THREAD

**Issue by SoptikHa2** [malware-dev/MDK-SE#39]
_Value cannot be null
Parameter name: path_

Visual Studio Community 2017 throws this error when I try to create any project using MDK-SE. It creates 2 directories (of name of the project)
- SelectedDirectory
   - _[NameOfProject]_
            - _[NameOfProject]_

Thats all, no .sln files, no .cs files, no .csproj files, nothing. It's the first time I use MDK-SE, what should I do? Downloaded [Gold Release 1.0](https://github.com/malware-dev/MDK-SE/releases/tag/1.0)

**Comment by malware-dev** [comment]
Do you have Space Engineers installed on the same machine?

**Comment by SoptikHa2** [comment]
No, is it needed? I have SE installed on another computer, but I program only on this machine. I have access to all SE files, would copying DLLs help?

**Comment by malware-dev** [comment]
SE is indeed required, but yes you can copy the binaries and manually configure the game path under Tools;Options;MDK/SE

---- SoptikHa2 wrote ----

**Comment by malware-dev** [comment]
Nevertheless you have still uncovered a bug; MDK shouldn't _crash_ because of this so thank you for that!

**Comment by SoptikHa2** [comment]
Thanks, it worked. Thanks for fast reply!

**Comment by malware-dev** [comment]
Oh man, I forgot this bug... Aargh. Ok, next release then 😞
