### ISSUE TITLE
Visual Studio breaks the hintpaths at times.

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#4]
Change the way files are referenced, and verify the paths themselves, don't rely on the MSBuild property

**Comment by malware-dev** [comment]
The entire way references are stored and updated is now changed and should hopefully work much better.

**Comment by Fezzik** [comment]
I'm starting to play with your extension. It looks really cool but the use of HintPath is messing with source control. The paths are relative to my local machine, which makes collaborating on scripts a pain. 

I tried using this construct but, when I open the project, your extension "upgrades" the project and removes my edit.

    <Reference Include="Sandbox.Common">
      <HintPath>**$(SpaceEngineersPath)**\Bin64\Sandbox.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>

Any suggestions on how to make MDK play nice with others?

**Comment by malware-dev** [comment]
No. I'm sorry.

**Comment by malware-dev** [comment]
To be more exact: What you're describing is what my problem was originally. I tried using variables but it simply doesn't work.

**Comment by BurningEnlightenment** [comment]
@malware-dev maybe we can work around the absolute paths in the project file by moving the affected assembly references into a separate msbuild file (like `game.props`) and [Import](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017) them back into the project (i.e. `<Import Project="./game.props" />`.

That way one could exclude the `game.props` from version control, but the vsts extension would have to regenerate the second project file on project open. Do you think this is a viable approach?

The `game.props` would look like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <Reference Include="Sandbox.Common">
          <HintPath>c:\program files (x86)\steam\SteamApps\common\SpaceEngineers\Bin64\Sandbox.Common.dll</HintPath>
          <Private>False</Private>
        </Reference>
        
        <!-- ... -->
        
        <Analyzer Include="c:\users\@@@@@\appdata\local\microsoft\visualstudio\15.0_@@@@@\extensions\@@@@@@.@@@\Analyzers\MDKAnalyzer.dll" />
    </ItemGroup>
</Project>
```

And by the way thanks for creating this extension! :+1:

**Comment by malware-dev** [comment]
This seems like a very good idea. I will do some research around the possibility of this.

**Comment by BurningEnlightenment** [comment]
I will do some of the implementation work if you want. However, I'm completely new to VS Extension development 😊

**Comment by malware-dev** [comment]
I will certainly accept any help I can get with gratitude, just make sure you [read the contribution text](https://github.com/malware-dev/MDK-SE/blob/master/CONTRIBUTING.md) first.

**Comment by malware-dev** [comment]
Well this is awkward. I've started, even almost finished it. However I need to make a project upgrader and a system to generate the file when it's missing, but I have no idea when I'll be able to finish it.

**Comment by BurningEnlightenment** [comment]
Can you publish the work on a feature branch? I could then branch off that and contribute the remaining work. Does that sound doable?

**Comment by malware-dev** [comment]
I don't know. While I would very much like the help you can provide, I'm afraid of wasting your time. I'm not even completely certain of _my own_ design on this yet. Due to this I'm not really comfortable of making public something I've yet to finish.

**Comment by malware-dev** [comment]
I have been looking through the branch to see if it's something I can publish. I'm sorry, but the required changes to get this to actually work the way I want it to is just too wide-spread. It affects more than I originally thought. I'm afraid this is something I'll have to do myself. I am very grateful for your willingness to help, though. Rest assured, your idea is just too good to ignore, I _will_ get it done.

**Comment by BurningEnlightenment** [comment]
OK 🙂 

If splitting work makes sense at some point just let me know 😉
