### ISSUE TITLE
MDK intermittently fails to load whitelist cache (MyGridProgram is prohibited)

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#40]
This is a problem reported happening intermittently with new projects. A reproduction has still not been made. If you have this problem, please upload your failing project here. If you can find a reliable reproduction, you are officially awesome.

**Comment by DeckerMMIV** [comment]
In the bigger screenshot that Scav provided in Discord, it is looking for the whitelist.cache file in folder;
`C:\Users\<user>\AppData\AppData\Local\<...etc...>`

Why twice the `AppData` folder-name?

**Comment by Scavenjer** [comment]
[Mine computer.zip](https://github.com/malware-dev/MDK-SE/files/1270936/Mine.computer.zip)
It happened again! Multiple instances of VS were open...

**Comment by Scavenjer** [comment]
[Mine computer.zip](https://github.com/malware-dev/MDK-SE/files/1270974/Mine.computer.zip)

**Comment by malware-dev** [comment]
A cause was found: Visual Studio is generating an invalid relative path for the whitelist file. As a workaround while I try to find a way to trick it to do something else, store your projects _somewhere else_ than under the Users folder.

**Comment by malware-dev** [comment]
I think the solution is to rewrite how this cache is referenced and _not_ use relative paths but just a local cache file for each project and let the project upgrade system also rewrite that cache.
