### ISSUE TITLE
Crashing visual studio with no internet access

### ISSUE THREAD

**Issue by yunsguo** [malware-dev/MDK-SE#42]
When opening a MDK project or solution with no internet access, the whole visual studio crashes.

<img width="960" alt="internetless crash" src="https://user-images.githubusercontent.com/14947503/30096233-52bee970-92a5-11e7-8b9a-c5d41b12b367.png">

by Neunzehn

**Comment by malware-dev** [comment]
Hah. _Someone_ has forgotten exception handling around the version check it seems... 😳

**Comment by malware-dev** [comment]
Surprise surprise, I can't reproduce this error either... 🙄

**Comment by malware-dev** [comment]
The bane of the software developer. Why can't things be easy... 😛

**Comment by malware-dev** [comment]
Apparently my update checker is _not_ unchecked. So I'm afraid I am going to need more information, because now I have _no_ idea at all what is going wrong.

**Comment by yunsguo** [comment]
>    MDK.dll!MDK.MDKPackage.CheckForUpdates() Line 147    C#
is what the exception call stack at
MDK.dll!MDK.MDKPackage.OnSolutionLoaded(EnvDTE.Solution solution) Line 290    C#
is where it is called if you put a break point and step through to get that exception

Tried steeping through the exception and it seems the exception occurs before function returns null but rather around line 70 in ExtendedPackage.cs
