### ISSUE TITLE
Failed to create project: "path" cannot be null

### ISSUE THREAD

**Issue by xyx0826** [malware-dev/MDK-SE#46]
I cannot create an Ingame Script project with the extension. Every time I confirm Visual Studio says the parameter "path" cannot be null, therefore making the directory for the project but leaving nothing inside.

Some warnings are given in the Activity Log when I open the Create Project dialog, if related to this issue:

`
615 | Warning | Found templates with duplicate template ids at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ProjectTemplates\CSharp\Windows\2052\ClassLibrary_WorkerRole.vstemplate" and "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ProjectTemplates\CSharp\Windows\2052\ClassLibrary\csClassLibrary.vstemplate"
616 | Warning | Found templates with duplicate template ids at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ProjectTemplates\CSharp\2052\SharedProject\SharedProject.vstemplate" and "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ProjectTemplates\CSharp\Windows\2052\SharedProject\SharedProject.vstemplate"
617 | Warning | Found templates with duplicate template ids at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ProjectTemplates\VisualBasic\Windows\2052\ClassLibrary_WorkerRole.vstemplate" and "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ProjectTemplates\VisualBasic\Windows\2052\ClassLibrary\classlibrary.vstemplate"
618 | Warning | Error! Cannot access file (C:\Users\[USERNAME]\AppData\Roaming\Microsoft\VisualStudio\15.0_3f523700\ProjectTemplatesCache\cache.bin).
`

And the "null" dialog will pop up together with this line of log:

`
619 | Warning | Performance warning: String load failed. Pkg:{D15F5C78-D04F-45FD-AEA2-D7982D8FA429} (VisualBasicProjectSystemPackage) LANG:0804 ID:2
`

**Comment by malware-dev** [comment]
Your issue sounds like issue #39 . Do you have Space Engineers installed on your development computer? Make sure you've configured MDK to point to the game's binary folder.

**Comment by malware-dev** [comment]
It would seem I've failed to fix it properly though, if you're still getting this issue.

**Comment by malware-dev** [comment]
Nothing in your posted log seems to be relevant to MDK, I'm afraid.

**Comment by xyx0826** [comment]
Thank you. This https://github.com/malware-dev/MDK-SE/issues/39#issuecomment-325283782 worked; I did not configure the game path. This is my first time using this plugin and I was wondering how can this extension get my game path without making me to specify it first... Maybe the wiki need an update to tell people to manually locate the game binaries path.

Also, maybe it's possible to add a more specified error message when auto path finding fails? The extension failed to build on my computer so I have no way to debug it...

**Comment by malware-dev** [comment]
Yes well... two things. First of all it's supposed to find the path by itself, it usually does. I don't know why it didn't for you. Secondly, I thought I _had_ added a proper error message hence why #39 was closed :D

**Comment by xyx0826** [comment]
I think I'm missing some dependencies on my computer to build it. I guess I can find out which step went wrong if fix the compilation issue.

**Comment by malware-dev** [comment]
Did you follow the instructions to the letter?

**Comment by malware-dev** [comment]
Well, I fixed this one now I think.
