### ISSUE TITLE
Build multilingual game translation content

### ISSUE THREAD

**Issue by he381141151** [malware-dev/MDK-SE#47]
Request to add identification xml file inside the text help document content, the establishment of multi-language xml document, so that the game can not identify the translation after the update content. (Such as: Sandbox.Common.xml inside the <member name = "P: Sandbox.ModAPI.Ingame.IMyRadioAntenna.IgnoreOtherBroadcast"> <summary> Ignores broadcasts sent by neutral and enemy antenna </ summary>, can identify <summary> / summary> between the content, build the multi-language translation game help documentation)

**Comment by malware-dev** [comment]
I'm sorry, I don't work for Keen, I cannot alter their documentation.
