### ISSUE TITLE
Typing error in "Debugging your Scripts"

### ISSUE THREAD

**Issue by LynnuxX** [malware-dev/MDK-SE#48]
Minor typo programmers will usually notice immediately => not critical:
_logOutput = GridTerminalSystem.GetBlockWithName("Log LCD") as IMyText**Block**;

Very neat info in that blog, btw. :-)

**Comment by malware-dev** [comment]
Whoopsie... :P The problem with having more than one thought in the head at once... We humans _really_ don't do multitasking well 😛 

Thank you, much appreciated. Will fix immediately!
