### ISSUE TITLE
Using MDK for Mod API?

### ISSUE THREAD

**Issue by Skimt** [malware-dev/MDK-SE#49]
Perhaps the Mod API is not in your line of interest, but thought I would ask just in case. Would it be possible to introduce another template aimed at the Mod API, with references to relevant libraries, and where the debug feedback could say _"The type or member x is prohibited in the Space Engineers Mod API"_ like it does currently for the In-Game API? Or, would it make things too troublesome, or mess with the point or "target audience" of the kit? Would it be pointless to use the MDK just for availability feedback?

Of course, the minifier wouldn't work, nor would deployment, hmm. Maybe in the Script Options, if a particular library is referenced, or if a "Mod API"-option has been ticked, then one would be unable to highlight or select the minifer and deployment options.

**Comment by malware-dev** [comment]
I have mentioned this in the descriptions. I have no interest in mods, I don't use them, so I will not do this. I am likely to accept a pull request with mod api support, but only if the requester would be willing to maintain that part of it. In the mean time, the internals of MDK is currently undergoing a rather big change so it's probably not a good idea for anyone to do that just yet.

**Comment by Skimt** [comment]
I beg your pardon. I should've read through the description more thoroughly; I missed it. I'll be looking forward to the new update.

**Comment by malware-dev** [comment]
Haha, no worries, it's not like I'm expecting _anyone_ to read that stuff... 😛
