### ISSUE TITLE
Deploying script error

### ISSUE THREAD

**Issue by thorwin99** [malware-dev/MDK-SE#50]
When i try deploying the script, i get this error
`System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: obj
   bei Microsoft.Internal.VisualStudio.PlatformUI.Utilities.GetObjectData(IVsUIObject obj)
   bei Microsoft.VisualStudio.PlatformUI.StatusBarService.GetImageListFromMonikers(IEnumerable`1 monikerList)
   bei Microsoft.VisualStudio.PlatformUI.StatusBarService.GetBuiltInAnimation(StatusBarAnimationIndex statusBarAnimationIndex)
   bei Microsoft.VisualStudio.PlatformUI.StatusBarService.StartAnimation(Object animationInfoKey, Boolean isBuiltInAnimation)
   bei Microsoft.VisualStudio.PlatformUI.StatusBarService.Animation(Int32 fOnOff, Object& pvIcon)
   bei MDK.VisualStudio.StatusBarAnimation.set_IsEnabled(Boolean value) in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\VisualStudio\StatusBarAnimation.cs:Zeile 69.
   bei MDK.MDKPackage.<Deploy>d__49.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:Zeile 0.`

**Comment by malware-dev** [comment]
Now that's interesting... What on earth is different with _your_ setup that makes this happen? This error is deep within Visual Studio's code, all I'm doing is enabling the animation... At any rate I can probably protect against an error here, I will get you a fix tomorrow.

**Comment by thorwin99** [comment]
The error occured after i updated MDK from an older Version, where everything worked fine. I also tested it in some more Projects if it had something to do with that. I havent updated to a new Version of VS2017 in a while.

**Comment by malware-dev** [comment]
🤔 Well this particular code hasn't changed since the earlier versions of MDK. It would be interesting to know if this happens after updating Visual Studio, but I'll be wrapping this call so it crashing don't crash the entire plugin. I mean, this is just a visual thing after all.

**Comment by malware-dev** [comment]
Should hopefully be fixed in 1.0.11.

**Comment by thorwin99** [comment]
Ok i updated VS now and its working with the old version... Had something to do with the VS version I had installed.

**Comment by malware-dev** [comment]
Good to know, thank you very much!
