### ISSUE TITLE
[Request]  Date and Time strings for when 'deployed'

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#51]
It would be nice to display when the script was deployed to help with supporting users and checking that they have the current version.

I propose that the standard date the time pre-processor definitions be used.

https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html

so then a script could use:
string DeployDate=__DATE__;
string DeployTime=__TIME__;

or
string Deployed=__DATE__ + " " + __TIME__;

Since these are not supported by Standard C#, the defines may have to be changed to require quotes so that they don't generate compile errors::

string DeployDate="__DATE__";
string DeployTime="__TIME__";

or
string Deployed="__DATE__" + " " + "__TIME__";

**Comment by malware-dev** [comment]
While the idea itself is very good, I cannot and will not implement something that can interfere with people's code. It's just too probable that people already have strings looking like that.

I cannot promise anything, but I'll see if I can come up with... _something_.

**Comment by malware-dev** [comment]
Note to self: Some kind of tag to indicate that MDK should run macros on constants?

```cs
//#mdk macro
const string DeploymentData = "Deployed %DATE% %TIME%";
```
or
```cs

public void Main() {
#region MDK Macro // enable string macro processing inside this region
        var deploymentDate = DateTime.Parse("%DATE% %TIME%");
#endregion
}

#region MDK macro
const string DATE = "%DATE%";
const string TIME = "%TIME%";
#endregion
```

**Comment by Wicorel** [comment]
I notice it took out the underscores on those examples.  

They should be __DATE__ and __TIME__.

Those are ANSI(?) standard pre-processor defines, so 'normal' could should not be using them.
