### ISSUE TITLE
Script Blueprint Manager window coloring issue

### ISSUE THREAD

**Issue by XkyRauh** [malware-dev/MDK-SE#52]
When Deploying scripts, the Script Blueprint Manager window comes up with a list of all scripts, with the recently deployed script highlighted in a yellow color.  This works fine if the user highlights other scripts in the list, as pictured below:
![untitled2](https://user-images.githubusercontent.com/30872131/34083634-832769ce-e328-11e7-9133-50900ba7f65d.png)

However, when the user clicks to highlight the recently deployed script itself, the color of the lettering turns white (as it is selected) but the background remains the yellow color, making the script title very difficult to read:
![untitled](https://user-images.githubusercontent.com/30872131/34083660-c6b5be3e-e328-11e7-92a2-09714a2efbcb.png)

This may be a Visual Studio issue, though, as it is present on each of the "Light," "Dark," "Blue," and "Blue (extra contrast)" color themes.

**Comment by malware-dev** [comment]
Oh rly? :P Clearly VS is overriding _some_ system colors but not others. Thank you Visual Studio...

**Comment by malware-dev** [comment]
I can't reproduce this. Is it still happening? Do you have some unusual Windows theme or something? Because I'm actually not explicitly coloring that text at all.

**Comment by malware-dev** [comment]
Since there's been two weeks since my request for an update without any answer I will assume this is no longer an issue.
