### ISSUE TITLE
Use JPEG thumb instead of PNG one

### ISSUE THREAD

**Issue by min050820** [malware-dev/MDK-SE#54]
Publishing to Steam Workshop fails, if thumb file is in PNG. But it works with JPEG file.

I just published a script that way, so it's pretty verified.

**Comment by malware-dev** [comment]
PNGs have been verified too, so if it fails with the PNG something must either have changed on Steam or there's a problem with Steam.

**Comment by min050820** [comment]
Oh, is that so? That's weird, since my script kept failing but it got published as soon as I changed the thumb to JPEG file a PNG file. Plus, there are [discussions like this](https://steamcommunity.com/app/244850/discussions/0/412447524178817357/).

So.... I'm not sure if it really is a bug or I just happened to try uploading when Steam server was down or something. I'll test again and will let you know the result as soon as I get to my home.

**Comment by malware-dev** [comment]
Oh I don't doubt for a second that you have had a problem, I just find it strange that this is the first I hear of this problem.

**Comment by malware-dev** [comment]
May I ask what happened?

**Comment by malware-dev** [comment]
Is this still a problem?

**Comment by min050820** [comment]
Oh, I'm terribly sorry! I just forgot about this issue.

I can't test the issue right now because I'm in a strict dorm, so I'll close the issue and let you know when I could test the issue.

**Comment by malware-dev** [comment]
Ok, thank you. I will ask in Keen's discord channel whether others have experienced this in the mean time.
