### ISSUE TITLE
[Question] Setup actions in Sensors/AirVents/Buttons

### ISSUE THREAD

**Issue by MrDj200** [malware-dev/MDK-SE#55]
Hello,
is there a way (via ingame scripts) to setup actions for a Sensor?

For example:
I wanna make a AirLock thingy(activated over antenna command), but don't really want to use Timer Blocks, so I use the Actions in an AirVent to open the doors once the room is depressurized.

Is this even possible, or does SE not provide methods for that?

-Dj

**Comment by malware-dev** [comment]
Hello, MrDj. I must ask you to keep scripting questions either to [Keen's discord](https://discord.gg/0hIE7GirODUqhfIg) or [the programming forums](https://forums.keenswh.com/forums/programming-in-game.410940/) (Discord usually providing faster answers, I'm often there too). _This_ site is purely for issues regarding MDK or the wiki 🙂 

To answer your question though, programmable blocks cannot change block actions. You do not need to use timer blocks any more either: See [continuous running](https://github.com/malware-dev/MDK-SE/wiki/Continuous-Running-No-Timers-Needed).

**Comment by MrDj200** [comment]
Oops, sorry. Gonna keep that in mind.

Thanks for the answer ^^
