### ISSUE TITLE
[Wiki] Small Typo in Continuous-Running-No-Timers-Needed

### ISSUE THREAD

**Issue by Morketh** [malware-dev/MDK-SE#56]
Under the section 
 

> More than one UpdateType per call 

in the second code example your comment says: 
```If the update source is either Trigger or Terminal, run the continuous logic```

However in the function definition:
```
void RunCommand(string argument)
{
  // Perform interactive logic
}
```
Its not that big of a typo but does add a little confusion when reading for the first time.
EDIT: Added full example for clarity.
```
const UpdateType CommandUpdate = UpdateType.Trigger | UpdateType.Terminal;

public void Main(string argument, UpdateType updateType) 
{
  // If the update source is either Trigger or Terminal, run the continuous logic
  if ((updateType & CommandUpdate) != 0) 
  {
    RunCommand(argument);
  }
}

void RunCommand(string argument)
{
  // Perform interactive logic
}
```

**Comment by malware-dev** [comment]
Yep 😄 

Thank you very much, fixed
