### ISSUE TITLE
[pre] MDK Preserve doesnt stop at end of region

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#61]
// <mdk sortorder="-100" />
using Sandbox.Game.EntityComponents;
using Sandbox.ModAPI.Ingame;
using Sandbox.ModAPI.Interfaces;
using SpaceEngineers.Game.ModAPI.Ingame;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System;
using VRage.Collections;
using VRage.Game.Components;
using VRage.Game.ModAPI.Ingame;
using VRage.Game.ObjectBuilders.Definitions;
using VRage.Game;
using VRageMath;

namespace IngameScript
{
    partial class Program : MyGridProgram
    {
#region mdk preserve
        // This script was deployed at $MDK_DATETIME$
        const string Deployment = "$MDK_DATE$, $MDK_TIME$";
#endregion

    }
}

Results in the entire solution being uncompressed.

**Comment by malware-dev** [comment]
Ok so this happens when the endregion is the last thing in a class?

**Comment by Wicorel** [comment]
Affirm.  Adding a line after the regions works correctly.
```
namespace IngameScript
{
    partial class Program : MyGridProgram
    {
        #region mdk preserve
        #region mdk macros
        // This script was deployed at $MDK_DATETIME$
        const string Deployment = "$MDK_DATE$, $MDK_TIME$";
        #endregion
        #endregion
        int test123 = 123;
    }
}

```

**Comment by malware-dev** [comment]
Ok this is really strange. Roslyn don't seem to report the endregion at all in this case. That's a problem.
