### ISSUE TITLE
[feature] Give warning/nag on detection of static variable definitions

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#65]
Give the user a warning or nag about using static variables in the code.

If dialog in UI is not possible or even 'friendly', then maybe add a comment at the top of the generated source file with a comment about statics being bad, m'kay.

// use of statics in SpaceEngineers is bad, m'kay
// Statics detected:

**Comment by kwilliams1987** [comment]
> If dialog in UI is not possible or even 'friendly', then maybe add a comment at the top of the generated source file with a comment about statics being bad, m'kay.
> // use of statics in SpaceEngineers is bad, m'kay
> // Statics detected:

Or just add them as compiler warnings.

**Comment by malware-dev** [comment]
It would just be another analysis result in the same vein as the whitelist processing, no big deal.

**Comment by malware-dev** [comment]
I've decided not to do this.
