### ISSUE TITLE
[Minor] Extra line added when deploying

### ISSUE THREAD

**Issue by Der-Isy** [malware-dev/MDK-SE#68]
When deploying a script with the malware mdk 1.1.8 on VS 15.7.3, an extra blank line is added to the top of the script.

So basically:

```C#
1 partial class Program : MyGridProgram
2 {
3 	// some Code
4 }
```

will become:

```C#
1
2 // some Code
```

in the ingame script editor instead of:

```C#
1 // some Code
```

(line numbers added for better understanding - not actual code)

I'm not quite sure, whether this is the MDK's fault or VS tab settings (tabs are set to be kept instead of being converted to whitespaces). Removing all tabs at the front didn't help. Placing the opening bracket in the class line didn't help either.

**Comment by malware-dev** [comment]
Thank you for your report. Most likely the newline after { is being preserved where it shouldn't.

**Comment by Der-Isy** [comment]
I know you're probably very busy lately but I saw, that you published some new versions of the MDK.. Unfortunately the error is still present in the latest version. Is it still on your todo list?

**Comment by malware-dev** [comment]
It is. I can only apologize; I honestly forgot in the hustle to get an MP-update compatible version out... I'll get my behind in gear.

**Comment by malware-dev** [comment]
Interesting. I'm not seeing the behavior you're reporting. In my tests, not even the comment is output.

**Comment by Der-Isy** [comment]
Okay, to be completely honest: I never tested it the way I posted it.. On further investigation I found out, that it only shows something in the PB afterwards, if at least one "real" command is used like a variable declaration or even an empty main method. If only comments are in the script, it deploys it empty..

For example:
```C#
1 partial class Program : MyGridProgram
2 {
3 	// Declare something
4	int something = 1;
5 }
```

will become:

```C#
1
2 	// Declare something
3	int something = 1;
```

whereas:

```C#
1 partial class Program : MyGridProgram
2 {
3 	// Declare something
4	// or maybe not..
5 }
```

will be blank after deploying.. Sorry for my misleading first example..

**Comment by malware-dev** [comment]
No worries, I've got it covered 😄 You showed two different bugs here. I've fixed the one you _actually_ reported, but not the other one yet.

**Comment by Der-Isy** [comment]
Awesome! Keep up your great work! I really love how your MDK simplifies a lot in developing and publishing SE scripts!

**Comment by malware-dev** [comment]
I'm _so_ sorry this is taking so long, @Der-Isy. I hit a problem with the secondary issue and I've got limited time... However I will _try_ to get your actually reported bug in together with the minifier issue at #73 as I cannot really justify releasing a fix _just_ for an extra whitespace line, and crashes needs to have priority anyway 😄 Thank you for being so patient.

**Comment by Der-Isy** [comment]
Take your time @malware-dev ! My issues is no big deal - it's just a cosmetic thing. If you fix it along with another real bug fix update, it's early enough for me ;)

**Comment by malware-dev** [comment]
Ok so... apparently I fixed one issue and caused another 😒 

I'm sorry, but I can't spend more time trying to trick Roslyn into doing what I want right now. I'll get to it eventually.

**Comment by malware-dev** [comment]
Ugh. The "fix" caused more problems than it fixed.

**Comment by Der-Isy** [comment]
I still use 1.1.17 right now - everything seems to be fine. Where exactly are the problems if I may ask?

**Comment by malware-dev** [comment]
Please see #75

**Comment by Der-Isy** [comment]
Oh my god.. What have I done.. I opened pandora's box :-/

**Comment by malware-dev** [comment]
I don't know if the changes in how MDK works has fixed this, but I probably won't be fixing this particular issue.
