### ISSUE TITLE
Doesn't produce any project files besides root project directory

### ISSUE THREAD

**Issue by iamtakingiteasy** [malware-dev/MDK-SE#69]
Visual Studio Community 2017 15.7.4
MDK/SE 1.1.8

Upon creation of project with Space Engineers ingame template, error box is popped out with message
"Cannot find the MDK/SE settings. The install might be corrupted. Please reinstall the extension.", however reinstalling MDK/SE has no effect and I seem to have the said settings:
https://static.eientei.org/data/94610883-5e4b-49d0-b992-a7fd6c66e888.png

No files besides project root directory are created.

**Comment by malware-dev** [comment]
This is likely to be the same issue as #66 . He was able to fix his problem (it's not really a problem with MDK). Maybe you can do what he did.

**Comment by iamtakingiteasy** [comment]
No, unlike in #66 i have no problem with creating **Console App (.NET Framework)** projects, only with **Ingame Script** of MDK/SE. And reinstalling Microsoft.Build.Framework by hand with gacutil had no effect on this issue.

I suspect that actual settings are not being injected into VS config if they was not present there before the installation of MDK, try fresh VS2017 instance without your current configuration.

Odd-looking to me are:
- missing explcit GUID on https://github.com/malware-dev/MDK-SE/blob/master/Source/MDK/Services/MDKOptions.cs -- not sure if it is being generated by VS and if so -- how to predict one.
- lookup for ["MDK/SE", "Options"] in https://github.com/malware-dev/MDK-SE/blob/ff0f9c57ba3605cbfa6d06ae03023a93659e0f2f/Source/MDK/Services/IngameScriptWizard.cs#L146 while actual category seems to be just ["MDK/SE"] as defined in MDKOptions.cs.

**Comment by malware-dev** [comment]
I have already tried a fresh installation of course, not to mention the people who have installed this extension completely fresh without any prior knowledge of programming _or_ Visual Studio. This is not something that every user is plagued with. Out of several hundred downloads there has been two complaints, as you have proven due to two different causes. So it's not quite so simple :)

**Comment by malware-dev** [comment]
(actually, it's not "several" hundred for this particular version. Only 225 at this point in time. But the point remains 😄 )

**Comment by malware-dev** [comment]
I am quite confident on the lookup on your second point, as nothing would ever work if that was wrong.  As for your first point though; I'm not sure whick explicit GUID you mean. Visual Studio Extension programming is not easy, there's very little documentation and what documentation there _is_ is contradictory. So if you know something I don't, I will be _very_ happy to learn!

**Comment by malware-dev** [comment]
Actually that's half a lie. It's not so much that there's very little documentation, it's just that it's so nonspecific, examples for outdated versions or just plain wrong.

**Comment by iamtakingiteasy** [comment]
As it hurts to admit, but yes, removing whole system of win10 drive and reinstalling it from scratch did resetted some state and enabled me to be able to create a project with MDK. Guess, my issue is closed, but this is hardly a way to deal with actual problem.

**Comment by malware-dev** [comment]
No, it certainly isn't, but as long as it's not possible for me to find an actual issue in MDK itself there isn't much I can do about it. 🙁
