### ISSUE TITLE
can't install?

### ISSUE THREAD

**Issue by patc4** [malware-dev/MDK-SE#71]
double clicking the .vsix file does nothing, how am I supposed to use this?

**Comment by patc4** [comment]
yep, i followed the wiki.  I have visual studio community 2017 installed.

**Comment by malware-dev** [comment]
I'm afraid I don't know. Clicking the vsix should just work. I can only guess that you're having a problem with your Visual Studio installation.

**Comment by patc4** [comment]
turns out when it says to restart the computer after install, it means you have no choice or nothing will work.  never have been a big fan of restarting my computer as it takes a while.

**Comment by patc4** [comment]
sorry for the trouble.

**Comment by malware-dev** [comment]
No trouble. Thank you for letting me know 😄
