### ISSUE TITLE
[Wiki] Unexpected Error on Deploy

### ISSUE THREAD

**Issue by markozar** [malware-dev/MDK-SE#73]
Options for deploy were:
- Trim Unused Types
- Minify

It works without Minify.
The script compiles under Visual Studio 2017 and it also works in Space Engineers.

Log:
=====================
MDK.Build.BuildException: Error generating script for  ---> System.ArgumentException: Do not understand the declaration type
Nome parametro: declaration
   in MDK.Build.AnalysisExtensions.GetFullName(MemberDeclarationSyntax declaration, DeclarationFullNameFlags flags) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\AnalysisExtensions.cs:riga 136
   in MDK.Build.Composers.Minifying.CodeSimplifier.ShouldRemoveModifier(SyntaxNode node) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\Composers\Minifying\CodeSimplifier.cs:riga 62
   in MDK.Build.Composers.Minifying.CodeSimplifier.VisitDelegateDeclaration(DelegateDeclarationSyntax node) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\Composers\Minifying\CodeSimplifier.cs:riga 185
   in Microsoft.CodeAnalysis.CSharp.Syntax.DelegateDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   in Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   in MDK.Build.Composers.Minifying.ProgramRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\Composers\Minifying\ProgramRewriter.cs:riga 24
   in Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   in Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   in MDK.Build.Composers.Minifying.CodeSimplifier.<ProcessAsync>d__16.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\Composers\Minifying\CodeSimplifier.cs:riga 278
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MDK.Build.Composers.Minifying.MinifyingComposer.<GenerateAsync>d__0.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\Composers\Minifying\MinifyingComposer.cs:riga 30
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MDK.Build.BuildModule.<ComposeScriptAsync>d__28.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:riga 179
   --- Fine della traccia dello stack dell'eccezione interna ---
   in MDK.Build.BuildModule.<ComposeScriptAsync>d__28.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:riga 184
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MDK.Build.BuildModule.<BuildAsync>d__27.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:riga 162
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:riga 116
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in MDK.MDKPackage.<DeployAsync>d__50.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:riga 367

**Comment by markozar** [comment]
Here is the script I tried to compile with the above options. Just a note: it worked unitl I added more lines today.

============================
using Sandbox.Game.EntityComponents;
using Sandbox.ModAPI.Ingame;
using Sandbox.ModAPI.Interfaces;
using SpaceEngineers.Game.ModAPI.Ingame;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System;
using VRage.Collections;
using VRage.Game.Components;
using VRage.Game.ModAPI.Ingame;
using VRage.Game.ModAPI.Ingame.Utilities;
using VRage.Game.ObjectBuilders.Definitions;
using VRage.Game;
using VRageMath;

namespace IngameScript {
    partial class Program : MyGridProgram {
        // Airlock system ======================
        private IMySensorBlock _airlockSensor;
        private IMyDoor _externalDoors;
        private IMyDoor _internalDoors;
        private IMyAirVent _vent;

        // Warning lights system ======================
        private List<IMyTerminalBlock> _lights = new List<IMyTerminalBlock>();

        // Inventory list system ======================
        private IMyTextPanel _lcdComponents;
        private IMyTextPanel _lcdMaterials;
        private IMySensorBlock _inventorySensor;
        private bool _updateInventory = false; // Keeps updating the inventory only inside sensor inventory range
        private List<MyDetectedEntityInfo> _entities = new List<MyDetectedEntityInfo>();
        private List<IMyTerminalBlock> _inventories = new List<IMyTerminalBlock>();
        private SortedDictionary<string, float> _inventoryComponents = new SortedDictionary<string, float>();
        private SortedDictionary<string, float> _inventoryIngots = new SortedDictionary<string, float>();
        private SortedDictionary<string, float> _inventoryOres = new SortedDictionary<string, float>();

        private delegate string _GetDisplayName(string name, string type);
        private _GetDisplayName GetDisplayName;

        public Program() {
            //This makes the program automatically run every 100 ticks for timed events
            Runtime.UpdateFrequency = UpdateFrequency.Update100;

            // Airlock system (trigger event) ======================
            _airlockSensor = GridTerminalSystem.GetBlockWithName("Airlock Sensor") as IMySensorBlock;
            _externalDoors = GridTerminalSystem.GetBlockWithName("External door") as IMyDoor;
            _internalDoors = GridTerminalSystem.GetBlockWithName("Internal door") as IMyDoor;
            _vent = GridTerminalSystem.GetBlockWithName("Door Vent") as IMyAirVent;

            // Warning lights system (timed event) ======================
            var warningLights = GridTerminalSystem.GetBlockGroupWithName("Warning lights");
            warningLights.GetBlocks(_lights);

            // Inventory list system (timed event) ======================
            _lcdComponents = GridTerminalSystem.GetBlockWithName("Components LCD") as IMyTextPanel;
            _lcdMaterials = GridTerminalSystem.GetBlockWithName("Materials LCD") as IMyTextPanel;

            GridTerminalSystem.SearchBlocksOfName("[INV]", _inventories); // valid for cargos, assemblers and refineries
            GetDisplayName = PartialDisplayName;
            //GetDisplayName = FullDisplayName;

            _inventorySensor = GridTerminalSystem.GetBlockWithName("Inventory Sensor") as IMySensorBlock;
        }

        //public void Save() {
        //    // Called when the program needs to save its state. Use
        //    // this method to save your state to the Storage field
        //    // or some other means. 
        //    // 
        //    // This method is optional and can be removed if not
        //    // needed.
        //}

        public void Main(string argument, UpdateType updateSource) {
            // Airlock system
            if (updateSource == UpdateType.Trigger && argument == "airlock") {
                ManageAirLock();
            }

            if (updateSource == UpdateType.Trigger && argument == "inventory") {
                _updateInventory = true;

            }

            if (updateSource == UpdateType.Update100) {
                ManageWarningLights();
                if (_updateInventory) {
                    ManageInventoryList();
                    _inventorySensor.DetectedEntities(_entities);
                    if(_entities.Count == 0) {
                        _updateInventory = false;
                    }
                }
            }
        }

        void ManageAirLock() {
            //_lcd.WritePublicText("Vent status: " + _vent.Status, false);
            if (_vent.Status == VentStatus.Depressurizing || _vent.Status == VentStatus.Depressurized) {
                // Pressurization sequence
                _externalDoors.ApplyAction("Open_Off");
                _vent.ApplyAction("Depressurize_Off");
            } else {
                // Depressurization sequence
                _internalDoors.ApplyAction("Open_Off");
                _vent.ApplyAction("Depressurize_On");
            }
        }

        void ManageWarningLights() {
            foreach (IMyTerminalBlock light in _lights) {
                light.ApplyAction("OnOff");
            }
        }

        void ManageInventoryList() {
            _inventoryComponents.Clear();
            _inventoryIngots.Clear();
            _inventoryOres.Clear();
            foreach (IMyEntity inventory in _inventories) {
                var inv = inventory.GetInventory();
                if(inv != null) {
                    var inventoryItems = inv.GetItems();
                    foreach (IMyInventoryItem item in inventoryItems) {
                        SortInventory(item);
                    }
                } else {
                    var inventoryItems = inventory.GetInventory(0).GetItems();
                    foreach (IMyInventoryItem item in inventoryItems) {
                        SortInventory(item);
                    }
                    inventoryItems = inventory.GetInventory(1).GetItems();
                    foreach (IMyInventoryItem item in inventoryItems) {
                        SortInventory(item);
                    }

                }
            }
            _lcdComponents.WritePublicText("Components:\n-------------------------------------------\n", false);
            WriteToLCD(_lcdComponents, _inventoryComponents, QuantityFormatter);
            _lcdMaterials.WritePublicText("Ingots:\n-------------------------------------------\n", false);
            WriteToLCD(_lcdMaterials, _inventoryIngots, WeightFormatter);
            _lcdMaterials.WritePublicText("\nOres:\n-------------------------------------------\n", true);
            WriteToLCD(_lcdMaterials, _inventoryOres, WeightFormatter);
        }

        void WriteToLCD(IMyTextPanel lcd, SortedDictionary<string, float> inventory, Func<float,string> formatter) {
            foreach (KeyValuePair<string, float> e in inventory) {
                lcd.WritePublicText($"{e.Key} {formatter(e.Value)}\n", true);
            }
        }

        void SortInventory(IMyInventoryItem item) {
            string itemName = item.ToString().Split('/')[1];
            string itemType = item.Content.TypeId.ToString().Split('_')[1];
            string name = GetDisplayName(itemName, itemType);
            float amount = (float)item.Amount;
            switch (itemType) {
                case "Ingot":
                    if (_inventoryIngots.ContainsKey(name)) {
                        _inventoryIngots[name] += amount;
                    } else {
                        _inventoryIngots[name] = amount;
                    }
                    break;
                case "Ore":
                    if (_inventoryOres.ContainsKey(name)) {
                        _inventoryOres[name] += amount;
                    } else {
                        _inventoryOres[name] = amount;
                    }
                    break;
                default:
                    if (_inventoryComponents.ContainsKey(name)) {
                        _inventoryComponents[name] += amount;
                    } else {
                        _inventoryComponents[name] = amount;
                    }
                    break;
            }
        }

        string WeightFormatter(float amt) {
            if (amt > 1000.0f) {
                return $"{Math.Round(amt / 1000.0f, 2)} Tons";
            } else {
                return $"{Math.Round(amt, 2)} kg";
            }
        }

        string QuantityFormatter(float amt) {
            if (amt > 1000.0f) {
                return $"{Math.Round(amt / 1000.0f, 2)}k";
            } else {
                return $"{Math.Round(amt, 2)}";
            }
        }

        private string PartialDisplayName(string name, string type) {
            var displayName = "";
            switch (type) {
                case null: displayName = "NOT AN ITEM"; break;
                case "Ingot":
                    switch (name) {
                        case "Magnesium": displayName = "Magnesium Powder"; break;
                        case "Scrap": displayName = "Old Scrap Metal"; break;
                        case "Silicon": displayName = "Silicon Wafer"; break;
                        case "Stone": displayName = "Gravel"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "Ore":
                    switch (name) {
                        case "Ice": displayName = "Ice"; break;
                        case "Organic": displayName = "Organic"; break;
                        case "Scrap": displayName = "Scrap Metal"; break;
                        case "Stone": displayName = "Stone"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "PhysicalGunObject":
                    switch (name) {
                        case "AngleGrinder2Item": displayName = "Enhanced Grinder"; break;
                        case "AngleGrinder3Item": displayName = "Proficient Grinder"; break;
                        case "AngleGrinder4Item": displayName = "Elite Grinder"; break;
                        case "AngleGrinderItem": displayName = "Grinder"; break;
                        case "AutomaticRifleItem": displayName = "Automatic Rifle"; break;
                        case "HandDrill2Item": displayName = "Enhanced Hand Drill"; break;
                        case "HandDrill3Item": displayName = "Proficient Hand Drill"; break;
                        case "HandDrill4Item": displayName = "Elite Hand Drill"; break;
                        case "HandDrillItem": displayName = "Hand Drill"; break;
                        case "PreciseAutomaticRifleItem": displayName = "Precise Automatic Rifle"; break;
                        case "RapidFireAutomaticRifleItem": displayName = "Rapid-Fire Automatic Rifle"; break;
                        case "UltimateAutomaticRifleItem": displayName = "Elite Automatic Rifle"; break;
                        case "WelderItem": displayName = "Welder"; break;
                        case "Welder2Item": displayName = "Enhanced Welder"; break;
                        case "Welder3Item": displayName = "Proficient Welder"; break;
                        case "Welder4Item": displayName = "Elite Welder"; break;
                        default: displayName = name; break;
                    }
                    break;
                default:
                    displayName = name; break;
            }
            return displayName;
        }

        private string FullDisplayName(string name, string type) {
            var displayName = "";
            switch (type) {
                case null: displayName = "NOT AN ITEM"; break;
                case "AmmoMagazine":
                    switch (name) {
                        case "Missile200mm": displayName = "200mm missile container"; break;
                        case "NATO_25x184mm": displayName = "25x184mm NATO ammo container"; break;
                        case "NATO_5p56x45mm": displayName = "5.56x45mm NATO magazine"; break;
                        default: displayName = name + " " + type; break;
                    }
                    break;
                case "Component":
                    switch (name) {
                        case "Construction": displayName = "Construction Component"; break;
                        case "Detector": displayName = "Detector Components"; break;
                        case "GravityGenerator": displayName = "Gravity Generator Components"; break;
                        case "InteriorPlate": displayName = "Interior Plate"; break;
                        case "Medical": displayName = "Medical Components"; break;
                        case "MetalGrid": displayName = "Metal Grid"; break;
                        case "PowerCell": displayName = "Power Cell"; break;
                        case "RadioCommunication": displayName = "Radio-communication Components"; break;
                        case "Reactor": displayName = "Reactor Components"; break;
                        case "SolarCell": displayName = "Solar Cell"; break;
                        case "SteelPlate": displayName = "Steel Plate"; break;
                        case "LargeTube": displayName = "Large Steel Tube"; break;
                        case "SmallTube": displayName = "Small Steel Tube"; break;
                        case "Superconductor": displayName = "Superconductor Conduits"; break;
                        case "Thrust": displayName = "Thruster Components"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "GasContainerObject":
                    switch (name) {
                        case "HydrogenBottle": displayName = "Hydrogen Bottle"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "OxygenContainerObject":
                    switch (name) {
                        case "OxygenBottle": displayName = "Oxygen Bottles"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "Ingot":
                    switch (name) {
                        case "Magnesium": displayName = "Magnesium Powder"; break;
                        case "Scrap": displayName = "Old Scrap Metal"; break;
                        case "Silicon": displayName = "Silicon Wafer"; break;
                        case "Stone": displayName = "Gravel"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "Ore":
                    switch (name) {
                        case "Ice": displayName = "Ice"; break;
                        case "Organic": displayName = "Organic"; break;
                        case "Scrap": displayName = "Scrap Metal"; break;
                        case "Stone": displayName = "Stone"; break;
                        default: displayName = name; break;
                    }
                    break;
                case "PhysicalGunObject":
                    switch (name) {
                        case "AngleGrinder2Item": displayName = "Enhanced Grinder"; break;
                        case "AngleGrinder3Item": displayName = "Proficient Grinder"; break;
                        case "AngleGrinder4Item": displayName = "Elite Grinder"; break;
                        case "AngleGrinderItem": displayName = "Grinder"; break;
                        case "AutomaticRifleItem": displayName = "Automatic Rifle"; break;
                        case "HandDrill2Item": displayName = "Enhanced Hand Drill"; break;
                        case "HandDrill3Item": displayName = "Proficient Hand Drill"; break;
                        case "HandDrill4Item": displayName = "Elite Hand Drill"; break;
                        case "HandDrillItem": displayName = "Hand Drill"; break;
                        case "PreciseAutomaticRifleItem": displayName = "Precise Automatic Rifle"; break;
                        case "RapidFireAutomaticRifleItem": displayName = "Rapid-Fire Automatic Rifle"; break;
                        case "UltimateAutomaticRifleItem": displayName = "Elite Automatic Rifle"; break;
                        case "WelderItem": displayName = "Welder"; break;
                        case "Welder2Item": displayName = "Enhanced Welder"; break;
                        case "Welder3Item": displayName = "Proficient Welder"; break;
                        case "Welder4Item": displayName = "Elite Welder"; break;
                        default: displayName = name; break;
                    }
                    break;
                default:
                    displayName = name; break;
            }
            return displayName;
        }
    }
}

**Comment by markozar** [comment]
I made some tries, and it seems that the problem arises with delegates

**Comment by malware-dev** [comment]
Thank you for your report. I will investigate as soon as I am able.
