### ISSUE TITLE
Runtime.UpdateFrequency not defined

### ISSUE THREAD

**Issue by proffzulus** [malware-dev/MDK-SE#74]
IMyGridProgramRuntimeInfo does not contain a definition of Runtime.UpdateFrequency.

Possible Fix:
//somewhere in namespace:

```
    enum UpdateFrequency
{
    Update1,
    Update10,
    Update100,
    Once
}
```

   ```
 public interface IMyGridProgramRuntimeInfo
    {
// previous code
      UpdateFrequency UpdateFrequency {get; set;}
    }


```

Usage then should be easy and straight as documented:
```
//somewhere in constructor
Runtime.UpdateFrequency = UpdateFrequency.Update10;
```

**Comment by malware-dev** [comment]
I'm sorry, but you're doing something wrong. The API used here is the _exact_ same is is being used in the game, I don't have a custom one, and people are using Runtime.UpdateFrequency all over, including myself 😄
