### ISSUE TITLE
Leading spaces has increased. 1.1.17

### ISSUE THREAD

**Issue by Elfiwolfe** [malware-dev/MDK-SE#75]
version 1.1.16
 *    1.187.089 Major Optimization
 *    1.187.088 added 6 * sec autolevel
 *    1.187.087 Optimization
 */

// O.I.S. Ship Main Computer Mk 2

//Run options
bool stopShipIfNotPiloted = true;
bool runAutoLevel = false;//runs auto leveling in natural Gravity
bool rocketGyro = false;//false if RC bottom towards gravity, true if RC back toward gravity
bool runAutoLevel6 = false;//runs auto level 6/1 sec

version 1.1.17
 *    1.187.100 removed mp temp fix
 *    1.187.089 Major Optimization
 *    1.187.088 added 6 * sec autolevel
 *    1.187.087 Optimization
 */
        // O.I.S. Ship Main Computer Mk 2

        //Run options
        bool stopShipIfNotPiloted = true;
        bool runAutoLevel = false;//runs auto leveling in natural Gravity
        bool rocketGyro = false;//false if RC bottom towards gravity, true if RC back toward gravity
        bool runAutoLevel6 = false;//runs auto level 6/1 sec

The top part of each segment is the end of Readme.
the bottom part of each segment is the start of program

**Comment by XkyRauh** [comment]
Agreeing with Elfi.  Noticed the leading spaces appear after the most recent VS update.

**Comment by malware-dev** [comment]
Fixed by reverting the "fix" that caused it
