### ISSUE TITLE
Deploy option in files.

### ISSUE THREAD

**Issue by oedze** [malware-dev/MDK-SE#79]
I have installed the MDK, and i am really happy about it!

However, I am not really a mouse person. so i mapped the "Deploy MDK  script" to a keyboard shortcut. 
This works fine when you have the project selected in the Solution Explorer, but, when you have a file selected. It is not possible to use the shortcut, because the option is not available for files.

I would love it if you can make it so that a Deploy MDK script button would be available when you select the files as well. This would fix that a shortcut won't work on files.

Thanks you in advance!

**Comment by malware-dev** [comment]
A-haa, so _that_ is why it only works some times!

**Comment by oedze** [comment]
Did i just find the cause of your problem?

**Comment by malware-dev** [comment]
I just wanted to say I haven't forgotten you. I just haven't found a good solution for this quite yet and other things have taken precedence.
