### ISSUE TITLE
Error Deploying MDK

### ISSUE THREAD

**Issue by idapixl** [malware-dev/MDK-SE#83]
I am receiving this error when I attempt to Deploy MDK Script.
[Error.txt](https://github.com/malware-dev/MDK-SE/files/2307971/Error.txt)
I cleaned up my computer and updated a few things after not using this for a few months. I'm not sure if I caused this somehow by moving or deleting something or if has something to do with the updates.

Windows 10
Using Visual Studios v15.8.1
MDK is showing that it is fully updated. Thank you for your help!

**Comment by malware-dev** [comment]
Hi. Are you _sure_ you have the newest MDK? Because the error you show indicates that you still have the pre-15.8 MDK, which didn't work. The current MDK version is 1.1.25

**Comment by idapixl** [comment]
Hmm, It does seem that I had the old MDK V1.0.25 despite 'Check for Updates' saying it was the latest version. 

 Now attempting to install the vsix gives me this error:

![e72474fa-e183-11e6-82d8-b1f8df594d22](https://user-images.githubusercontent.com/8084809/44451378-7a50bb00-a5a8-11e8-9e3a-8806c8fdf366.png)

Log:

> 8/22/2018 12:54:30 AM - Microsoft VSIX Installer
> 8/22/2018 12:54:30 AM - -------------------------------------------
> 8/22/2018 12:54:30 AM - vsixinstaller.exe version:
> 8/22/2018 12:54:30 AM - 15.8.3237
> 8/22/2018 12:54:30 AM - -------------------------------------------
> 8/22/2018 12:54:30 AM - Command line parameters:
> 8/22/2018 12:54:30 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\Downloads\MDK (5).vsix
> 8/22/2018 12:54:30 AM - -------------------------------------------
> 8/22/2018 12:54:30 AM - Microsoft VSIX Installer
> 8/22/2018 12:54:30 AM - -------------------------------------------
> 8/22/2018 12:54:30 AM - Found setup instance 45636111 but not in launchable state.
> 8/22/2018 12:54:30 AM - Initializing Install...
> 8/22/2018 12:54:30 AM - Extension Details...
> 8/22/2018 12:54:30 AM - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
> 8/22/2018 12:54:30 AM - 	Name               : MDK/SE
> 8/22/2018 12:54:30 AM - 	Author             : Morten Aune Lyrstad
> 8/22/2018 12:54:30 AM - 	Version            : 1.1.25
> 8/22/2018 12:54:30 AM - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.
> 
> Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
> 8/22/2018 12:54:30 AM - 	Locale             : en-US
> 8/22/2018 12:54:30 AM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
> 8/22/2018 12:54:30 AM - 	InstalledByMSI     : False
> 8/22/2018 12:54:30 AM - 	SupportedFrameworkVersionRange : [4.6.1,)
> 8/22/2018 12:54:30 AM - 
> 8/22/2018 12:54:30 AM - 	SignatureState     : Unsigned
> 8/22/2018 12:54:30 AM - 	Supported Products : 
> 8/22/2018 12:54:30 AM - 		Microsoft.VisualStudio.Community
> 8/22/2018 12:54:30 AM - 			Version : [15.0]
> 8/22/2018 12:54:30 AM - 
> 8/22/2018 12:54:30 AM - 	References         : 
> 8/22/2018 12:54:30 AM - 		-------------------------------------------------------
> 8/22/2018 12:54:30 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
> 8/22/2018 12:54:30 AM - 		Name         : Visual Studio MPF 15.0
> 8/22/2018 12:54:30 AM - 		Version      : [15.0]
> 8/22/2018 12:54:30 AM - 		MoreInfoURL  : 
> 8/22/2018 12:54:30 AM - 		Nested       : No
> 8/22/2018 12:54:30 AM - 
> 8/22/2018 12:54:30 AM - 	Prerequisites      : 
> 8/22/2018 12:54:30 AM - 		-------------------------------------------------------
> 8/22/2018 12:54:30 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 8/22/2018 12:54:30 AM - 		Name         : Visual Studio core editor
> 8/22/2018 12:54:30 AM - 		Version      : [15.0,16.0)
> 8/22/2018 12:54:30 AM - 
> 8/22/2018 12:54:30 AM - 		-------------------------------------------------------
> 8/22/2018 12:54:30 AM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
> 8/22/2018 12:54:30 AM - 		Name         : Roslyn Language Services
> 8/22/2018 12:54:30 AM - 		Version      : [15.0,16.0)
> 8/22/2018 12:54:30 AM - 
> 8/22/2018 12:54:30 AM - Signature Details...
> 8/22/2018 12:54:30 AM - 	Extension is not signed.
> 8/22/2018 12:54:30 AM - 
> 8/22/2018 12:54:30 AM - Searching for applicable products...
> 8/22/2018 12:54:30 AM - Found installed product - Global Location
> 8/22/2018 12:54:31 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
>    at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> 

Thank you for your time! Any help is appreciated!

**Comment by malware-dev** [comment]
You did include the .NET Desktop Development module when you installed Visual Studio right?

**Comment by idapixl** [comment]
**[RESOLVED]**
_I did include the .Net Desktop  Development_ module at install but decided I should double check everything. Attempting to repair the VS install threw an error referencing that the install couldn't be found. 
 
Anyway, I did a **FULL** uninstall of VS using a third party tool to remove all files, reinstalled, and everything worked fine! Not sure what happened, but it definitely had to do with my install path.

I can't tell you how much I appreciate this toolkit and the work you have put into it! I am a novice programmer and have learned a lot from what you have done here. Thanks again!! Excited to get back working on my script!

**Comment by malware-dev** [comment]
Awesome! It's a pity VS has to be so finicky.

Glad you find it useful! Good luck with your script.
