### ISSUE TITLE
"Preserved" sections are fraught with new lines

### ISSUE THREAD

**Issue by jturp** [malware-dev/MDK-SE#86]
When deploying, sections marked as "mdk preserve" are not actually preserved. For instance, this:

```cs
#region mdk preserve
if (timer.CustomName.Contains(advTimerTagIn) || timer.CustomName.Contains(advTimerTagOut)) {
  name = timer.CustomName;
  inTag = timer.CustomName.Contains(advTimerTagIn);
}
else if (timer.CustomData.Contains(advTimerTagIn) || timer.CustomData.Contains(advTimerTagOut)) {
  name = timer.CustomData;
  inTag = timer.CustomData.Contains(advTimerTagIn);
}
else continue;
#endregion
```

ends up looking like this:
```cs
if (timer.CustomName.Contains(
advTimerTagIn) || timer.CustomName.Contains(
advTimerTagOut)) {
name = timer.CustomName;
inTag = timer.CustomName.Contains(
advTimerTagIn);
}
else  if (timer.CustomData.Contains(
advTimerTagIn) || timer.CustomData.Contains(
advTimerTagOut)) {
name = timer.CustomData;
inTag = timer.CustomData.Contains(
advTimerTagIn);
}
else  continue;
```

From what I can gather, a newline is inserted after any / all open parens, brackets, or commas.

**Comment by Der-Isy** [comment]
The preserve function also adds additional spaces:

```csharp
#region mdk preserve
string test = "Hello World!";
#endregion
```

becomes:

```csharp
string  test = "Hello World!";
```
(two spaces between string and test instead of one)

**Comment by malware-dev** [comment]
I haven't forgotten this issue, don't worry. It just hasn't been of the highest priority. I think I will be able to do this the next time I can work on MDK. I _will_ fix it, I promise 😄

**Comment by Der-Isy** [comment]
I wasn't referencing to #68 - no worries.. Just another small thing I noticed that doesn't really hurt anyone ;)

**Comment by malware-dev** [comment]
I understood this, I was literally talking about _this_ issue... which _does_ "hurt", look at the other example up there... The preserve really doesn't really, um, preserve...
