### ISSUE TITLE
MDK.options causes Access Denied errors during deployment.

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-SE#89]
Reproduction:
1. Create a project which deploys correctly on one user account.
2. Open the same project on a different user account.
3. Attempt to deploy the MDK script.

Expected Behaviour:
Project deploys to the AppData\Roaming\SpaceEngineers\IngameScripts\local folder of the currently active account.

Actual:
The script deployment fails with an Access Denied error.

Cause:
MDK.options parser doesn't correctly expand environment variables like %APPDATA%, all paths are hard-coded.
This means attempting to run a project on a computer/user account where the AppData folder isn't under the same user directory as the original author will cause an Access Denied error during deployment.

**Comment by malware-dev** [comment]
It doesn't expand environment variables because it was never designed to, the concept never even entered my mind to _try_ ;)
