### ISSUE TITLE
Closing bracket of class from another file gets placed in front it instead of after it when deploying

### ISSUE THREAD

**Issue by Der-Isy** [malware-dev/MDK-SE#94]
I have frequently used methods for several scripts in a Extensions.cs file. When deploying a script, the content of the file gets appended to the script but the closing bracket of the class gets placed in front of it instead of after it.

Used version of VS: 15.8.6
Used version of MDK: 1.1.28

Basically:
```csharp
public static class Extensions
{
    // Methods
}
```

Becomes:
```csharp
}
public static class Extensions
{
    // Methods
```

Even when placing the Extensions class directly in the script file, the closing bracket is at the wrong place.

Here's a little demonstration script, that shows the error. Just open it, deploy it and see the result:
https://www.dropbox.com/s/3zyhphldm53oyyo/MDKBracketError.zip?dl=1

**Comment by malware-dev** [comment]
After live discussion with Isy: This behavior is as defined and expected.
