### ISSUE TITLE
Reduce code size by merging partial class definitions.

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-SE#95]
An idea for a useful enhancement.

Currently having two files:

UtilityClass.Part1.cs

```C#
public partial class UtilityClass
{
	public void UtilityFunction1() { }
}
```

UtilityClass.Part2.cs
```C#
public partial class UtilityClass
{
	public void UtilityFunction2() { }
}
```

will generate the following output in the final script.cs file:

```C#
public partial class UtilityClass
{
	public void UtilityFunction1() { }
}

public partial class UtilityClass
{
	public void UtilityFunction2() { }
}
```

Merging the two partials generates the following:

```C#
public partial class UtilityClass
{
	public void UtilityFunction1() { }
	
	public void UtilityFunction2() { }
}
```

This is a saving of 33 characters in this very small example.

In my project I am using a partial class as a pseudo namespace for some extra functionality, this means I have 33 declarations of:
```C#
partial class Serialization
{
	// Subclass
}
```

Merging these into a single class during compilation would result in a saving of almost 1000 characters.

**Comment by malware-dev** [comment]
This represents a potentially significant workload I cannot promise I can provide, not any time soon anyway. I also consider using partials like this... well... I don't see the point. Why on earth would you need _namespaces_ in something as small as a script? You can easily write your code in a way that won't result in this sizing issue.

I will not outright reject it, not yet, but this is an extreme edge case and currently I don't want to spend time on such things. I'm sorry.

**Comment by Der-Isy** [comment]
Welcome to the club of "edge cases" ;) As you know with my latest isse #93 I'm also a fan of this ;) So thumbs up for this idea!

**Comment by malware-dev** [comment]
I _will_ consider merging a PR with this support. Would have to be in the type stripper and/or minifier, not default. But I don't have the time.

**Comment by kwilliams1987** [comment]
I have a feeling this will need to take place somewhere around [Source/MDK/Build/Solution/ProgramDocumentComposer.cs#L107](https://github.com/malware-dev/MDK-SE/blob/master/Source/MDK/Build/Solution/ProgramDocumentComposer.cs#L107), after the individual ScriptParts are generated, and before returning the ProjectContent.

**Comment by malware-dev** [comment]
The default generator shouldn't do any major changes to the code.

**Comment by kwilliams1987** [comment]
>           The default generator shouldn't do any major changes to the code.

While I certainly agree with this sentiment, does this classify as a "major code change"?
In essence it's just a very clever Regex.

**Comment by malware-dev** [comment]
It's a major code change to the _source script_. The default generator should only do the absolutely necessary changes to the source script. This is not an absolutely necessary change. If you want this feature, it must be included in either the typestripper module (which is my recommendation) or the minifier, both which is designed to and understood to make changes to the source script.

**Comment by kwilliams1987** [comment]
A fair point, I will keep looking. 👍

**Comment by malware-dev** [comment]
OK so


you _may_ be getting your wish on this one. I'm working on a backend update, I _may_ add this feature in at the same time. Can't promise anything though, it depends on how complicated it gets, but I'll add it to the worklist at least.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
