### ISSUE TITLE
debug code support

### ISSUE THREAD

**Issue by modom** [malware-dev/MDK-SE#97]
Support marking of some lines of code as debug-only.
Some kind of simple preprocessor.
For example like in C/C++:
```
#ifdef DEBUG
Echo("Debug Code here.");
#endif
```
or any other type of marking (for example; ```//@debug``` to mark the line as debug, and/or ```//@debug-begin``` ```//@debug-end``` to mark the debug code section inbetween).

The inclusion/exclusion during deployment of debug code should be selectable in MDK options.

_If marked wrongly, this **might** cause some code being undeployable in debug or release configuration - however that's problem of use, nothing to take care of in MDK (only if it would be easy to implement warning)._

**Comment by kwilliams1987** [comment]
Doesn't the `#if DEBUG` convention already work for this?

**Comment by malware-dev** [comment]
It should use the traditional #if DEBUG, yes, but I believe the request is about actually removing the debug code from deployment. 

This is a common use case and is essentially an extension of the .debug.cs feature., so it might be considered, especially if it's to be an option. I cannot promise anything at this time though.

**Comment by modom** [comment]
@malware-dev @kwilliams1987 Yes, sorry I didn't wrote it specifically - removal of debug code is the aim of this request :)

**Comment by hades200082** [comment]
I'd prefer if it simply worked with the existing `if DEBUG` syntax

**Comment by swarr** [comment]
Seems that MDK does not use symbols defined in project, as a workaround - symbol could be defined in start of each file by code:
`#define DEBUG`

It would be great if any symbols defined in project properties would be used, this will allow to turn on/off debug code by just configuring proper symbols in project.

**Comment by malware-dev** [comment]
MDK is just a publisher. Any support like this has to be _explicitly made_ to actively remove code within such sections, and that's more effort that I'm ready to put into this at this point. The actual interpretation of the published code is fully up to SE, not MDK.

**Comment by malware-dev** [comment]
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.
