### ISSUE TITLE
Unimportant Non-SE Project Error

### ISSUE THREAD

**Issue by Skimt** [malware-dev/MDK-SE#98]
I'm working over FTP (Web site / FTP site), on a project unrelated to SE, when I receive the following error. Presumably because so long as the MDK is an extension of VS, it will always try to figure out what the project is or where the project files are located at ("\AppData\Local\Temp\VWDWebCache\" FTP cache files). 

> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Malware.MDKServices.ProjectScriptInfo.Load(String projectFileName, String projectName)
   at Malware.MDKServices.ScriptUpgrades.AnalyzeProject(Project project, ScriptUpgradeAnalysisOptions options)
   at Malware.MDKServices.ScriptUpgrades.<>c__DisplayClass13_1.<AnalyzeAsync>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Malware.MDKServices.ScriptUpgrades.<AnalyzeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<OnSolutionLoaded>d__49.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 266

Another possibility is that it's trying to work out the following in the solution file: 
> Debug.AspNetCompiler.VirtualPath = ""
> Debug.AspNetCompiler.PhysicalPath = ""

I consider it unimportant because the error doesn't affect anything other than the extension which I'm not using on these types of projects.

**Comment by malware-dev** [comment]
Oh! Ok, I think I can probably fix that although I haven't really got any way to test it. Thank you.

**Comment by malware-dev** [comment]
I know it's been a while, but... do you have an example of exactly what this path it's trying to load looks like? I don't have a way to reproduce.

**Comment by malware-dev** [comment]
I don't understand this. Given the error message, the path given to MDK needs to have invalid characters or format of some sort, and none of your examples show this. Which means that whatever is fed to MDK by VS is not what you show here.

**Comment by Skimt** [comment]
Here's the content of the FTP project file

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.28010.2003
MinimumVisualStudioVersion = 10.0.40219.1
Project("{E24C85DC-7377-472B-9ABA-BC803B73C61A}") = "my.domain.name", "ftp://my.host.name/my.domain.name", "{6771A81D-EF46-4EB0-A49F-B4F330F77EA3}"
	ProjectSection(WebsiteProperties) = preProject
		TargetFrameworkMoniker = ".NETFramework,Version%3Dv4.0"
		Debug.AspNetCompiler.VirtualPath = "/my.domain.name"
		Debug.AspNetCompiler.PhysicalPath = "..\..\..\AppData\Local\Temp\VWDWebCache\my.host.name_my.domain.name_myUserName\"
		Debug.AspNetCompiler.TargetPath = "PrecompiledWeb\my.domain.name\"
		Debug.AspNetCompiler.Updateable = "true"
		Debug.AspNetCompiler.ForceOverwrite = "true"
		Debug.AspNetCompiler.FixedNames = "false"
		Debug.AspNetCompiler.Debug = "True"
		Release.AspNetCompiler.VirtualPath = "/my.domain.name"
		Release.AspNetCompiler.PhysicalPath = "..\..\..\AppData\Local\Temp\VWDWebCache\my.host.name_my.domain.name_myUserName\"
		Release.AspNetCompiler.TargetPath = "PrecompiledWeb\my.domain.name\"
		Release.AspNetCompiler.Updateable = "true"
		Release.AspNetCompiler.ForceOverwrite = "true"
		Release.AspNetCompiler.FixedNames = "false"
		Release.AspNetCompiler.Debug = "False"
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{6771A81D-EF46-4EB0-A49F-B4F330F77EA3}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6771A81D-EF46-4EB0-A49F-B4F330F77EA3}.Debug|Any CPU.Build.0 = Debug|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {90E8BD3D-8F31-48D6-BDB1-E6C2393BACF9}
	EndGlobalSection
EndGlobal
```

This project file is stored on my OneDrive cloud. When I load it, it will open and display the contents of my.domain.name in Visual Studio solution explorer, but not download any files in my.domain.name until I've clicked to view any of those files specifically. Meaning, the `"\my.webhost.domain_my.website.domain_myUserName"` folder can be empty, because Visual Studio treats those files as if they are cache files. It's not until you've opened/downloaded a specific file, and then choose to save/upload the changes you've made, that Visual Studio requires the cache file. I can't make much sense of it neither, but I'm presuming it's because of the way FTP projects work contra ordinary projects. 

Can you make the MDK ignore projects that contain `"ftp://"`?

The line I'm looking at is: 
`Project("{E24C85DC-7377-472B-9ABA-BC803B73C61A}") = "my.domain.name", "ftp://my.host.name/my.domain.name", "{6771A81D-EF46-4EB0-A49F-B4F330F77EA3}"`

In normal C# project this line looks like: 
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyProject", "MyProject\MyProject.csproj", "{8F3EAD3C-A4B3-4BEF-8D32-CCEEB298F13D}"`

I really should sit down one day and get to know the MDK source code, but I'm just so busy with school these days. I'm taking "voksenopplæring" which is basically like three years of high school compressed into one year, and then I'm going for bachelor in software engineering after that. On top of that I'm preparing to start a business, while I go to school. I don't sleep.

**Comment by malware-dev** [comment]
Oh that's right, you're Norwegian too, I forgot that 😁 I'll still stick to English though, since other people might hit the same issue before I can release a new version.

Ok, then I will assume that the path being sent to MDK is an URL, I can filter for that easily enough. At least it won't be any _worse_ than it is now.

**Comment by kwilliams1987** [comment]
Could be caused by the project name being an FTP path?

**Comment by malware-dev** [comment]
That's the current theory, yes. I've added in a check to see if it's an URL as opposed to a file path.
